### ISSUE TITLE
Audible feedback whenever user executes an action

### ISSUE THREAD

**Issue by WesleyPolicena** [TheOfficialFloW/VitaShell#103]
Audible feedback (Tick) when you press a button, like the PSP

[Example - Google Drive](https://drive.google.com/file/d/0BzmkBUkhmZFAZ3k3TjBtVXB5dkU/view?usp=sharing)

**Comment by limyz** [comment]
Not sure if it irritates users but probably can be included in options.

**Comment by WesleyPolicena** [comment]
Good

**Comment by limyz** [comment]
Merged to #96.
