### ISSUE TITLE
Splash screen

### ISSUE THREAD

**Issue by littlebalup** [TheOfficialFloW/VitaShell#106]
Heavy theme make some time to display. A splash screen may be cool.

**Comment by TheOfficialFloW** [comment]
I will consider adding this if there's also a settings menu to disable it

**Comment by littlebalup** [comment]
Make sense

**Comment by littlebalup** [comment]
now there is : https://github.com/TheOfficialFloW/VitaShell/blob/master/pkg/sce_sys/pic0.png

**Comment by littlebalup** [comment]
![pic0](https://cloud.githubusercontent.com/assets/6732619/19131654/98cac96e-8b50-11e6-8f57-a65d25b54bca.png)

**Comment by WesleyPolicena** [comment]
I also want to play :)

![splash-screen](https://cloud.githubusercontent.com/assets/21372797/19234727/ea76718e-8ec3-11e6-9574-e5f3be49866a.gif)

**Comment by TheOfficialFloW** [comment]
VitaShell is meant to be quickly accessible, a splash screen would slow down the startup, so I'm not going to add it.
