### ISSUE TITLE
in app theme customization.

### ISSUE THREAD

**Issue by Dimkar3000** [TheOfficialFloW/VitaShell#107]
I'd like more theme changing abilities in app. The text editor can change a theme but those are hard edits. Maybe when a theme is loaded, it should be stored seperatly. This way we can mod the running theme without destroying the original. Also we could have a theme settings section in menu where we can easily change some values like text color, background color, text size... Maybe a color picker, and an export function for the custom theme. This will also make it easier to create themes. If you want to take it to the extreme, you can create background images from PNGs stored on the vita. 

The finale line is that I would like a theme creator inside the vita shell 😄

**Comment by limyz** [comment]
Refer to #7.
