### ISSUE TITLE
Font doesn't support Simplified Chinese

### ISSUE THREAD

**Issue by jack980517** [TheOfficialFloW/VitaShell#108]
It supports Japanese Kanji and Traditional Chinese well, but Simplified Chinese-only characters are displayed as `_`. You can see this when viewing param.sfo files. For example, the Simplified Chinese name for "manual" in the system is `说明书` which is displayed as `_明_`.

**Comment by littlebalup** [comment]
Could you give me your simplified chinese translation? I'll see if it works with a custom pgf.

**Comment by jack980517** [comment]
Do you mean the UI text translation? There is one in the xy2iii/vitashell-themes repo already, although I'm not using Simplified Chinese as my system language so I don't know if it would work. My system language is English. I only discovered this problem when viewing param.sfo files.

**Comment by littlebalup** [comment]
To test it, you can rename the simplified chinese ui translation as english_us.txt and replace in the language folder.
Anyway, I'll have a look.

**Comment by jack980517** [comment]
I know, Simplified Chinese is my native language... I just didn't bother downloading the translation files since I know English well enough for these UI text lol

I'm now at school and can't test until 4hr later so probably you would get the result faster.

**Comment by jack980517** [comment]
Still managed to use the vita... And here it is: ![Screenshot of Simplified Chinese UI](http://imgur.com/a/5k6jT)

**Comment by littlebalup** [comment]
I confirm, there is some missing characters.
example : `确` that is u786E
Same case for `说` u8BF4 and `书` u4E66
Those chars are not mapped in the jpn0.pgf default font table.
List of available unicode chars:  [char_map.txt](https://github.com/TheOfficialFloW/VitaShell/files/496963/char_map.txt)

I'm able to replace already mapped latin characters. I don't know if/how we can map new char...

**Comment by jack980517** [comment]
I'm curious though, why are those characters not included? The PSV system itself supports Simplified Chinese very well.

P.S.: not sure if I should create another issue for this, but when renaming files with Chinese characters (no matter simplified or traditional; probably for all non-ASCII chars, haven't tested), the name appearing in the textbox stripped all Chinese characters in the filename, and after pressing confirm, the saved new file name doesn't contain those characters either.

**Comment by littlebalup** [comment]
vitashell use pgf font that is legacy PSP font. PSV system uses other pvf fonts (ttf fonts...)

**Comment by littlebalup** [comment]
it works great using ttf_pgf to make a custom pgf: 
![2016-09-28-053943](https://cloud.githubusercontent.com/assets/6732619/18900095/a0a38080-853e-11e6-8310-14f0b57d021f.jpg)

**Comment by jack980517** [comment]
But PSP has Simplified Chinese support too.. So you just didn't take the Simplified Chinese part?

**Comment by limyz** [comment]
VitaShell's code currently has no provision for non-UTF characters. As such, renaming files with such characters will be stripped of their output. As said, VitaShell works great from a custom pgf, probably we need Simplified Chinese ttfs to make it work.

**Comment by jack980517** [comment]
Try [Wen Quan Yi](http://wenq.org/en). It's open source and shouldn't have licensing problems.

**Comment by limyz** [comment]
Placing it here for personal reference:
https://github.com/adobe-fonts/source-han-sans
https://www.freedesktop.org/wiki/Software/CJKUnifonts/

**Comment by littlebalup** [comment]
I'll make those fonts as pgf and pull them over @xy2iii repo.

**Comment by jack980517** [comment]
Custom font still doesn't work in 1.31, nor is xy2iii/vitashell-themes updated... When would this be implemented... QuQ

**Comment by littlebalup** [comment]
@TheOfficialFloW  commented the code for custom fonts support:

> TheFloW: I am using a modified vita2dlib that doesn't have this function yet
>  and I'm too lazy to update mine. Will do it in the future.

**Comment by WanderMax** [comment]
Hi,
I find PSV new font type in sa0:/data/font/pvf , the font files in this folder is big enough to support all characters. I hope it can be helpful for this topic.

**Comment by littlebalup** [comment]
pvf is similar to ttf. Vitashell uses pgf font format since v0.4 if I remember well. It could be changed again of course. @TheOfficialFlow to make the decision.

**Comment by WanderMax** [comment]
Yes, I find that size of cn1.pvf file is big enough to support Simplified Chinese characters, maybe pvf files can support more than pgf for non-ASCII characters.
Thanks.

**Comment by littlebalup** [comment]
pgf can support it as well but need custom one. I made some and pushed on the xy2iii git days ago. We are waiting official custom pgf support to merge them and close this issue.

**Comment by WanderMax** [comment]
thanks, pvf font support (if it can display all characters) can make use of system embedded font, however, for pgf support , users can custom font they like. both are OK.
thanks again.

**Comment by TheOfficialFloW** [comment]
http://pastebin.com/0K0vD00e that's the code I'm using, maybe anybody else is motivated enough to integrate it to the vita2dlib

**Comment by TheOfficialFloW** [comment]
The reason I'm not using pvf is that it looks ugly to me xD

**Comment by d3m3vilurr** [comment]
@TheOfficialFloW actually already merged :) https://github.com/xerpi/libvita2d/pull/30
https://github.com/d3m3vilurr/vita-savemgr/blob/e5cc7fa/src/font.c

**Comment by TheOfficialFloW** [comment]
There's more than that:
* lwmutex lock/unlock needed for multithreading
* the utf32 conversion commited by endrift breaks strings in vitashell

**Comment by jack980517** [comment]
Some new info I just found on this:
The Simplified Chinese-only characters are not in `jpn0.pgf` indeed, but they're in `gb3s1518.bwfon`. However the `bwfon` file seems to be in a different format than `pgf` files. If you can find a way to read `bwfon` files, custom font support shouldn't be necessary to display Chinese text properly.

What I did:
I first used littlebalup's `WenQuanYiMicroHei.pgf` to substitute `jpn0.pgf`, and found that only the Japanese font was changed, but the Chinese font was not. And then I used WQYMH to substitute the bwfon file instead, and all Simplified Chinese-only characters displayed as garbage.

**Comment by TheOfficialFloW** [comment]
https://drive.google.com/file/d/0B8d0Wy4mDFrGOGNjd0ktVm9PYTg/view?usp=sharing

This one has got custom font support, may you guys test it?

**Comment by WanderMax** [comment]
maybe you should recommend the convert tool
