### ISSUE TITLE
Promote uncompressed VPK

### ISSUE THREAD

**Issue by gusmanb** [TheOfficialFloW/VitaShell#109]
Hi.

First of all, I'm not sure if this can be done now, if it's possible then I would like to know how to promote an uncompressed package. Else, this would be a very good addition for some cases.

Let me explain the situation and the purpose of this: I'm creating (another) FTP app manager for Vita and I want to save as much space as possible.

Think of this case, you have an 8Gb card, some games are eating 3 Gb and you want to install a game which is 4Gb of size once installed, if the installer already uses 3Gb (per example) then, even if you have enough space left when the game is installed you can't install it.

I already have the program working, it decompresses the VPK in memory, reads the param.sfo to retrieve the title id and title name, it recreates the folder structure in the app folder and copies all the files, just need to promote the installed app. 

Cheers.

**Comment by coddoge** [comment]
Unzip vpk, select  `sce_xxx` `xxx.sprx` `eboot.bin` files, include dir struct zip and rename to vpk.
Ftp to stick and install.

After install , shoult get dir in `ux:/app/xxxx_xxxxxx/`
Manual ftp remain files to that.

**Comment by limyz** [comment]
Refer to https://github.com/soywiz/vitaorganizer. Issues #38 and PR #43 addresses what you may want.

**Comment by gusmanb** [comment]
Thanks a lot for the info, that makes sense.

Cheers.
