### ISSUE TITLE
Compress/Packer in VPK and/or ZIP and/or RAR

### ISSUE THREAD

**Issue by MrCampy** [TheOfficialFloW/VitaShell#110]
Be able to compress/packer in any of the above file name extensions (VPK, ZIP, RAR) to facilitate the passage of large folders through the QCMA. Ex: Once created the compressed/packed file can be renamed to MP4 and passed to the PC by the content manager.

**Comment by TheOfficialFloW** [comment]
I will do it

**Comment by WanderMax** [comment]
@TheOfficialFloW @littlebalup Could you tell me the compress level when creating the archive? Is it level C0?  I don't know why compress speed is not that fast.

**Comment by TheOfficialFloW** [comment]
It's set to default. Around C6. C0 would be store only.

**Comment by WanderMax** [comment]
@TheOfficialFloW C6 is too slow as PSV's CPU is not that powerful and external memory is not that fast. I need so much time to compress files into .zip file. I hope you can improve this, maybe set to C2 or lower or give options/different command(sub menu to set compress speed) to creating the archive. Thanks.

**Comment by WanderMax** [comment]
@TheOfficialFloW For compress speed, fast-->C0, normal-->C2, slow-->C6, or others. Thanks.

**Comment by TheOfficialFloW** [comment]
Added:
https://github.com/TheOfficialFloW/VitaShell/commit/4119bb01ac08b5d11bffa9e5af987d0b4d96f085
