### ISSUE TITLE
Align the partition used/total text

### ISSUE THREAD

**Issue by limyz** [TheOfficialFloW/VitaShell#112]
As requested by @TheOfficialFloW

**Comment by littlebalup** [comment]
Something not very elegant but simple without braking anything:

`if (dir_level == 0) {
    pgf_draw_text(ALIGN_LEFT(INFORMATION_X, vita2d_pgf_text_width(font, FONT_SIZE, "000.00 MB / 000.00 MB")), y, color, FONT_SIZE, str);
}else{
    pgf_draw_text(ALIGN_LEFT(INFORMATION_X, vita2d_pgf_text_width(font, FONT_SIZE, str)), y, color, FONT_SIZE, str);
`
where "000.00 MB / 000.00 MB" is the worst length and will format the alignment, taking in account font parameters.
We can do the same for files information but we can't for the language_container[FOLDER] as it depends of the translation as well.

Let me know if you agree the principle and I'll push it.

**Comment by TheOfficialFloW** [comment]
I'd rather align by x coordinate. 010.00 MB for example doesn't look nice

**Comment by littlebalup** [comment]
it will not show 010.00 MB but 10.00 MB as of today.
I mean it is not string format but string lenth format

**Comment by littlebalup** [comment]
![2016-10-04-205138](https://cloud.githubusercontent.com/assets/6732619/19088037/af27ac04-8a74-11e6-810c-f9b157f82eeb.jpg)

like this

**Comment by TheOfficialFloW** [comment]
By aligning used/total text I mean that 'used' and 'total' should be in different columns

**Comment by littlebalup** [comment]
oh! ok. I misunderstood. Sorry.

**Comment by littlebalup** [comment]
Something like that?
![2016-10-05-201836](https://cloud.githubusercontent.com/assets/6732619/19125927/2eab2590-8b39-11e6-9552-e36031c1c693.jpg)

```
			// File information
			if (strcmp(file_entry->name, DIR_UP) != 0) {
				if (dir_level == 0) {
					char free_size_string[16], max_size_string[16];
					int max_size_x = ALIGN_LEFT(INFORMATION_X, vita2d_pgf_text_width(font, FONT_SIZE, "000.00 MB"));
					int separator_x = ALIGN_LEFT(max_size_x, vita2d_pgf_text_width(font, FONT_SIZE, " / "));
					int free_size_x = ALIGN_LEFT(separator_x, vita2d_pgf_text_width(font, FONT_SIZE, "000.00 MB"));
					if (file_entry->size != 0 && file_entry->size2 != 0) {
						getSizeString(free_size_string, file_entry->size2 - file_entry->size);
						getSizeString(max_size_string, file_entry->size2);
					} else {
						strcpy(free_size_string, "-");
						strcpy(max_size_string, "-");
					}
					pgf_draw_text(max_size_x, y, color, FONT_SIZE, max_size_string);
					pgf_draw_text(separator_x, y, color, FONT_SIZE, " /");
					pgf_draw_text(free_size_x, y, color, FONT_SIZE, free_size_string);
				} else {
					char *str = NULL;
					if (!file_entry->is_folder) {
						// Folder/size
						char string[16];
						getSizeString(string, file_entry->size);

						str = string;
					} else {
						str = language_container[FOLDER];
					}
					pgf_draw_text(ALIGN_LEFT(INFORMATION_X, vita2d_pgf_text_width(font, FONT_SIZE, str)), y, color, FONT_SIZE, str);
				}
```

**Comment by TheOfficialFloW** [comment]
Exactly! However both right-aligned. Thanks

**Comment by littlebalup** [comment]
Ok:
![2016-10-05-203708](https://cloud.githubusercontent.com/assets/6732619/19126608/dfa716f4-8b3b-11e6-9251-e1a0145f106d.jpg)
```
			// File information
			if (strcmp(file_entry->name, DIR_UP) != 0) {
				if (dir_level == 0) {
					char free_size_string[16], max_size_string[16];
					int max_size_x = ALIGN_LEFT(INFORMATION_X, vita2d_pgf_text_width(font, FONT_SIZE, "000.00 MB"));
					int separator_x = ALIGN_LEFT(max_size_x, vita2d_pgf_text_width(font, FONT_SIZE, " / "));
					// int free_size_x = ALIGN_LEFT(separator_x, vita2d_pgf_text_width(font, FONT_SIZE, "000.00 MB"));
					if (file_entry->size != 0 && file_entry->size2 != 0) {
						getSizeString(free_size_string, file_entry->size2 - file_entry->size);
						getSizeString(max_size_string, file_entry->size2);
					} else {
						strcpy(free_size_string, "-");
						strcpy(max_size_string, "-");
					}
					pgf_draw_text(ALIGN_LEFT(INFORMATION_X, vita2d_pgf_text_width(font, FONT_SIZE, max_size_string)), y, color, FONT_SIZE, max_size_string);
					pgf_draw_text(separator_x, y, color, FONT_SIZE, " /");
					pgf_draw_text(ALIGN_LEFT(separator_x, vita2d_pgf_text_width(font, FONT_SIZE, free_size_string)), y, color, FONT_SIZE, free_size_string);
				} else {
					char *str = NULL;
					if (!file_entry->is_folder) {
						// Folder/size
						char string[16];
						getSizeString(string, file_entry->size);

						str = string;
					} else {
						str = language_container[FOLDER];
					}
					pgf_draw_text(ALIGN_LEFT(INFORMATION_X, vita2d_pgf_text_width(font, FONT_SIZE, str)), y, color, FONT_SIZE, str);
				}

I push this?
```

**Comment by limyz** [comment]
I feel that ```/``` can be replaced with ```|```.

**Comment by littlebalup** [comment]
![2016-10-05-205733](https://cloud.githubusercontent.com/assets/6732619/19127249/80f00e24-8b3e-11e6-9e85-9b8f5ae3e453.jpg)

**Comment by limyz** [comment]
Does it look better? I would like to hear your insights as well.

**Comment by TheOfficialFloW** [comment]
Maybe a little bigger distance between the text and | would look better

**Comment by littlebalup** [comment]
![2016-10-05-210639](https://cloud.githubusercontent.com/assets/6732619/19127549/b9dbdd20-8b3f-11e6-8989-a9f6c3e1efc5.jpg)
