### ISSUE TITLE
What programs do you use to develop? :)

### ISSUE THREAD

**Issue by WesleyPolicena** [TheOfficialFloW/VitaShell#113]
I would like to help more in the project.

What programs do you use to develop and compile?

**Comment by TheOfficialFloW** [comment]
All the dependencies are listed in the readme document. To install vitasdk refer to the henkaku developer page, there's an simple tutorial.

**Comment by WesleyPolicena** [comment]
Thanks!!!  :grimacing::thumbsup:

**Comment by limyz** [comment]
Refer to https://github.com/TheOfficialFloW/VitaShell/wiki/Developers.
