### ISSUE TITLE
UI2 touch enhancement

### ISSUE THREAD

**Issue by littlebalup** [TheOfficialFloW/VitaShell#117]
to discuss about what can be even better:
- simple touch : show item information
- double touch : open item
- use back touch to scroll

**Comment by coderobe** [comment]
back touch for scrolling should be an opt-in setting in the upcoming settings menu, because i, and probably other people, find back touch annoying

**Comment by TheOfficialFloW** [comment]
I have decided to remove the UI2 code since it's not maintained properly.
