### ISSUE TITLE
INSTALL_WARNING crashes

### ISSUE THREAD

**Issue by mrsshr** [TheOfficialFloW/VitaShell#12]
Reproduce Steps

- change system language to 한국어 (Settings -> Language -> System Language)
- (maybe optional) delete all files in ux0:/VitaShell/language
- put attached korean.txt to ux0:/VitaShell/language
- install any package with extended permissions
- crashes after: '설치중...'

[lang_and_dump.zip](https://github.com/TheOfficialFloW/VitaShell/files/444967/lang_and_dump.zip)

**Comment by limyz** [comment]
Duplicates with #6
