### ISSUE TITLE
Prompt user if a virus is detected

### ISSUE THREAD

**Issue by limyz** [TheOfficialFloW/VitaShell#120]
- [ ] NID detection
- [ ] Prompt user

**Comment by damteenagers** [comment]
Listen, it is not theFlow0's job to add features like this. Its up to the user to install homebrews from reliable sources. Plus, there are no "virus's" on the vita. A virus has to infect other files, what your thinking of is malicious software on the vita which makes the vita perform weird stuff or malware for short.

**Comment by limyz** [comment]
Erm. This issue is requested by @TheOfficialFlow. Yes, it is the user's responsibility to ensure their sources are reliable. Do note this issue is an enchantment and may not be worked on.

**Comment by TheOfficialFloW** [comment]
Added small check in https://github.com/TheOfficialFloW/VitaShell/commit/e68933686a86cee1ec46fe47fbaa6f3bf4102153
