### ISSUE TITLE
Subdirectory sublevel limit?

### ISSUE THREAD

**Issue by iadlast** [TheOfficialFloW/VitaShell#122]
Does VitaShell have a hard limit for accessing any given subdirectory and its files depending on its depth level?

I ask because while manipulating the files for a game, I was unable to copy, delete or open them because I got a 0x80010016 error due to them being located in a folder ten levels below the root in ux0:, and the only way to do anything with these files was moving them to a higher sublevel depth.

**Comment by TheOfficialFloW** [comment]
VitaShell doesn't set this limit. It's Sony's file system.
