### ISSUE TITLE
Vitashell 1.31 displaying the "extended permissions" message on all vpks

### ISSUE THREAD

**Issue by dyerseve** [TheOfficialFloW/VitaShell#127]
On Vitashell 1.31 all vpks seem to have the extended permissions warning even if they have been marked safe. I was on 1.2 and had just transfered about 15 files over to the ps vita, I installed 2 files and then got the prompt to update to 1.31, after the update all the remaining files show that they have extended permissions. I transferred a file by ftp and same result, I made sure these were all marked safe in vitaorganizer before hand.
Did something change in 1.31 that would make these files come up that way?

**Comment by TheOfficialFloW** [comment]
What kind of vpks are they?

**Comment by dyerseve** [comment]
Maybe it's just total chance, i tried scummvm since i now that one is marked safe and it installed no problem. The vpks are a mix of vitamin 1.1 and 2.0 dumps, haven't installed them before so it's possible they're just "not right". Is there an easy way to rollback to 2.0 and try the same files there, then I'll know for certain if it's just my files.

**Comment by TheOfficialFloW** [comment]
Well they have got mai.suprx/steroid.suprx and those are unsafe...

**Comment by dyerseve** [comment]
That is correct, so working as designed then. Thanks.

**Comment by TheOfficialFloW** [comment]
The reason for this additional check is that the last bricker was distinguished as mai.suprx..
