### ISSUE TITLE
Request feature: Restart VitaShell

### ISSUE THREAD

**Issue by WesleyPolicena** [TheOfficialFloW/VitaShell#129]
Add the toolbox or in the future settings menu, the feature **restart VitaShell**

to apply themes or simply restart the application for example

**Comment by littlebalup** [comment]
I'm not sure that is possible to restart an application without to launch an intermediate application (like the updater). In other words, we can start an application from another but not from itself as it is already running.
Anyway, we should be able to reload theme, langage, font... without to close vitashell.

**Comment by theorywrong** [comment]
if you want to apply themes change, you have just to trigger loadTheme function

**Comment by littlebalup** [comment]
yea but will crash vitashell if reloaded 3-4 times. Memory issue probably.

**Comment by TheOfficialFloW** [comment]
You need to free the resources first of course.

**Comment by TheOfficialFloW** [comment]
https://github.com/TheOfficialFloW/VitaShell/commit/49e6b9b8988ebf1a2fd2de0474ae1c5a64167757
