### ISSUE TITLE
[FTP] APPE - 502 Command not implemented

### ISSUE THREAD

**Issue by dude22072** [TheOfficialFloW/VitaShell#13]
FileZilla returns a 502 when attempting to use the APPE command.

**Comment by limyz** [comment]
Can you try using resume instead? Filezilla GUI does not show options to append files.

**Comment by StepS-** [comment]
I believe your vita went into sleep mode, then you woke it up, and FileZilla tried to append the rest of the file as it lost the connection. This is not supported at the moment and has to be reported to https://github.com/xerpi/ftpvitalib.

**Comment by dude22072** [comment]
> Can you try using resume instead? Filezilla GUI does not show options to append files.

I am using FilaZilla GUI.
>I believe your vita went into sleep mode, then you woke it up, and FileZilla tried to append the rest of the file as it lost the connection. 

My vita did not go into sleep mode, but filezilla is losing connection, I believe it's a poor connection issue.

**Comment by limyz** [comment]
This is not an issue with VitaShell and probably will not see an fix soon. Refer to https://github.com/xerpi/libftpvita/blob/master/libftpvita/ftpvita.c#L945.

Bring the vita nearer to your access point to prevent connection drops.

**Comment by persona5** [comment]
Actually, I've made a temporary fix for this, and it is already in the master of libftpvita . Refer to 
https://github.com/xerpi/libftpvita/pull/12

I have implemented APPE and REST, (and FEAT, i don't know why but RFC for ftp extensions said I need to do it, I guess it is so client would know that server supports resume).

It is not super reliable, but I did many tests - disabled wifi or quit app in the middle of transfer - and after resume it completed successfully, with copied file being byte-to-byte identical to original. 

Please link it against current master or libftpvita and test if you want.

**Comment by limyz** [comment]
I managed to replicate the problem by getting VitaShell to suspend then going back in. Doing so will the client will send a REST then the APPE commands. Yep, looks like we need an update to VitaShell soon.

**Comment by TheOfficialFloW** [comment]
Fixed in 0.9
