### ISSUE TITLE
Implement advanced vpk install option.

### ISSUE THREAD

**Issue by damteenagers** [TheOfficialFloW/VitaShell#132]
Say on the Dialog that appears on when pressing triangle;
In advanced options; have a setting for users to do shit with vpks.
Then have different options for installing vpk suchas;
"Path to install"
"Change app name/icon before installing"
"Remove vpk after installation"
thnx.
Flow I appreciate all the good work you did; many aspire to have half the amount of skill you demonstrated.

**Comment by limyz** [comment]
Merged to #96.
