### ISSUE TITLE
Add write protection for system folder

### ISSUE THREAD

**Issue by WanderMax** [TheOfficialFloW/VitaShell#135]
Hi, 
Could you please add write protection for system folders, like write action warning popup in PSV all drives except ux0.
Thanks.

**Comment by TheOfficialFloW** [comment]
Thanks for the suggestions, but honestly, please change the way you express yourself. We are not a McDonald where you can simply order things

**Comment by WanderMax** [comment]
OK, edited.
Sorry, I type in these content via my phone.
Thanks again.

**Comment by TheOfficialFloW** [comment]
Not neccessary, there's already safe/unsafe mode
