### ISSUE TITLE
Missing libs?

### ISSUE THREAD

**Issue by Yamigami** [TheOfficialFloW/VitaShell#137]
/usr/local/vitasdk/bin/../lib/gcc/arm-vita-eabi/4.9.3/../../../../arm-vita-eabi/bin/ld: cannot find -lonig

Can you tell me what i am missing? I installed all of the required deps

**Comment by TheOfficialFloW** [comment]
Obviously libonig. See the readme

**Comment by limyz** [comment]
Also, refer to the wiki.
https://github.com/TheOfficialFloW/VitaShell/wiki
