### ISSUE TITLE
NLST command for FTP server

### ISSUE THREAD

**Issue by kwyxz** [TheOfficialFloW/VitaShell#139]
Hello and thank you for your amazing work,

I have been working on a pet project to write a simple Python program that would manage roms / playlists with RetroArch on a remote Vita and wondered if the FTP server integrated with VitaShell could handle the NLST command? The LIST command works fine but having NLST would make browsing much much easier.

Thank you for your consideration and best regards,

**Comment by limyz** [comment]
The FTP server is handled by https://github.com/xerpi/libftpvita, not by VitaShell. You may include custom commands into the project to allow your project to interface with it.
