### ISSUE TITLE
C2-12828-1 error when booting up vitashell/moleculeshell

### ISSUE THREAD

**Issue by SpookTheSkeleton** [TheOfficialFloW/VitaShell#14]
So yeah , after i install vitashell and press on the bubble i get this message: (C2-12828-1) Saved Core File Succeeded ux0:data/psp2core-xxxxxxxxxx-eboot.bin.psp2dmp.
I can't really boot up the shell.
Seems like it's a problem with ux0:data/ files being saved.

**Comment by limyz** [comment]
Have you tried to remove moleculeshell then reattempt to install Henkaku again?

**Comment by limyz** [comment]
@SpookTheSkeleton Will close issue due no reply. Suspect problem caused by corrupted themes.

**Comment by joshua12378** [comment]
i have the same problem but this time is when i install hencore and download vitashell the hencore start right but when i go to start vita shell give me this error ux0:data/psp2core-1533798257-0x00003335b-eboot.bin.psp2dmp i do everything format the memory card format the psvita rebuild database reinstall hencore and download again vitashell but the problem persist anyone can help me please thankyou

**Comment by cursai** [comment]
did you ever solve this Johua, i have the same issue

**Comment by TheOfficialFloW** [comment]
@cursai
Can you somehow send me the files at the directory ux0:VitaShell?

**Comment by cursai** [comment]
Hey. i cant access ux0: at all. Neither Vitashell or molecularshell work. 
im  trying this https://www.reddit.com/r/vitahacks/comments/83qz40/help_cant_install_vitashell_in_365_ens%C5%8D/dvjxsr3/  

and this https://www.reddit.com/r/VitaPiracy/comments/83rb8x/cant_install_vitashell_on_365_error_0x80010016/
at the moment.

**Comment by TheOfficialFloW** [comment]
@cursai try launching vitashell and hold L trigger (quite tricky to achieve the perfect moment) try a few times. If it boots successfully, please send me the vitashell folder then.

**Comment by cursai** [comment]
No. its wont boot past the eror screen. Gonna try accessing my ux:o from a backup  of the offical memory card. (dont know if thats any help).

**Comment by cursai** [comment]
I cant get access to ux0:Vitashell from decrypting the memory card backup with psvimgtools. There is a ux0:data/vitashell. dont know if thats relevant. Anuhow i deleted that folder and the patch/vitashell folder. it did nothing but make my psn games corrupt.

**Comment by TheOfficialFloW** [comment]
Can you send me the crash dumps though?

**Comment by cursai** [comment]
Of course. Thanks for the help by the way. How do i access those. I can see the error history in settings but how do i export them?

**Comment by TheOfficialFloW** [comment]
They should be at ux0:data, can you access them using psvimgtools?

**Comment by cursai** [comment]
Afraid not, inclued a screenshot of my backup. [https://imgur.com/a/yyxiSTW](url)

**Comment by cursai** [comment]
So frustrating trying to fix this. Soooo many emulators lost. Thumps chest in rage

**Comment by TheOfficialFloW** [comment]
You formatted ms?

**Comment by cursai** [comment]
Yep. ive done that a few times. and restoring and rebuilt database a few times. Also reinstalled firmware. As recent as yesterday. Installed Vitashell again a good many times too.

**Comment by TheOfficialFloW** [comment]
And it still doesn‘t work? That‘s fucked up hmm

**Comment by cursai** [comment]
yeahits headwrecking. thats why i came to the official flow chat for help. after trying other methods.

**Comment by cursai** [comment]
stupid question. does the formatting and restoring, rebuilding and even reinstalling firmware reset the vita and memory card fully. Or are there traces left that might softbrick.

**Comment by cursai** [comment]
bump. should i just give up or is there anything i can provide to help?

**Comment by shouldershimmy** [comment]
Hey. Im having the same issue hencore works and downloads the vitashell no problem gets the c2- 12828-1 error as well, i think it has something to do with tai folder duplication in uxo and uro.

**Comment by seacrysos60** [comment]
bump. Getting same issue when using trinity and opening vitashell

**Comment by shouldershimmy** [comment]
Geez. No luck for me then .even downgrading to 3.60 and doing the xyz hack.i still get the error and could not open vita shell or molecular shell

**Comment by seacrysos60** [comment]
It turns out it's actually a few applications that give me that error. I managed to downgrade to 3.60, install enso and even get a sd to vita card working. However, even when I use my micro SD card as my memory card I'm still getting the same error message. Really strange

**Comment by guille1986** [comment]
hi, I´m new here, ps vita 1000 was working smooth with henkaku on 3.60 but installed enso and everything went to hell... after  several errors trying to open vitashell got desperate and set vita to fabric settings, bad luck because upgraded firm to 3.70 by mistake but made it to hack again with trinity. i have installed henkaku now but after all still having same problem and can´t access vitashell ... any help willl be really appreciated!!!!

"an error has occurred in the following application. (c2-12828-1) saved core file succeded uxo:data/psp2core-1558333035-0v0000103197-eboot.bin.pspdmp"

**Comment by rey-k2** [comment]
hi i'm having the same problem as well. has anybody found any solution?

**Comment by cursai** [comment]
Never got this solved myself. Tried everything. Had to buy new motherboard in the end

**Comment by rey-k2** [comment]
> Never got this solved myself. Tried everything. Had to buy new motherboard in the end

mind if i ask where you got your new motherboard from? i'm starting to think i'm going to have to replace mine myself too...

**Comment by guille1986** [comment]
We are screwed! I kept looking for a way to solve this but till now nothing... I had to buy  a lime 2000 through china which  is hacked and loud! But  the 1000 is still waiting for a good soul with a definitive solution :(

**Comment by Chaser496930** [comment]
Yeah me to i get error C2-12828-1 Saved core file succeded ux0:data/psp2core-xxxxxxxxxx-0x00000c2bc5-eboot.bin.psp2dmp

(after psp2core its not only x i just didnt want to put it)
