### ISSUE TITLE
Specific characters don't display correctly

### ISSUE THREAD

**Issue by Sora3100** [TheOfficialFloW/VitaShell#144]
Some characters from the Hungarian language don't display correctly, they display as "_".
These should be the following 2 characters from what I have noticed: "ő" and "ű" (and probably "Ő","Ű").
Maybe I should just comment this to #108?

**Comment by littlebalup** [comment]
Yeah, same issue than https://github.com/TheOfficialFloW/VitaShell/issues/108 .  Costom fonts should solve it.
