### ISSUE TITLE
When i compile vitashell with new vitasdk i got a error

### ISSUE THREAD

**Issue by kingzhe2011** [TheOfficialFloW/VitaShell#145]
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable main.o init.o io_process.o makezip.o package_installer.o network_update.o context_menu.o archive.o photo.o audioplayer.o file.o text.o hex.o sfo.o settings.o property_dialog.o uncommon_dialog.o message_dialog.o ime_dialog.o config.o theme.o language.o utils.o elf.o sha1.o list_dialog.o UI2.o touch_shell.o minizip/zip.o minizip/unzip.o minizip/ioapi.o bm.o audio/vita_audio.o audio/player.o audio/id3.o audio/oggplayer.o audio/mp3player.o audio/mp3xing.o audio/lrcparse.o libmad/bit.o libmad/decoder.o libmad/fixed.o libmad/frame.o libmad/huffman.o libmad/layer12.o libmad/layer3.o libmad/stream.o libmad/synth.o libmad/timer.o resources/battery_bar_green.o resources/pause.o resources/pd0.o resources/unknown_file.o resources/mark.o resources/archive_icon.o resources/play.o resources/savedata0.o resources/folder.o resources/fastforward.o resources/title_bar_bg.o resources/vita_game_card.o resources/sa0.o resources/ur0.o resources/vd0.o resources/app0.o resources/wifi.o resources/memory_card.o resources/ftp.o resources/audio_icon.o resources/music_file.o resources/ud0.o resources/bg_wallpaper.o resources/zip_file.o resources/battery.o resources/txt_file.o resources/vs0.o resources/stop.o resources/folder_icon.o resources/battery_bar_charge.o resources/cover.o resources/updir.o resources/text_icon.o resources/sfo_icon.o resources/image_icon.o resources/run_file.o resources/file_icon.o resources/image_file.o resources/battery_bar_red.o resources/fastrewind.o resources/vita_game_card_storage.o resources/os0.o resources/theme.o resources/english_us.o resources/colors.o resources/changeinfo.o resources/updater_eboot.o resources/updater_param.o -lvorbisfile -lvorbis -logg -lftpvita -lvita2d -lpng -ljpeg -lz -lm -lc -lonig -lSceAppMgr_stub -lSceAppUtil_stub -lSceCommonDialog_stub -lSceCtrl_stub -lSceDisplay_stub -lSceGxm_stub -lSceIme_stub -lSceHttp_stub -lSceMusicExport_stub -lSceNet_stub -lSceNetCtl_stub -lSceSsl_stub -lSceSysmodule_stub -lScePhotoExport_stub -lScePower_stub -lScePgf_stub libpromoter/libScePromoterUtil_stub.a -lSceAudio_stub -lSceAudiodec_stub -lSceTouch_stub -lSceShellSvc_stub -o VitaShell.elf
lto1: fatal error: bytecode stream generated with LTO version 4.1 instead of the expected 5.1
compilation terminated.
lto-wrapper: fatal error: arm-vita-eabi-gcc returned 1 exit status
compilation terminated.
/vitasdk/lib/gcc/arm-vita-eabi/6.2.0/../../../../arm-vita-eabi/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
Makefile:52: recipe for target 'VitaShell.elf' failed
make: *** [VitaShell.elf] Error 1

**Comment by TheOfficialFloW** [comment]
compile libvita2d using the newest vitasdk.
