### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by Yamigami** [TheOfficialFloW/VitaShell#147]
yami@elemos:~/Documents/VitaShell$ make
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o main.o main.c
In file included from main.c:27:0:
main.h:37:28: fatal error: psp2/shellutil.h: No such file or directory
compilation terminated.
<builtin>: recipe for target 'main.o' failed
make: *** [main.o] Error 1

**Comment by TheOfficialFloW** [comment]
update to latest vitasdk.

**Comment by Yamigami** [comment]
which one i have 5.9?

**Comment by TheOfficialFloW** [comment]
https://bintray.com/package/files/vitasdk/vitasdk/toolchain?order=desc&sort=fileLastModified&basePath=&tab=files

**Comment by Yamigami** [comment]
now this error ... 
i compiled vita2dlib and onigmo other deps too 

yami@elemos:~/Documents/VitaShell$ make
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o main.o main.c
In file included from main.c:27:0:
main.h:31:29: fatal error: psp2/moduleinfo.h: No such file or directory
 #include <psp2/moduleinfo.h>
                             ^
compilation terminated.
<builtin>: recipe for target 'main.o' failed
make: *** [main.o] Error 1

**Comment by limyz** [comment]
It has been previously raised before.
Please read https://github.com/TheOfficialFloW/VitaShell/wiki.

**Comment by Yamigami** [comment]
same problem, i read the docs and followed extractly gives me error. Then i tried doing manual compiling using latest vitasdk same thing

**Comment by limyz** [comment]
You may not have extracted the vitasdk libs properly. I do not come across this issue.

**Comment by TheOfficialFloW** [comment]
Just use moduleinfo.h from a previous built until I fix it. Learn to understand error results.
