### ISSUE TITLE
Black screen when running VitaShell

### ISSUE THREAD

**Issue by PerplexedPanda** [TheOfficialFloW/VitaShell#148]
So I've built VitaShell without any apparent issue, but when I run it all I get is a black screen; it doesn't crash though.

Built on Linux x64 using latest toolchain and VitaShell with all dependencies outlined in README.md.
 [Build output](http://hastebin.com/onixozidov.swift)

Another thing I've noticed is that the resulting executable size ends up smaller than that which is found in the release. Not sure if that is of any relevance, but there you go.
[Additional info](http://hastebin.com/gadepinimi.sql)

I realize this may not be an issue with VitaShell itself, but I wasn't sure where else to bring this up.

**Comment by limyz** [comment]
Have you tried an earlier commit to see if the problem persists?

**Comment by PerplexedPanda** [comment]
Yeah, I've tried building VitaShell a few times prior to this new release with the same results. I've set up the toolchain and dependencies again each time.

**Comment by PerplexedPanda** [comment]
So I gave in and installed Windows to see if building VitaShell on Windows would make a difference and it didn't; same black screen. XYZ has had the same problem with VitaShell and gave up some time ago and at this point I give up too.

I don't know what wizardry TheFloW is using that allows him to compile a functioning build of VitaShell, but I've tried everything I could think of.

**Comment by limyz** [comment]
Is the issue resolved? If so, a solution to your problem would be appreciated.
