### ISSUE TITLE
Translation offer

### ISSUE THREAD

**Issue by MrTheFrenchOctopus** [TheOfficialFloW/VitaShell#149]
I don't know if you need my help, but I've made an almost full translation of VitaShell (with the file french.txt) on my vita, and I thought maybe I could translate your app to French officially :)
And for free of course, i'd feel guilty to get money from that.

**Comment by limyz** [comment]
All translations can be submitted via a PR over at https://github.com/xy2iii/vitashell-themes.

**Comment by TheOfficialFloW** [comment]
None of us are getting money from anything. All our work are for free. Not sure why you have even had the thought of taking money for a translation ;)

**Comment by MrTheFrenchOctopus** [comment]
I dont know, some people really insist on paying the translations ^^
I translate a lot and I've already met some of these people, and I had to refuse firmly x)
So now I say it before making an offer :3
