### ISSUE TITLE
i can't quit with ps button unless reboot my vita

### ISSUE THREAD

**Issue by kingzhe2011** [TheOfficialFloW/VitaShell#151]
![2016-11-13-204207](https://cloud.githubusercontent.com/assets/2289763/20245765/c2d7f708-a9e2-11e6-91e2-e449a28196cc.jpg)

**Comment by Yamigami** [comment]
You have to have your wifi on before you start vitashell, so this doesn't happen. Also be sure to turn off FTP BEFORE so you could close vitashell, idk why its like this

**Comment by TheOfficialFloW** [comment]
This is not a bug, this is a feature I have added to avoid data corruption.

**Comment by kingzhe2011** [comment]
ok
