### ISSUE TITLE
Suggestion to MaiDump

### ISSUE THREAD

**Issue by MrCampy** [TheOfficialFloW/VitaShell#152]
Hi TheFlow,

I can't disturb to you with this message but... could you said to "BeniYukiMai" (MaiDumpTools' creators) how can they to dump a game without converting to demo mode and converting to full mode?

You can post in this github: https://github.com/BeniYukiMai/MaiDumpTool

I think that you are a great man and a great worker.

**Comment by TheOfficialFloW** [comment]
I'm not happy at all that I had to read and repond to this message. The issue section here is not meant to request things that are not related to VitaShell.
