### ISSUE TITLE
Cannot leave app due to FTP and button lock on PS button

### ISSUE THREAD

**Issue by RePod** [TheOfficialFloW/VitaShell#154]
There seems to be a discrepancy between the FTP server not running and if the PS button functions as intended.

No sure-fire way to reproduce other than dropping the wireless signal. Seems to be more frequent when resuming from standby.

Pressing Select to open the FTP options gives only "Please wait...", cancelling that does not unlock usage of the PS button.

Possible suggestions:
 - Add a close/exit option in the menu accessible via pressing Start
 - Force the PS button to unlock if cancelling the "Please wait..." dialog
 - Make the locking of the PS button configurable

This is happening 1.42

**Comment by RePod** [comment]
Sorry, checked commit history seems this was resolved and not released yet.

**Comment by limyz** [comment]
Refer to https://github.com/TheOfficialFloW/VitaShell/commit/cc4216f2bca22da1e08d4ba3aef8a221b8b0b38e

**Comment by RePod** [comment]
I'd like to draw attention to my suggestion in my edit of adding additional control over Vita Shell from the Start menu.

While fixed, it could still potentially be confusing to certain users who do not understand the FTP task was backgrounded. Additional options to, say, exit or restart Vita Shell would be nice to have.

**Comment by TheOfficialFloW** [comment]
I have already fixed that bug: https://github.com/TheOfficialFloW/VitaShell/commit/cc4216f2bca22da1e08d4ba3aef8a221b8b0b38e

The next update will have it.
