### ISSUE TITLE
Bug taihen Permissions maybe ?

### ISSUE THREAD

**Issue by Rezasdemon** [TheOfficialFloW/VitaShell#156]
it seems with the new taihenkaku update my vitashell is broken

I downloaded vitashell 1.42 from github/vitashell/releases
I remove molecule and vitashell from vita 
restart the vita
launch browser -> go.henkaku.xyz 
launch molecule shell
install vita shell 
launch vitashell 
it works as expected I am able to see all partitions
ux0,ur0,etc 
I can also see a file ux0:/tai/config.txt
... ERROR occurence is in taihenkaku
exit vitashell 
close and remove apps vitashell , molecule
restart
launch browser -> beta.henkaku.xyz
launch molecule ( shows molecular shell in top)
press start -> enable unsafe stuff
install vitashell 
launch vitashell
and the error is now that I still cannot see all the partitions and it wont allow me to upload or modify or even read or list in the ftp the file ux0:/tai/config.txt
new taihen version from working to fail  it was working on taihen beta before ?

**Comment by TheOfficialFloW** [comment]
Reboot once again.

**Comment by Rezasdemon** [comment]
Wow I swear to god I did that already OMG I've been working on this issue for so long now and I've restarted millions of times never and worked before this I guess I undid my self by switching back to the original when the normal one failed lol ok this can be closed thanks. Can't believe I made this mistake.
