### ISSUE TITLE
Compiling Error

### ISSUE THREAD

**Issue by Hitogami** [TheOfficialFloW/VitaShell#158]
hitogami@build:~/Downloads/VitaShell$ make
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o audio/oggplayer.o audio/oggplayer.c
audio/oggplayer.c:24:44: fatal error: vorbis/codec.h: No such file or directory
 #include <vorbis/codec.h>      //ogg-vorbis
                                            ^
compilation terminated.

**Comment by Hitogami** [comment]
Fixed by putting vita_toolchains.tar.gz (lib, include) files inside /usr/local/vitasdk/arm-vita-eabi/ not in /usr/local/vitasdk as the wiki suggest. Please fix that

Another error came up
/usr/local/vitasdk/bin/../lib/gcc/arm-vita-eabi/6.2.0/../../../../arm-vita-eabi/bin/ld: cannot find -lHENkaku_stub

i am already using latest sdk from lolhax.org?

**Comment by d3m3vilurr** [comment]
you should install libvorbis, libogg, and code require [henkaku plugin](https://github.com/henkaku/henkaku/tree/master/plugin)

**Comment by Hitogami** [comment]
@d3m3vilurr You mean install using apt-get? the libvorbis and libogg? How do i put henkaku plugin?

**Comment by d3m3vilurr** [comment]
1. no. you should build & install vorbis and ogg with vitasdk.
like this, https://github.com/d3m3vilurr/vitatoolchain/commit/6c09c475dc

2. henkaku plugin need to build [taihen](https://github.com/yifanlu/taiHEN), follow henkaku [readme](https://github.com/henkaku/henkaku/blob/master/README.md) then you can build henkaku plugin.
then you can build library using `vita-libs-gen`

**Comment by Hitogami** [comment]
Well i am just using your for-vitashell automated script for that environment, but stuck here
https://github.com/d3m3vilurr/vitatoolchain/commit/269094b2eeb8b5ba2d5c336ea19ea55afd345a42
What is roptool/uglifyjs and how do i install them?

**Comment by d3m3vilurr** [comment]
* roptool: https://bitbucket.org/DaveeFTW/roptool you need boost >= 1.60. if you use ubuntu, probably need to upgrade yakkety (16.10)

* uglifyjs: https://github.com/mishoo/UglifyJS2 you need node environ, `npm install uglifyjs -g`
