### ISSUE TITLE
Implement rename through FTP

### ISSUE THREAD

**Issue by sorgelig** [TheOfficialFloW/VitaShell#16]
Please implement FTP rename command.

**Comment by limyz** [comment]
I have successfully renamed the a file over FTP. Which folder or file were you trying to rename? Were you at ux0:/?

**Comment by sorgelig** [comment]
yes, in ux0:
Tried Total Commander and FileZilla.

**Comment by TheOfficialFloW** [comment]
Rename has been implemented since ever
