### ISSUE TITLE
Use Line Wrap Algorithm for dialog and text editor

### ISSUE THREAD

**Issue by TheOfficialFloW** [TheOfficialFloW/VitaShell#161]

**Comment by Mayoshiroi** [comment]
I want to start this work,so can you speak a little more about this 'Line Wrap Algorithm'? :)

**Comment by limyz** [comment]
@TheOfficialFloW probably wants to create an algorithm from scratch to line wrap text within its boundaries. I leave some info here for personal reference.

http://stackoverflow.com/questions/17586/best-word-wrap-algorithm
http://stackoverflow.com/questions/28642880/line-wrapping-algorithm-the-greedy-approach
