### ISSUE TITLE
[Request] Button other than Start to access Unsafe Homebrew toggle

### ISSUE THREAD

**Issue by GamerGoddessDin** [TheOfficialFloW/VitaShell#168]
My Vita's Start button is apparently dying/dead and doesn't always work and thus I'm having difficulty accessing the settings menu to enable Unsafe Homebrew.

Since I have a PSTV as well and my Dualshock controller's buttons all work I should be able to move my memory card to it and do the relevant configuration but not everyone has that option available to them but may be in a similar situation.

Proposed alternate button location: Pressing Triangle on a "Drive Letter" (such as "ux0:") to pull up the same menu Start should be.

**Comment by TheOfficialFloW** [comment]
Grab the source, change the button and compile. I cannot take care of everyones broken buttons...
