### ISSUE TITLE
Add rar archive support

### ISSUE THREAD

**Issue by TheOfficialFloW** [TheOfficialFloW/VitaShell#171]

**Comment by Mayoshiroi** [comment]
I starting to this issues, please remind me if anyone wants to do this issues  :)

**Comment by MegaPramuk** [comment]
Instead of using .rar, why not implement 7z archive support?
It's a free format after all unlike rar.

**Comment by TheOfficialFloW** [comment]
@MegaPramuk I'm taking about rar extraction.
