### ISSUE TITLE
home (SAFE MODE)

### ISSUE THREAD

**Issue by VheeCious** [TheOfficialFloW/VitaShell#173]
Dear Henkaku / Molecule / VitaShell developer,
I have issue here.

the app "molecule" which usually shows the full list of folders now only shows ux0: folder. and if I try to make new directory within the app itself, or by using FTP, the newly made folder would never show up on my screen.

The problem is, on the "home" where usually it shows lists of folders, on the very top now it says "home (SAFE MODE). What does this mean?

I tried formating my mmc, formating my ps vita system, restoring the settings, rebuild database on vita safe mode, and nothing seems to be working.

So, the problem occured when, I was trying to backup a whole lot of saved games into my PC through content manager. When I left it for 2 hours, it says, 25 minutes left. but after leaving it for 3 hours, it still says 25 minutes left. and after 3.5 hours, i decided to cancel the backup. so then the system starts to show a circling icon which means it's working. but after several minutes, it freezed, and so I powered it off as usual. when it came back on, of course, as usual, I went to go.henkaku.xyz again for another fresh install of molecule. and that's when the problem occured. there showed up the "home (SAFE MODE)" and I just can't fix it no matter what. If I try to transfer a file using FTP with the premade folder, nothing seems to be a problem.

So problem is,
1. only ux0: shows up.
2. inside ux0: folder:
calendar/
data/
mms/
ptmp
tai/
VitaShell/
3. I usually transfer large files using qmca, copy the file using video app, rename the file and install vpk through molecule app. 
But after the home (SAFE MODE) it seems that, I can still copy the file through QMCA, but I cannot see my file anywhere within that ux0 folders.
My copied file would be in video app directory, but cannot find it through the molecule app.

and 1 thing I noticed,
usually when I install fresh henkaku, it will automatically install molecule app. and when i first open molecule app, it will automatically install vitashell app.
but after this problem, it seems that molecule is not going to install vitashell anywhere.

So, what happened here? Did I do anything wrong?
Please help me....

Thank you in advance.

**Comment by TheOfficialFloW** [comment]
Press START.

**Comment by VheeCious** [comment]
@TheOfficialFloW I've tried. and it shows me settings like,
enable psn spoofing
enable unsafe homebrew,
and so on.

So, what changes should I make?

**Comment by TheOfficialFloW** [comment]
Enable unsafe homebrew?

**Comment by VheeCious** [comment]
@TheOfficialFloW it was off, and now it's turned on. but home (SAFE MODE) is still there.

**Comment by VheeCious** [comment]
@TheOfficialFloW  Oh wait. I tried closing the app and reopened it. and it worked.
Thank you so much for your help!
I was just really worried that my vita would be bricked or something :/
Thanks again!

**Comment by TheOfficialFloW** [comment]
ok. this wasn't the right area to ask those simple questions though...

**Comment by VheeCious** [comment]
@TheOfficialFloW I'm sorry. I have no idea where else to ask. cz, I've tried hours googling with what to do with this safe mode, but every article I found lead to vita safe mode, which is a different case. I'm sorry, and thank  you.
