### ISSUE TITLE
small bug with context menu

### ISSUE THREAD

**Issue by razneck** [TheOfficialFloW/VitaShell#177]
So I'v been theming today and stumbled upon a small bug.
The regular context menu keeps the size of the context menu in the text editor which is a bit stretched.

To reproduce, just open a text file, open context menu and open hexeditor.
Than just close the hexeditor with O/X and open the context menu again in the browser, voila.

I'm not even sure if this could be/is a feature. It looks rather interesting on my latest Why2k theme.

**Comment by TheOfficialFloW** [comment]
Ah yes that's a bug! Btw I really love your themes and would like to have a private chat with you. Add me on hangouts if you like: theofficialflow1996@gmail.com
