### ISSUE TITLE
USB support in 1.5 not working with Linux

### ISSUE THREAD

**Issue by parkerlreed** [TheOfficialFloW/VitaShell#178]
````
[parker@satellite ~]$ sudo mount /dev/sdb /mnt
FUSE exfat 1.2.5
ERROR: unsupported FAT count: 2.
````

exfat-utils are installed. 

EDIT: This is on Arch Linux

**Comment by Evengard** [comment]
you don't have sdb1? try to mount it if you do.

**Comment by d3m3vilurr** [comment]
linux system, use [exfat-nofuse](https://github.com/dorimanx/exfat-nofuse) instead of exfat-fuse.
exfat-fuse cannot mount that.

and `/dev/sdb` is right :)

**Comment by parkerlreed** [comment]
@Evengard Yeah that's called a superblock. The whole device gets mapped as the "partition"

@d3m3vilurr Thanks for the suggestion, will try that out.

**Comment by parkerlreed** [comment]
@d3m3vilurr Thanks! Installing https://aur.archlinux.org/packages/exfat-dkms-git/ and removing exfat-utils solves it. (Same mount /dev/sdb command)

**Comment by andre104623** [comment]
doesn't work on linux mint 
andre104623@andre104623-SVE14A27CXH ~ $ sudo mount /dev/sdb /mnt
[sudo] password for andre104623: 
FUSE exfat 1.2.3
ERROR: unsupported FAT count: 2.
I'm still very new to linux if someone could just tell me the right line to type into terminal I'll be good I think....

**Comment by fennectech** [comment]
Thanks  worked for me :+1:    Andre  you should look into installing exfat-dkms on your distro

**Comment by d3m3vilurr** [comment]
if you use ubuntu, can use eugenesan's [ppa](https://launchpad.net/~eugenesan/+archive/ubuntu/ppa)
this ppa only support until xenial, but compatible with yakkety.

install  exfat-nofuse then build and install on `/usr/src/exfat*`
or compile manually; follow this [steps](https://www.reddit.com/r/vitahacks/comments/5nkgcu/theflow_finally_release_vitashell_update_with_usb/dccekoh/)

**Comment by PHD59fr** [comment]
for Ubuntu 16.04.1 LTS:

git clone https://github.com/rxrz/exfat-nofuse.git
cd exfat-nofuse
make && make install

mount /dev/sd*** /mnt/***

**Comment by papa-gene** [comment]
@PHD59fr 's solution worked, awesome!

**Comment by fennectech** [comment]
we can also recreate the filesystem with a fresh exfat filesystem  that linux will happily mount  and the vita will be none the wiser and happily repopulate the directories

**Comment by fennectech** [comment]
i would not recomend using fat32  because of the 4gb file size limit           There may be games with files larger than 4gb

**Comment by parkerlreed** [comment]
@fennectech Does that actually work?

**Comment by fennectech** [comment]
Yes  it is the technique i used    execute mkfs.exfat on the drive and linux will prepair a  filesystem it supports properly   then you can just copy your stuff back  (dont let the vita  know anything has changed)  dont unplug or youll loose all your saves  and the vita wont take em   also    execute "sync' from the command line and wait a few minutes    ive had lotsa problems with incomplete writes

**Comment by fennectech** [comment]
as i understand    The filesystem the vita creates has an unsupported feature enabled  that linux poopoos about     creating the filesystem with linux will have all features linux supports

**Comment by aphirst** [comment]
I can confirm that @fennectech's approach works. I can now select "Memory Card" from inside VitaShell and mount it on all my Linux (Arch) machines without special configuration (as long as they have the default exfat driver installed), just like I always could when mounting my SD card via "SD2Vita" USB mode.

Definitely important to `sync` before disconnecting! I like to monitor the **real** status of the copy using something like `watch grep -e Dirty /proc/meminfo`.

**Comment by robsdedude** [comment]
@fennectech 

> Yes it is the technique i used execute mkfs.exfat on the drive and linux will prepair a filesystem it supports properly then you can just copy your stuff back (dont let the vita know anything has changed) dont unplug or youll loose all your saves and the vita wont take em also execute "sync' from the command line and wait a few minutes ive had lotsa problems with incomplete writes

How do you copy the stuff back if you cannot mount the fs in the first place?

**Comment by aphirst** [comment]
@robsdedude 

1. First you copy stuff off the vita memory card by mounting via FTP.
2. Then you connect via USB, set VitaShell to USB, then ignore the Linux-side errors about failing to mount.
3. Notice, however, that the **block device** is still visible to Linux just fine, so (once you're **very sure** you backed up the vita memory card correctly) use `mkfs.exfat` to format the block device into a new exfat partition that Linux will (of course) be able to access without problem.
4. Copy the backed-up files and folders onto your new exfat partition.

Ideally, don't disconnect the Vita from USB between formatting and finishing restoring the backed-up data.

**Comment by evertonstz** [comment]
I'm able to mount with https://aur.archlinux.org/packages/exfat-dkms-git/ but everytime I try to copy something to the system everything is copied with 1 second and all files I copied go to the vita corrupted. Any way to fix it?

**Comment by Niketin** [comment]
> I'm able to mount with https://aur.archlinux.org/packages/exfat-dkms-git/ but everytime I try to copy something to the system everything is copied with 1 second and all files I copied go to the vita corrupted. Any way to fix it?

I have the exact same problem. Any solutions?

**Comment by unresolvedsymbol** [comment]
For anyone still with this problem, **DONT** bother with the exfat-dkms/exfat-nofuse kmod, it's outdated. If fuse-exfat is trying to handle the partition simply uninstall exfat-utils and fuse-exfat (pm/distro dependent) and let the kernel mount it, it's been builtin for some time. Kernel version `5.10.8_1`

**Comment by unresolvedsymbol** [comment]
PS. If anyone insists on using this for some reason, you can try [my fork](https://github.com/unresolvedsymbol/exfat-nofuse).

**Comment by Bobbydigital420** [comment]
> > I'm able to mount with https://aur.archlinux.org/packages/exfat-dkms-git/ but everytime I try to copy something to the system everything is copied with 1 second and all files I copied go to the vita corrupted. Any way to fix it?
> 
> I have the exact same problem. Any solutions?

I was experiencing the same issue. aphirst has the answer we were looking for above. The files are quickly copied into a memory buffer then written to disk. The file transfer will seem to be fast but thats just it being being buffered. You can use the command he mentioned "watch grep -e Dirty /proc/meminfo" to see the progress of the buffer being written to disk or just use the sync command and wait until its done.

**Comment by philj0st** [comment]
followed @unresolvedsymbol s advice and deleted exfat-utils and it worked.
Arch with 5.13.12-zen1-1-zen kernel
