### ISSUE TITLE
USB Issue with Win7

### ISSUE THREAD

**Issue by ScHlAuChii** [TheOfficialFloW/VitaShell#180]
![usb](https://cloud.githubusercontent.com/assets/12144392/21913189/1a84d04e-d92b-11e6-90dd-cc9c8300ed82.jpg)

When I try to copy a file onto the Vita this is the error I get, copying to PC from the Vita works without problems! The error 0x80071ac3 = Volume is dirty/Filesystem corrupt

Is it safe to run chkdsk or will this corrupt the Vita?
Is there any way to resolve this issue?

**Comment by marcos-torres** [comment]
Also noticed this issue even when the USB has been ejected properly.

![scanandfix](https://cloud.githubusercontent.com/assets/1701084/22130573/ba5c8978-de61-11e6-8a5e-2dc2c0832c6b.png)

**Comment by limyz** [comment]
Not related. Probably disk flagged as dirty. You scan and fix to resolve this issue.
