### ISSUE TITLE
VitaShell 1.5 freezes when trying to installl a VPK

### ISSUE THREAD

**Issue by parkerlreed** [TheOfficialFloW/VitaShell#181]
Tried to install the theme manager and it freezes before getting to the unsafe popup. Tried starting fresh by wiping ux0:Vitashell with the same result.

**Comment by d3m3vilurr** [comment]
i heard from @TheOfficialFloW at last night, i'll try to figure that at tonight. :(

**Comment by fennectech** [comment]
![2015-01-01-014124](https://cloud.githubusercontent.com/assets/11953665/21927089/4650fad0-d94a-11e6-9cf9-533d0a538c59.jpg)

**Comment by kylon** [comment]
this commit is the cause
https://github.com/TheOfficialFloW/VitaShell/commit/f0a9325e0725cb7a55243e038b34d93fa503b233

the problem only occurs when you install a NEW vpk.
where NEW means: it is not already installed.

**Comment by d3m3vilurr** [comment]
@fennectech @kylon crash bug will fix with #190 
@parkerlreed are you getting freeze instead crash?

**Comment by d3m3vilurr** [comment]
@kylon can your share impact homebrew project?

**Comment by kylon** [comment]
Yea, check your email

**Comment by d3m3vilurr** [comment]
@kylon your app looks safe app.

**Comment by kylon** [comment]
According to vita shell 1.43 it is unsafe and the -s flag is not set

**Comment by d3m3vilurr** [comment]
in hex data, your app marked `0x2F00000000000002`
and compressed app always said unsafe before 1.50
so your app is safe

**Comment by kylon** [comment]
Clear now
Thanks

**Comment by parkerlreed** [comment]
@d3m3vilurr Yeah it freezes up. Cannot navigate Vtashell and pressing the PS button gives me the little warning in the upper left. I can still long hold power and then tap the power off button.

**Comment by d3m3vilurr** [comment]
@parkerlreed can you share your app? always?

**Comment by parkerlreed** [comment]
http://wololo.net/talk/viewtopic.php?f=116&t=46936

Which on that note, themes don't seem to be working (I tried applying manually and through that application but it just stays on default)

**Comment by TheOfficialFloW** [comment]
Should be fixed in v1.51

**Comment by parkerlreed** [comment]
Working great!
