### ISSUE TITLE
Music corruption after USB connection

### ISSUE THREAD

**Issue by DreamLabsM47** [TheOfficialFloW/VitaShell#182]
When i connected to my pc w/ usb for the first time all of my music was corrupt. Nothing would play and I tried to restart too.. nothing worked. So i deleted it all... I was able to get my music back by transferring my   backups via qcma.

**Comment by Kenshii** [comment]
I'm also noticing this music corruption bug. Restarting the vita actually solves it for me when I do get it, though.

**Comment by DreamLabsM47** [comment]
Restarting my vita isn't actually working for me. I have to rebuild my data base every time i want my music back.

**Comment by Hitogami** [comment]
Weird my musics are file even after connecting to usb and not rebooting

**Comment by limyz** [comment]
Just checking before I flag this as a bug. How is the music file being played? Does transferring over OpenCMA or QCMA causes this issue as well?

**Comment by DreamLabsM47** [comment]
QCMA does not cause the same issue and I'm not 100% sure what you mean when you ask how it is being played. I'm attempting to play it through the music app and it claims that the file is corrupt along with everything else, however if i attempt to play it in vitashell in it's folder it works. i'm sorry, I really hope this answers your question.
