### ISSUE TITLE
Usb not working on linux mint

### ISSUE THREAD

**Issue by andre104623** [TheOfficialFloW/VitaShell#183]
andre104623@andre104623-SVE14A27CXH ~ $ sudo mount /dev/sdb /mnt
[sudo] password for andre104623: 
FUSE exfat 1.2.3
ERROR: unsupported FAT count: 2.
Still very new to linux I tried to sudo apt-get install exfat-fuse exfat-utils. On Archlinux however, other people have recommended to install exfat-dkms-git instead of exfat-fuse and exfat-utils. 
Still not getting anywhere

**Comment by andre104623** [comment]
If someone could tell me the right line to type into terminal hopefully I'll be good. I'm sorry really new to linux just started using 3 weeks ago

**Comment by TheOfficialFloW** [comment]
Your problem is not a specific problem of VitaShell, so please stop asking for help here.
