### ISSUE TITLE
PS Vita crash when disconnecting USB 

### ISSUE THREAD

**Issue by devnoname120** [TheOfficialFloW/VitaShell#184]
1. Enable USB and connect the Vita to your computer.
2. Wait that the Vita turns its screen off (not sure if necessary, will confirm it later).
3. Disconnect the USB cable.
4. The PS Vita crashes.

![Vita crash](https://cloud.githubusercontent.com/assets/2824100/21921929/c9a10f4e-d96b-11e6-90bd-8e5cfd74afe2.jpg)

**Comment by limyz** [comment]
Unable to reproduce bug
