### ISSUE TITLE
config.txt not working since i updated vitashell to 1.5

### ISSUE THREAD

**Issue by headhunterpao** [TheOfficialFloW/VitaShell#189]
i did everything, rebuild database, reformat, reinstall henkaku, and still the config.txt I inputted for plugins doesnt work anymore... BTW, I'm kinda curious since when I updated vitashell to verson 1.5 where there is USB mode, the molecular shell remained version 1.43 .... Does anyone have the same problem as mine?

**Comment by parkerlreed** [comment]
Vitashell has nothing to do with the config.txt. That's tai/Henkaku.

**Comment by headhunterpao** [comment]
there is nothing wrong with it, it runs fine if I use the old version of vitashell, if i install vitashell 1.5, it wont work again, currently now im using vitashell 1.43, i only update it to 1.5 for transferring backups only then would switch back to old version again
