### ISSUE TITLE
Improvement: display size and free space of the memory card

### ISSUE THREAD

**Issue by littlebalup** [TheOfficialFloW/VitaShell#19]
Should be useful as I always wonder how many space remains on my mem card when I install and transfer stuff.
Maybe applicable to other storage devices.

**Comment by Catarax** [comment]
Yes!

**Comment by littlebalup** [comment]
looking deeper in the code, I found that by pressing L+R+Start shows system infos, including mem card size.
A good point but should be more accessible.

**Comment by kuni59** [comment]
my dick

**Comment by limyz** [comment]
Refer to https://github.com/TheOfficialFloW/VitaShell/releases/tag/0.9. System information can now be triggered by pressing START.

**Comment by limyz** [comment]
Refer to https://github.com/TheOfficialFloW/VitaShell/commit/a39b48954f03c5d0e5d1fc594baa328c1eb2934b.
