### ISSUE TITLE
usb storage bug with 64GB memory card

### ISSUE THREAD

**Issue by 133794m3r** [TheOfficialFloW/VitaShell#193]
Error mounting /dev/sdb at /media/1F30-38DA: Command-line `mount -t "exfat" -o "uhelper=udisks2,nodev,nosuid,uid=1000,gid=1000,iocharset=utf8,namecase=0,errors=remount-ro,umask=0077" "/dev/sdb" "/media/1F30-38DA"' exited with non-zero exit status 1:
stdout: `FUSE exfat 1.1.0
'
stderr: `ERROR: unsupported FAT count: 2.
'

dmesg tells me the following information. 

Jan 15 05:17:13 sager-laptop kernel: [37417.828244] usb 4-1.1: Manufacturer: SONY
Jan 15 05:17:32 sager-laptop kernel: [37436.492905] usb 4-1.1: USB disconnect, device number 7
Jan 15 05:17:32 sager-laptop kernel: [37436.691044] usb 4-1.1: new high-speed USB device number 8 using ehci-pci
Jan 15 05:17:32 sager-laptop kernel: [37436.784921] usb 4-1.1: New USB device 
Jan 15 05:17:32 sager-laptop kernel: [37436.784932] usb 4-1.1: New USB device 
Jan 15 05:17:32 sager-laptop kernel: [37436.784937] usb 4-1.1: Product: "PS Vita" Type A
Jan 15 05:17:32 sager-laptop kernel: [37436.784942] usb 4-1.1: Manufacturer: SONY
Jan 15 05:17:32 sager-laptop kernel: [37436.784946] usb 4-1.1: SerialNumber: 
Jan 15 05:17:32 sager-laptop kernel: [37436.785727] usb-storage 4-1.1:1.0: USB Mass Storage device detected
Jan 15 05:17:32 sager-laptop kernel: [37436.786103] scsi8 : usb-storage 4-1.1:1.0
Jan 15 05:17:33 sager-laptop kernel: [37437.785069] scsi 8:0:0:0: Direct-Access     SONY     "PS Vita" MC     1.00 PQ: 0 ANSI: 0 CCS
Jan 15 05:17:33 sager-laptop kernel: [37437.785858] sd 8:0:0:0: Attached scsi generic sg2 type 0
Jan 15 05:17:33 sager-laptop kernel: [37437.787771] sd 8:0:0:0: [sdb] 125992960 512-byte logical blocks: (64.5 GB/60.0 GiB)
Jan 15 05:17:33 sager-laptop kernel: [37437.788165] sd 8:0:0:0: [sdb] Write Protect is off
Jan 15 05:17:33 sager-laptop kernel: [37437.788176] sd 8:0:0:0: [sdb] Mode Sense: 2d 00 00 00
Jan 15 05:17:33 sager-laptop kernel: [37437.788776] sd 8:0:0:0: [sdb] Write cache: disabled, read cache: disabled, doesn't support DPO or FUA
Jan 15 05:17:33 sager-laptop kernel: [37437.794758]  sdb: unknown partition table
Jan 15 05:17:33 sager-laptop kernel: [37437.797094] sd 8:0:0:0: [sdb] Attached SCSI remov

that's the full dmesg log so it's not doing something right I guess.

It says type-a when it connects to computer then switches to type b when I enable usb mode.

**Comment by dic1911** [comment]
That's not the problem with memory card capacity, I'm using 8GB memcard and it doesn't work with Linux Mint too

**Comment by 133794m3r** [comment]
so i guess it is. I searched online for that error and couldn't find anything about it. I've used exfat formatted devices before. Both direct(through latptop's sd card connector) and through a usb adapter never had issues before so figured the only thing tha changed was the primary issue.

**Comment by d3m3vilurr** [comment]
this issue duplicated too many times, @TheOfficialFloW your [retweet][1] can make confusing, so maybe we need to update README about this..

how about like that;
 ```
## USB Mount on Linux
Use [exfat-nofuse](https://github.com/dorimanx/exfat-nofuse) instead of exfat-fuse
```

[1]: https://twitter.com/theflow0/status/819590382703022081
