### ISSUE TITLE
Can't connect with USB

### ISSUE THREAD

**Issue by Vasniktel** [TheOfficialFloW/VitaShell#196]
I can't connect to Windows XP by USB, it writes that the storage device is needed to be formatted.

**Comment by Mtgxyz2** [comment]
You probably need service pack 3 to read exFAT formatted storage devices like the PS VITA. Also: Upgrade your operating system to windows 7.

**Comment by Vasniktel** [comment]
My Windows is SP3

**Comment by Vasniktel** [comment]
SP3 is already installed
