### ISSUE TITLE
Request: Remote VPK installation.

### ISSUE THREAD

**Issue by IcySon55** [TheOfficialFloW/VitaShell#199]
Would be nice to see a remote VPK installation option.

Similar in usage to FBI on the 3DS. Pass the system a URL and have it download and install a VPK from a web server.

Bonus: QR Code support for URLs. (Do we have camera control in homebrew yet?)

Edit: The benefits here are that with only 2GB of space left, you can install a 1.8GB VPK as well as it taking less time overall since the transfer and installation happen at the same time.

**Comment by limyz** [comment]
The vitaskd has provisions for camera support but doesn't have an utility to grab the QR code. Refer to http://docs.vitasdk.org/camera_8h.html

**Comment by bel3atar** [comment]
meh, of course it won't 
qr code decoding must be coded separately
