### ISSUE TITLE
Give the user a human-readable explanation for the most common errors

### ISSUE THREAD

**Issue by devnoname120** [TheOfficialFloW/VitaShell#200]
Here are some ideas:

- 0x???????? : Too big sce_sys/* images, try reducing them with pngquant
- 0x80010016 : Subdirectory limit reached
- 0xFFFFFFFD : VPK is corrupted
- 0xFFFFFFFF : generic error (file might be PFS-encrypted)

**Comment by limyz** [comment]
@devnoname120 Feel free to list all error codes. Since there's a library of them, leaving them to the Internet or a separate file (e.g readme.txt) may be a feasible option.

**Comment by devnoname120** [comment]
I don't really have more errors in mind. What do you mean with "there's a library of them"?

**Comment by limyz** [comment]
https://www.vitadevwiki.com/index.php?title=Error_Codes
