### ISSUE TITLE
Several options

### ISSUE THREAD

**Issue by BenMitnicK** [TheOfficialFloW/VitaShell#201]
Add pic0 (For Customizer)
    Add background image random "20 max" (For Customizer)
    Add language selection in options
    Add of the selection of themes in the options
    Add noPreview image and square+triangle button image to theme folder
    Add DataBaseMenu (right joystick => Left to activate the menu)
    Add PluginsManager (Right joystick => Up to activate the menu)
    Add language of the different menu and options in the language file
    Add color options for different menus
    Add credit (activate with triangle in the HOME Directory)
    Settings menu remapped to LTRIGGER+START  (For Customizer "Screenshot"")
    ToolBox reactivate LTRIGGER+SELECT
    Move color.txt language.txt and setting.txt to .ini file (For Customizer best read in TextEditor)

    See screenshot in my web site http://bmk.hamtek-solutions.com/index.php/29-psvita/39-vitatoolbox-1-1

**Comment by TheOfficialFloW** [comment]
Where is the source code of your mod? Respect the license mate...

**Comment by BenMitnicK** [comment]
Yes but I have not finished I clean the source code before the upload I finish an integration then it will be available I count to do it

**Comment by BenMitnicK** [comment]
Source code available but my code maybe not clean because I'm new in programming and C

http://bmk.hamtek-solutions.com/plugins/hitcounter/counter.php?file=VitaToolBox_1.1_sourcecode.tar.gz
