### ISSUE TITLE
USB mass storage mounts as read only

### ISSUE THREAD

**Issue by khomyaque** [TheOfficialFloW/VitaShell#205]
VitaShell USB mass storage mounts as read only on my two Win7 machines. 
Tested versions 1.5 and 1.51. Tried rebooting Vita and Windows, reinstalling VitaShell.
Read access works fine, FTP is okay as well.

Strangely, when I connected mass storage for the first time, its write access worked nicely, but soon after it only allowed me to read from mounted storage.

**Comment by TheOfficialFloW** [comment]
Do a chkdsk

**Comment by khomyaque** [comment]
It did not help.
