### ISSUE TITLE
Default to FTP on the PSTV

### ISSUE THREAD

**Issue by gnmmarechal** [TheOfficialFloW/VitaShell#208]
It's a very minor thing, but by default it still is set to USB, and then says it isn't available. Perhaps FTP should be set as default on the PSTV.

**Comment by timbru31** [comment]
Even better, maybe explain that uma0: and then ux0: need to be mounted (I was confused at first - I know, I know README and things) 👍

**Comment by TheOfficialFloW** [comment]
https://github.com/TheOfficialFloW/VitaShell/commit/eb6048a8f2825e43a92407f1478661c2a22440ec
