### ISSUE TITLE
Vitashell 1.60 Mount usb error

### ISSUE THREAD

**Issue by kamuixx** [TheOfficialFloW/VitaShell#209]
Error C2-12828-1 Error C2-12828-1 ux0:data/psp2core-1489793657-0x000028381-eboot.bin.psp2dmp
What, I can do ?

Kindly Regards

**Comment by DarkSynopsis** [comment]
I'm not even getting to the mounting point, when pressing /\ in the 'home' section it crashes with that error.

**Comment by Fallenleader** [comment]
Shot you a tweet, does the same for me as it does for @DarkSynopsis
Going to attempt to remove the latest version and let it auto update from 1.43 to the latest possible, then manually update incrementally.

**Comment by DarkSynopsis** [comment]
Just tried installing 1.5, 15.1 and 1.60 while opening and closing after each install and still crash :(

**Comment by eluu4262** [comment]
Hey @Fallenleader I'm at the step where your hit /\ and a menu pops up and select "Mount USB ux0", when I click on this, the menu stays on the screen, then the screen goes black. Is this normal?
