### ISSUE TITLE
New function:Screensaver for OLED when extracting archive?

### ISSUE THREAD

**Issue by Cinnamoni** [TheOfficialFloW/VitaShell#21]
It would help OLED Vita owners if it had a screensaver function to avoid burn-ins when extracting archives. A slideshow would work too.

**Comment by limyz** [comment]
Just use a black background for now. See attached.
![black](https://cloud.githubusercontent.com/assets/8562888/18174784/6195468c-70a1-11e6-95ee-ac026bdb58ab.jpg)

**Comment by TheOfficialFloW** [comment]
Fixed in 0.9, auto old-off after 3min by system.

**Comment by devnoname120** [comment]
@TheOfficialFloW It doesn't seem to work here (using VitaShell 1.2). The screen never shuts off or turns black.

**Comment by devnoname120** [comment]
Between 0.86 and 0.9, the only change related to the screen is the removal of [this line](https://github.com/TheOfficialFloW/VitaShell/compare/2893fb8768194b1aee1601f5332451973574faa9...a39b48954f03c5d0e5d1fc594baa328c1eb2934b#diff-2d6a4a738ceb8495048f4b03daa2f4cfL109):
```C
sceKernelPowerTick(SCE_KERNEL_POWER_TICK_DISABLE_OLED_OFF);
```

Is it enough to let the screen go to sleep? It doesn't work on my PS Vita, and I could not find any configuration in the system menu allowing to change the screen-off time.

**Comment by TheOfficialFloW** [comment]
Power save settings

**Comment by devnoname120** [comment]
Never mind, my joystick was stuck. It works correctly now.
