### ISSUE TITLE
1.60 error 0xfffffff

### ISSUE THREAD

**Issue by Bananasplitter** [TheOfficialFloW/VitaShell#213]
Hi! I'm currently having this problem with Vitashell 1.51v it asks me to update it to 1.60v, but alas after my vita downloaded the update and tried to install it, this error pop-ups, "Error 0xffffffff". I hoping someone would help me about it. Thanks in advance.
![dsc_0228](https://cloud.githubusercontent.com/assets/26497349/24068986/58c02f28-0bd7-11e7-853f-6583b16a972f.JPG)

**Comment by ZeroDk** [comment]
I got the same problem hope someone tell how to fix that error :(

**Comment by joel16** [comment]
Just download the VPK and manually install it? https://github.com/TheOfficialFloW/VitaShell/releases/download/1.60/VitaShell.vpk
You guys are mindlessly blowing up his GitHub notifications.

**Comment by Bananasplitter** [comment]
I already tried that, but it still has an error, "Error 0x80101114" after it manually installed. 
![dsc_0228](https://cloud.githubusercontent.com/assets/26497349/24069299/4910698c-0bdf-11e7-9fec-094d1d4b6a82.JPG)

**Comment by andutrache** [comment]
just got the exact same couple of errors.
to fix it just install vitashell from molecularshell.

**Comment by Bananasplitter** [comment]
You mean I need to freshly install a new molecular shell and the new version of vitashell? Wouldn't that brick my vita in any case?

**Comment by joel16** [comment]
No, once you install henkaku, it will by default install molecular shell. Once you have molecular shell running copy over the vitashell.vpk to your PS TV by ftp. Then install it on molecular shell.
