### ISSUE TITLE
Weird issues\bugs with VitaShell 1.61...

### ISSUE THREAD

**Issue by alpakeno** [TheOfficialFloW/VitaShell#216]
The latest version of VitaShell 1.61 have a two issues\bugs:

1- when selecting a file or folder I cannot scroll\select the exactly item i want, it scroll very fast using the pad,
also when selecting item in context menu.

2- when opening\viewing png image ( or any image ) it automatically zoomed-out to 10% and cannot be zoomed-in or be viewed as normal  ( this issue also available in v1.5x as i have reported it, but it got closed with invalid tag! )

Tried everything, rebuilding database, restored vita settings, removed VitaShell and settings then installed it, reinstalled TaiHENKaku, but still the same issue.

VitaShell v1.43 and previous versions doesn't have these issues at all.

Tested on Vita 3G 1000 series.

**Comment by alpakeno** [comment]
I would like to confirm that when unplugged the headphone jack from the PSVita the two issues are gone,
and when plug it in back it comes back again ( the same as issue [#219](https://github.com/TheOfficialFloW/VitaShell/issues/219) )

**Comment by limyz** [comment]
Refer to #219.

**Comment by alpakeno** [comment]
The first issue has been solved, but the second one still not fixed in v1.62
