### ISSUE TITLE
What are the Mounted USB drive limitations?

### ISSUE THREAD

**Issue by piotrekhenry** [TheOfficialFloW/VitaShell#217]
Could you include some additional information in the documentation concerning the following questions:
1. What is the maximum size supported ?(1TB ? 2TB ? 4TB? other ?)
2. How many Bubbles can be crated / stored on a mounted USB drive ?
3. Can the drive have more than 1 partition present ? If Yes - Does the Fat32/exFat partition have to be first or have other requirements (cluster size / partition type (primary / extended)?
4. Could other filesystems be supported in the future (NTFS / ext1/2/3 / other)?

**Comment by limyz** [comment]
Just reread this and this is not a helpdesk to generic problems faced by VitaShell.
