### ISSUE TITLE
Headset causing strange issues in VitaShell 1.61

### ISSUE THREAD

**Issue by Zeroba** [TheOfficialFloW/VitaShell#219]
It seems when a headset is plugged in (It may be headphones too, but the ones I'm testing have an in-line mic) Vitashell thinks the right stick is being held down.
I noticed as soon as I unplugged my headset, any image I was viewing would stop zooming out, and the fast-paced menu navigation stopped as well.
But as soon as I plug it back in, it would begin to zoom the image out and the menu navigation would begin to skip selections again.

**Comment by alpakeno** [comment]
Also would like to confirm that when running VitaShell in Safe mode this issue is gone otherwise it will be there.

**Comment by TheOfficialFloW** [comment]
https://github.com/TheOfficialFloW/VitaShell/commit/718ca49305b09145db933c4aa67f905444e4a053

**Comment by alpakeno** [comment]
scroll\selection has been fixed, but for image viewing it's still not fixed... see issue #216
