### ISSUE TITLE
Using "Mount USB ux0" freezes VitaShell

### ISSUE THREAD

**Issue by Vidalizer** [TheOfficialFloW/VitaShell#220]
When I plug in my USB Flash drive formatted FAT32 or exFAT into my PSTV. "Mount uma0" works fine, but when I try to "Mount USB ux0", the menu freezes and it won't work. I have used many different USB flash drives, but none of them work. :(

**Comment by TheOfficialFloW** [comment]
Leave to the livearea and resume the app may help

**Comment by Vidalizer** [comment]
Hey TheFlow0, thanks for your reply! I have tried it, and it works sometimes. But when I successfully mount USB ux0 and can use my USB as a memory card,  I find that if I when am installing a small homebrew app (i.e. Whitelister), it is painfully slow. Is this normal? Thanks!
