### ISSUE TITLE
How to know through an app if ux0: is memcard or USB ?

### ISSUE THREAD

**Issue by CelesteBlue-dev** [TheOfficialFloW/VitaShell#221]
Hi TheFl0W. Thanks for all you did on Vita scene.

I need for one of my apps to know if ux0: is currently memcard or USB.
I think I can get it using vitashell_kernel.suprx but I am not sure.
Please help me. This will be so useful.

Thank you thank you. Bonnes chances dans tes études ;)

**Comment by limyz** [comment]
Not a VitaShell related issue.

**Comment by CelesteBlue-dev** [comment]
Could you at least answer please ?

**Comment by limyz** [comment]
I am not even sure what you are doing. Refer to vitasdk or request help through dev channels.

**Comment by TheOfficialFloW** [comment]
Load both modules as shown in init.c. Then use the library.
