### ISSUE TITLE
error c1-2755-9 upon disconnecting USB cable from PC.

### ISSUE THREAD

**Issue by sutiam** [TheOfficialFloW/VitaShell#222]
This issue is not about **pstv**, I don't have one.

But everytime after I finished transferring files from PC to Vita in USB mode, the error code **c1-2755-9** pops up as soon as the USB cable is disconnected.

If I were to close Vitashell and re-open it, another message tells me that the file is _corrupted_ and thus renders Vitashell unusable; very strangely, MolecularShell shows the exact same error message.

Reboot the system and run HENkaku again fix the problem though. I'm using vitaShell 1.6.1

**Comment by Duxter7** [comment]
You have to always disconnect usb cabel by pressing O. Otherwise you'll get that error.

**Comment by Rinnegatamante** [comment]
To me this specific error pops out right when i try to close the USB connection with O.
Also, it will bring back to Livearea and whatever you try to start, it will tell you that the files are damaged like if some partition is not currently remounted correctly, forcing me to restart my console.

This happened right after i updated from VitaShell 1.5.1 to 1.6.1 using the internal updater (on older version everything was working correctly).

**Comment by VermillionRED** [comment]
This also happens to me.  I have to follow the same steps as Rin.

**Comment by BohemianGeek** [comment]
Hi. This is now happening to me as well, after updating to 1.7.4. Error c1-2755-9 upon disconnecting USB using the O button, "This file is corrupted" when re-opening VitaShell, the only way to get pass that error is to reboot my vita and rebuild the database.

**Comment by Dimmidice** [comment]
I have the same issue. Never ever had it before switching to SD2Vita. Frequently since. I do press O to exit USB and all that.  Would love to hear of a fix if anyone knows one.
