### ISSUE TITLE
ftp on vita

### ISSUE THREAD

**Issue by toomanylegos** [TheOfficialFloW/VitaShell#226]
whenever I connect my PSvita to power but it is already charged so it does not except power and than i turn on FTP through vitashell but instead of the usual message it says usb connected and when i hit cancel it comes up with an error and all data is then corrupted :(. This is very annoying because I have to reset system and re-transfer all my stuff. also in the settings i have it set to start ftp when select is pressed.

**Comment by limyz** [comment]
Disconnect the USB cable then attempt to use FTP first
