### ISSUE TITLE
Wrong sorting order by name!

### ISSUE THREAD

**Issue by alpakeno** [TheOfficialFloW/VitaShell#227]
These is the correct orders:
SLOT_0
SLOT_1
SLOT_2
SLOT_10
SLOT_11

Instead of that, VitaShell shows these orders:
SLOT_0
SLOT_1
SLOT_10
SLOT_11
SLOT_2
SLOT_3

**Comment by CelesteBlue-dev** [comment]
The first order you show is never used.
The second order is the one used in Windows File Manager for exemple.

**Comment by TheOfficialFloW** [comment]
Fixed in https://github.com/TheOfficialFloW/VitaShell/commit/4a31ac8100672bc49883b06a1a87a99575225ca4
