### ISSUE TITLE
PS TV Mounted USB Memory Card & Game Updates

### ISSUE THREAD

**Issue by Brolijah** [TheOfficialFloW/VitaShell#228]
I couldn't find much information about this online, so I'm curious if it is related to odd install path bs.

I've two games so far that have been obtained through the PSN Store to my USB drive and have updates available (Thomas Was Alone and Amnesia: Memories). From what I've read, after downloaded, game updates should install the next time it is launched. However, that isn't happening. The games launch and play normally as they did before and the update is still "waiting to install." If I back to the LiveArea and return to the game I'm prompted to close the game to apply the update. Again, it doesn't start any update when launching the game.

Once again, I'd like to reiterate: Is there is some issue with the updates and the USB path; skipping installing the game update? If more info is needed I'll provide what I can.

**Comment by limyz** [comment]
Not a VitaShell related problem.

**Comment by MegaPramuk** [comment]
If it works with an actual memory card but not USB ux0 mounting, then yes. It is a problem related to VitaShell's USB mounting.
