### ISSUE TITLE
Export Media - Fails when USB mounted as ux0:

### ISSUE THREAD

**Issue by RePod** [TheOfficialFloW/VitaShell#231]
What does work: ( ***uma0:*** not mounted as ***ux0:*** )
---
- Exporting an MP3 from ***ur0:*** or ***ux0:*** *to* ***ux0:***
- Copying the MP3 over through the Music app via Q/CMA

What does not work: ( ***uma0:*** mounted as ***ux0:*** )
---
- Exporting an MP3 from ***ur0:*** or ***ux0:*** *to* ***ux0:***
  - VitaShell error **`0x8010530B`**
- Copying the MP3 over through the Music app via Q/CMA while not mounted, mounting, and replicating the folder structure
  - Error starting playback in Music app
- Doing the above, but the USB device is empty for the first time mounting
- Downloading the MP3 from the web browser
  - System error **`Could not install.(C2-11934-8)`**
- Refreshing the livearea or rebuilding the database
- Unmounting ***uma0:*** as ***ux0:***
  - Exporting to original ***ux0:*** VitaShell error **`0x8010530B`**
  - Also cannot start playback of original audio from original ***ux0:***

The MP3 in question is nothing special. 40KB, 5 seconds of generally white noise. However, I would assume any other acceptable media is affected.

Honorable mention: Screenshots via PS+Start are fine.

**Comment by salamcast** [comment]
What is your USB drives filesystem? exFAT?  I now have a 2TB drive as FAT32 and Export Media is working with MP4 videos, but not MP4 (m4a) audio.  it could be a filesystem problem if you're using exFAT, I had problems with it before on the most current version of VitaShell v1.62 using exFAT.
