### ISSUE TITLE
HOME (SAFE MODE)

### ISSUE THREAD

**Issue by piteralx** [TheOfficialFloW/VitaShell#234]
Hello!
I just installed the henkaku.
I'm having a problem with safe mode, I don't know how to turn to "unsafe mode" and copy archives to vita

![20170512_160437](https://cloud.githubusercontent.com/assets/28658809/26013095/4267ce1c-372d-11e7-92d3-ce5b7b0ce7dc.jpg)
![20170512_160409](https://cloud.githubusercontent.com/assets/28658809/26013094/424c8e2c-372d-11e7-8a38-603dea05ee57.jpg)

**Comment by CelesteBlue-dev** [comment]
wait a bit, or open Settings app, go to HENkaku Settings and Enable Unsafe apps.

**Comment by rumpeltizkin** [comment]
Same goes for me. I have a PSTV and the option "enable unsafe mode" or whatever it is called is totally missing. Then I go to molecule settings and it drives me to the sony main settings, nothing related with molecule nor vita shell.

Is this a bug?

**Comment by TheOfficialFloW** [comment]
Open official settings bubble. The settings menu has been moved

**Comment by rumpeltizkin** [comment]
Yes!, I just found it searching through all menus inside the console. I'm new to Vita menu and that was the issue, not the program. Now I can see lots of folders with a different disposition.

Thank you for replying so fast! :)

**Comment by Tacohan** [comment]
(SOLVED) Found a solution. I feel soo stupid for not finding this before. you have to go into your system settings, click henkaku settings, and check enable unsafe mode. youre done. now launch vita shell again. youll now be able to utilize the tool. IF Henkaku settings are not there then if youre running 3.66- 3.68 then youll have to launch the H-encore app. and install Henkaku. youll have to install it like this every time you turn your vita off. only way to avoid having to do this process is to install enzo. however Enzo has not been released yet to the 3.66- 3.68 firmware yet. once enzo has been fully released then install it immediately. ps make sure you turn off auto updates in your system settings so you wont run into any problems in the future by having random system updates ruining your hacks. hope this helps
