### ISSUE TITLE
Nethostfs support?

### ISSUE THREAD

**Issue by krossvas** [TheOfficialFloW/VitaShell#236]
As now it is possible to do an "USB as memory stick" trick, seems it is time to implement also nethostfs trick we used on PSP?

So this https://github.com/yubo/nethostfs_for_psp
or this https://github.com/joel16/Custom-Firmware-Extender/blob/master/cfe_redirect/wifihost.c

**Comment by limyz** [comment]
Feel free to submit a PR for the functionality. Do note that FTP is already implemented on VitaShell, making file transfers possible over WiFi.
