### ISSUE TITLE
Mounting USB Storage on Linux doesnt work!

### ISSUE THREAD

**Issue by SilicaAndPina** [TheOfficialFloW/VitaShell#241]
Using linux mint 18, KDE Plasma verison.

when i go to mount usb storage via dolphin i get this error

An error occurred while accessing '60.1 GiB Removable Media', the system responded: The requested operation has failed: Error mounting /dev/sdb at /media/silicaandpina/22CA-0086: Command-line `mount -t "exfat" -o "uhelper=udisks2,nodev,nosuid,uid=1000,gid=1000,iocharset=utf8,namecase=0,errors=remount-ro,umask=0077" "/dev/sdb" "/media/silicaandpina/22CA-0086"' exited with non-zero exit status 1:
stdout: `FUSE exfat 1.2.3
'
stderr: `ERROR: unsupported FAT count: 2.
'

**Comment by ml-** [comment]
Yea, it's documented nowhere. However there is a workaround for this.

Check this issue:
https://github.com/TheOfficialFloW/VitaShell/issues/178

**Comment by SilicaAndPina** [comment]
thx
