### ISSUE TITLE
VitaShell always freeze if you edit .txt to much

### ISSUE THREAD

**Issue by julienkoenig** [TheOfficialFloW/VitaShell#243]
If you edit .txt data (or other if you can edit it) and edit it multiple times in one at once (open it; edit something; save; open again; edit again etc. ) it will always freeze after a time. (No crash, just freeze (if you try to leave the edited data)) 
You can close VitaShell and start it again, and anything work fine till you edit again multiple times. 
(I will test now if it's a specific amount of times after which it freezes and add the information)

-it's my first time reporting a bug on github, if I made a mistake, just correct it ;-)

**Comment by julienkoenig** [comment]
So, i've made 5 .txt's ("freeze test.txt"; "freeze test2.txt"; and so on), all empty.
I've opened the first with VitaShell, and added "1× editiert", saved, opened again and changed the "1" to a "2".
It freezed always if I tried to change "10× editiert" to "11× editiert" , it freezed in the moment I pushed (X) to open the Vita Keyboard, so I couldn't even change the "10" to a "11". (I've said it freezes by saving, that was wrong. It freezes by opening the Vita Keyboard. My bad..)
Of course it's the newest VitaShell (1.62), but I'm quite sure the problem exists longer.

**Comment by julienkoenig** [comment]
In short: it's freezing if i try to edit 11 times in a row

**Comment by Nkekev** [comment]
Hello, I'm currently editing some saves with Vitashell and I've exactly the same problem. The save is average 1MB long and when i try to edit multiples row (between 5/10), it freezes when you try to edit another row.

**Comment by Nkekev** [comment]
Ok it happens kind of randomly, sometimes 3 row, sometimes 5...

**Comment by Sir-Charles** [comment]
I also get this freeze problem when editing multiple times. Not just editing text files but also just renaming any folders or files. Basically if I do anything that uses the keyboard more than just a couple times it'll lock up and I have to close/reopen VitaShell. Not really a big deal since it doesn't happen often and it's not a crash that creates error logs, but it is repeatable.

**Comment by TheOfficialFloW** [comment]
Fixed in https://github.com/TheOfficialFloW/VitaShell/commit/a9f68eb47569948e5c182483e0efb0f6ff695bc2
