### ISSUE TITLE
Error C0-15009-5 after mounting USB as ux0 VitaTV

### ISSUE THREAD

**Issue by Nefarus** [TheOfficialFloW/VitaShell#244]
I was using Adrenaline, playing a GBA backup on a mounted USB HDD.  The power to the USB went out without me noticing.   I clicked save state on the emulator, and it gave me odd results.   I closed Adrenaline, and unmounted the USB with VitaShell.   Then I tried to mount as ux0: and it gave me error code C0-15009-5.   I rebooted the vita, and tried with the same USB, which gave the same error.  I rebooted, and tried with several other USB drives, all with the same error.  I reformatted the memory card,
reinstalled 3.60, and did a system restore, but the same error keeps coming back.  Everything else seems to work normally, I just cant mount USB disk as ux0:

**Comment by TheOfficialFloW** [comment]
Did you try formatting your usb drive yet?

**Comment by Nefarus** [comment]
I had several drives lying around that I tried, but I'll format one now and try it.

**Comment by Nefarus** [comment]
Using a freshly formatted drive worked.  Thank you for taking the time to help.   Odd that the other drives I had lying around wouldn't work unless formatted.  I didn't format any of them the first time I used them either.   Anyway kep up the good work!  It's much appreciated!
