### ISSUE TITLE
VitaShell 1.62 (Patching) bug

### ISSUE THREAD

**Issue by roahnosh** [TheOfficialFloW/VitaShell#245]
Installing patch removes the original game assets.

As an example I installed Minecraft. This is file structure after installing the game:

	Common
		Media
			font
				CHT
				JPN
				KOR
				Mojang Font_11.ttf
				Mojang Font_7.ttf
				Mojangles.ttf
	...

And after installing the patch 01.36 (as an example) I got this instead:

	Common
		Media
			font
				CHS
	...

As you can see, Vitashell 1.62 indeed copied the patch files to the app0 directory but have also removed the existing assets.

And when I tried to run the game obviously I got an error.

This also happens with other games like Freedom Wars.

This has been a problem that I have observed in a while now. When copying files I use molecularShell 1.62 and when installing vpk games I use VitaShell 1.42.

**System**:

- PSN Spoofing = enabled
- Unsafe = enabled
- Spoofing enabled = enabled
- Spoofed version = 3.65
- Henkaku version: R10 (v10.01) Tue, Jun 6 @19:58:29

**Comment by roahnosh** [comment]
Forgot to mention, I installed game and update using the install folder.

**Comment by TheOfficialFloW** [comment]
I have removed the ability to install patches.
