### ISSUE TITLE
[USB mod only issue PSV]Transfer issue via cable.

### ISSUE THREAD

**Issue by Zexceil** [TheOfficialFloW/VitaShell#246]
When "uma0" is mounted to "ux0" and transfer is set to USB cable, the Vita memory card is mounted to computer instead of the USB mass storage device.

**Comment by TheOfficialFloW** [comment]
https://github.com/TheOfficialFloW/VitaShell/commit/eb6048a8f2825e43a92407f1478661c2a22440ec
