### ISSUE TITLE
PSTV FTP connection over LAN drops?

### ISSUE THREAD

**Issue by DuIslingr** [TheOfficialFloW/VitaShell#251]
So basically with idk recent combination of henkaku and VitaShell updates( i say recent as i haven't used either in a few months), maybe even Windows when I FTP, the connection seems to like drop after a while. Filezilla still accepts the login and stuff, but then its stuck waiting for a response and I have to relaunch VitaShell and stuff for it to work again. It basically starts timing out after a while.

Note I am connecting this over a direct LAN to PC. I share my connection through my Ethernet port to the PSTV and it has never had issues like this before so idk.

**Comment by Rufis01** [comment]
I can confirm this. Even with enso it happens, after a bit it starts to get very slow and sometimes it times out.

**Comment by Hking0036** [comment]
can confirm I'm experiencing the same on my pstv over wifi on 1.74.

**Comment by Hking0036** [comment]
Okay, I kept trying and figured something out. On larger (>1 GB) files, it tends to throw an error saying "inactive for 20s" but if I occasionally move the stick on the controller it keeps going. Must be something to do with the pstv's inactive mode or power save, but I still have wifi on power save on, so no idea what could be causing it.
