### ISSUE TITLE
MacOS unmount/remount problem

### ISSUE THREAD

**Issue by steliosaa** [TheOfficialFloW/VitaShell#254]
**_Information:_**
-My setup = (MacOS Sierra 10.12.6 + Enzo + PSVita-1000+ VitaShell 1.62)
-VitaShell mounts fine with the MacOS.
-When ejected from the MacOS, VitaShell and molecularShell exhibit "The File is corrupt" error every time you run them, and requires a PSVita restart to be fixed so that it can run again.
-When ejecting by pressing "O" on the PSVita, then VitaShell ejects/unmounts fine and it works. The MacOS however doesn't like this and exhibits a "Not ejected properly" notification 

**_The Issue:_**
-The VitaShell after this type of unmounting (pressing "O" on PSVita) cannot be remounted to the MacOS unless you manually delete the folders created by MacOS on ux0:
a) .fseventsd/
b) .Spotlight-V100/

**_Suggestion:_**
-AutoDelete script of these 2 folders when pressing "O" to unmount the USB connection since this seems to fix the problem

![image](https://user-images.githubusercontent.com/26743665/29059913-df6af962-7c17-11e7-96ce-40f52cc04d6e.png)

**Comment by coderobe** [comment]
```
-When ejected from the MacOS, VitaShell and molecularShell exhibit "The File is corrupt" error every time you run them, and requires a PSVita restart to be fixed so that it can run again.
```
I get this on Windows 10 as well, when using "Eject" on the drive from Windows Explorer. This does not happen every time and i am not sure what exactly causes it.

**Comment by TheOfficialFloW** [comment]
Fixed in https://github.com/TheOfficialFloW/VitaShell/commit/5a376ca464ac7bd4db75f88d4ca6cd2ba5abfd53
