### ISSUE TITLE
Reason for creating a rif?

### ISSUE THREAD

**Issue by llakssz** [TheOfficialFloW/VitaShell#255]
https://github.com/TheOfficialFloW/VitaShell/blob/16e2e1eeaf4a8ebac7cb7c90071dd75369bbd5b2/package_installer.c#L39

I see when anything is installed, a rif file is created.
But for decrypted contents, it is not necessary. (Correct? From my testing, yes.)

Unlike real content from sony, the rif is not needed, so why tell the vita create a junk rif?

Instead of `scePromoterUtilityPromotePkgWithRif`, how about `scePromoterUtilityPromotePkg`? :)

Thanks

**Comment by yifanlu** [comment]
When I wrote the package installer, the first method didn't work so I tried the second one (with rif) and found the only difference was the second one creates a rif so...

**Comment by llakssz** [comment]
Ok, strange. Thanks for the answer
