### ISSUE TITLE
Install from URL / Using QR code

### ISSUE THREAD

**Issue by devnoname120** [TheOfficialFloW/VitaShell#258]
It would be nice if VitaShell could install a VPK from a url or [from a QR code](https://www.reddit.com/r/vitahacks/comments/6tln7k/vitashell_fork_vpk_installs_from_qr_codes/).

This would enable people to install homebrews such as [vhbb](https://github.com/devnoname120/vhbb/) without any access to a computer. I would be glad to set up a short link and a QR code for this homebrew.

**Comment by TheOfficialFloW** [comment]
VitaShell is supposed to be a community project. So if you want it, create a PR (please don't say you're already busy with other projects again, I'm really sick of hearing that).

**Comment by limyz** [comment]
Refer to https://github.com/TheOfficialFloW/VitaShell/issues/199. This has been brought up before.

**Comment by devnoname120** [comment]
Related: https://github.com/henkaku/henkaku/issues/82

When this happens, I will make a VHBB installer in the form of a SELF.

**Comment by TheOfficialFloW** [comment]
https://github.com/TheOfficialFloW/VitaShell/commit/f90ffa53e2e08d802b461be457d0b8017cd93792
