### ISSUE TITLE
Memory Leak When transferring files. 

### ISSUE THREAD

**Issue by phant0mg33k** [TheOfficialFloW/VitaShell#259]
When you transfer ad lage amount for files between say /:Uma0 to /:Ux0. Vita shell with eventually run out of memoery. I transferred about 12 directories and each ranging from 100 files to 1000. Vita shell hit an error.  The device needed to be rebooted 2  times to clear the the out the error.

**Comment by limyz** [comment]
Sony proprietary filesystem limitation
