### ISSUE TITLE
Viewing photos with headphones bug

### ISSUE THREAD

**Issue by t1ckk** [TheOfficialFloW/VitaShell#260]
There's a bug in VitaShell when I'm using my headphones. Viewing png file (image) in VitaShell minimises the photo to the minimum 10% zoom automatically and you can't zoom in, because it resets to 10% instantly.

**Comment by limyz** [comment]
Refer to #216 and #252

**Comment by limyz** [comment]
Fixed in https://github.com/TheOfficialFloW/VitaShell/commit/98f7ba3d5d49dbfc39826e9b51b384819d0c1282
