### ISSUE TITLE
Other partitions for USB connection

### ISSUE THREAD

**Issue by Rinnegatamante** [TheOfficialFloW/VitaShell#263]
Didn't check accurately if that was suggested before but would be nice to select what partition to show up during USB connection if possible especially now that we have SD2VITA / PSVSD and several users are starting using uma0: partition consistently.

**Comment by TheOfficialFloW** [comment]
https://github.com/TheOfficialFloW/VitaShell/commit/9385a487066c624b433255ce1177b145bf0ec0b9
