### ISSUE TITLE
Pressing Start when ux0 is not mounted results in a crash

### ISSUE THREAD

**Issue by shinji257** [TheOfficialFloW/VitaShell#264]
I didn't see this reported.

If ux0 happens to not be mounted for some reason then pressing Start will result in C2-12828-1 and crash the app.  I don't know many scenarios where this would come up but one such scenario is where the sd2vita card wasn't inserted but the driver to mount it ux0 was loaded.  This (in itself) also results in the system giving a prompt to format a non-existent card but I ignore that and tell it to do nothing.

VitaShell is setup to run from ur0.  It runs properly if ux0 is mounted and available.

**Comment by TheOfficialFloW** [comment]
https://github.com/TheOfficialFloW/VitaShell/commit/eb6048a8f2825e43a92407f1478661c2a22440ec
