### ISSUE TITLE
VitaShell delete my language when I reboot the PS Vita

### ISSUE THREAD

**Issue by Keizel** [TheOfficialFloW/VitaShell#265]
Each time that I reboot the PS Vita, Vitashell delete "spanish.txt" lenguage of VItaShell/language and I must put the file again on "language" folder.

**Comment by TheOfficialFloW** [comment]
explain

**Comment by Keizel** [comment]
This happen only with the lastest translate spanish.txt of VitaShell-Themes. When I put "spanish" file on "language" folder don't happen until I reboot PS Vita. I put another "spanish.txt" translate and this don't happen, it must problem of that file, I will commit it to VitaShell-Themes with correct language file.
