### ISSUE TITLE
imc0: can't be mounted without a memory card inserted

### ISSUE THREAD

**Issue by ubergeek77** [TheOfficialFloW/VitaShell#266]
I'm using an SD2Vita adapter, with a plugin that mounts the SD2Vita as ux0:, and a Vita Memory Card as uma0:, if it is inserted.

If I have a memory card inserted, there's no issue - I can access ux0:, uma0:, and imc0: as expected. But if I don't have a memory card inserted, I can't mount imc0: in VitaShell. Strangely, imc0: is still completely accessible, because if I use VitaShell to mount the USB storage, it will mount imc0: on the PC I'm plugged in to.

Since imc0: is accessible anyway, it would be nice to be able to mount it in VitaShell, without needing to have a memory card inserted.

**Comment by TheOfficialFloW** [comment]
Fixed in this commit https://github.com/TheOfficialFloW/VitaShell/commits/master
