### ISSUE TITLE
FTP client 

### ISSUE THREAD

**Issue by Dragoon1010** [TheOfficialFloW/VitaShell#27]
have the opposite option, you can connect the PS Vita to an FTP started on a PC to download files or stream file.

**Comment by dude22072** [comment]
What would this accomplish that can't already be done with the current FTP setup?

**Comment by Dragoon1010** [comment]
currently , it's necessary to have the pc side you, to put the files on the psvita. Whereas with a server started on the PC, you can connect anytime, anywhere, via the psvita .

**Comment by limyz** [comment]
Pretty much pointless in my opinion. If it's ain't broken, there is no need for a fix. There is no difference is the setup you described with the current one.

**Comment by Dragoon1010** [comment]
sorry for my bad english, i'm french ^^. But yes, i search FTP client for my vita ^^.

**Comment by gordon0001** [comment]
yes a ftp and smb client integrated into vitashell would be nice. then i could connect to my NAS to download/transfer files without the need of a pc/mac.

i guess the ftp client is easier to make, dont know if there are any smb libs for vita are available yet or have been ported.

**Comment by Mored1984** [comment]
Make the VitaShell work as background when activating FTP client

**Comment by theorywrong** [comment]
@Mored1984 Your request does not make sense

An repository system (Like Cydia) could be nice instead of a ftp client
