### ISSUE TITLE
Livearea refresh error

### ISSUE THREAD

**Issue by ness151** [TheOfficialFloW/VitaShell#272]
I seem to be having trouble with the system not refreshing the livearea after using other users game dumps.

I am still able to use my own cart-to-data dumps, but when I try to use other, confirmed working dumps, using the livearea refresh function still returns 0.

I've formatted my memory card, I've formatted my vita, I've made sure no other plugins are running, I've restarted the vita, all return the same undesired effect.  My vita no longer sees any other game dumps except my own.

**Comment by TheOfficialFloW** [comment]
I'm sure your dumps are missing the fake license.

**Comment by ness151** [comment]
They aren't.

**Comment by TheOfficialFloW** [comment]
Wtf?!

**Comment by ness151** [comment]
Excuse me, I think you were a little quick to close my issue.  To clarify, I've tested two of the same game dumps (mine, and another persons), all files are there, work.bin is in the sce_sys\package folder, while mine shows up and plays just fine, theirs doesn't.  They tested mine and both dumps show up.

**Comment by TheOfficialFloW** [comment]
Everbody else can install just fine. How can it be different for you unless the mistake is on your side?

**Comment by TheOfficialFloW** [comment]
Send me the dumps then

**Comment by ness151** [comment]
How would like you recieve them? email?

**Comment by TheOfficialFloW** [comment]
Yes

**Comment by ness151** [comment]
...I think I'm going to chalk this up to hardware failure.  The memory card in question is throwing up 0x80AF5025 errors on any vpk that I try to reinstall.  I think I may have to consider this closed.
