### ISSUE TITLE
VitaShell 1.71 can't copy decrypted files while using "Open decrypted" PFS decryption

### ISSUE THREAD

**Issue by s1cp** [TheOfficialFloW/VitaShell#273]
I can decrypt game folders just fine with the new PFS decryption functionality, which I can confirm by looking at pictures inside sce_sys folders, but there is no way to import or export decrypted files out of it. I tried copying a picture from a PFS decrypted folder to ux0: and check it with VitaShell and Windows, but the file remained PFS encrypted.

Edit: FTP works for copying files out of decrypted PFS, but you can't copy them out of the decrypted folder inside VitaShell itself.

**Comment by TheOfficialFloW** [comment]
Fixed https://github.com/TheOfficialFloW/VitaShell/commit/3c5378c017cad801511c621d7985c1cbe3a37364

**Comment by TheOfficialFloW** [comment]
in v1.71 you are able to copy out from path ux0:app/TITLEID/. copy out from ux0:app/TITLEID/folder/ will not work due to a bug.
