### ISSUE TITLE
QR Code open web browser not always working

### ISSUE THREAD

**Issue by pyroesp** [TheOfficialFloW/VitaShell#274]
I've been testing the new QR code reader and it doesn't always open the web browser (correctly ?). The link is displayed fine in VitaShell but opening the link gives a C2-13696-5 error code. I suppose this is from the web browser as VitaShell does not crash/freeze.
VitaShell v1.71

**Comment by TheOfficialFloW** [comment]
Is this still an issue in v1.73?

**Comment by cxziaho** [comment]
Yes, but I have patched this (as well as improved file downloading) in my next update that should be out hopefully in 30 minutes.  Just have to finish testing different file types.

**Comment by TheOfficialFloW** [comment]
@cxziaho I sent you an invitation for being a collaborator, so you can directly submit your commits here

**Comment by cxziaho** [comment]
The error C2-13696-5 occurs when it is trying to open a URI that is just a blank string, so I'm assuming this issue was cause by `last_qr` being reset before the URI could be launched.

**Comment by cxziaho** [comment]
Ok.  Will commit when I'm finished :)

**Comment by TheOfficialFloW** [comment]
If you're motivated, may you also add uncommon dialog width limitation?

**Comment by cxziaho** [comment]
I might tomorrow.  I should be studying right now lol, but just thought I would add 'one small fix' which took a while.

**Comment by pyroesp** [comment]
Looked at the code yesterday and thought about an empty string too. Didn't have time to test a fix. Also didn't see the new version today. I'm currently at work so won't be able to test the latest release.

**Comment by TheOfficialFloW** [comment]
https://github.com/TheOfficialFloW/VitaShell/commit/9ed04d7b22128c58031d8ba738c113f6cc52cafd
