### ISSUE TITLE
psvsd mounting as usbdevice on 1.71 not working

### ISSUE THREAD

**Issue by EdDude** [TheOfficialFloW/VitaShell#275]
On ver. 1.70 mounting psvsd works perfect. On ver. 1.71 vitashell is asking for inserting a SD Card. I got an psvsd running as memory card.

**Comment by TheOfficialFloW** [comment]
https://github.com/TheOfficialFloW/VitaShell/commit/6ca9db843b85d6c86562704e36b214ebe69e6691

**Comment by EdDude** [comment]
Sorry i don't understand this link to the code. I tried again, but it´s not working for me. I just stay on 1.70.

Sorry i'm very new Github and coding.

**Comment by TheOfficialFloW** [comment]
Check if v1.72 fixes this bug

**Comment by EdDude** [comment]
Yes it works! Thank you!
