### ISSUE TITLE
UMA0 has disappeared on file explorer

### ISSUE THREAD

**Issue by baldman89** [TheOfficialFloW/VitaShell#276]
When I updated Vitashell from v1.6x to v1.72 Uma0 location (configured as Sony 8gb memory card) has disappeared from the file explorer, and I don't know why...

**Comment by baldman89** [comment]
Ok, you closed it, but the problem still exists.
Can you tell me why you closed it or what can I do to repair it?

**Comment by TheOfficialFloW** [comment]
no idea, but it's working for me

**Comment by baldman89** [comment]
Okey, I will uninstall and reinstall it, is the only thing that I can do...
If the problem persists, I will go back to v1.6x

Thanks anyway for answering.

**Comment by TheOfficialFloW** [comment]
did it disappear from the list or from the triangle menu?

**Comment by baldman89** [comment]
It disappeared from the home list of devices (only appears os0, pd0, sa0, tm0, ud0, ur0, ux0, vd0 and vs0), and when I push triangle, the only available options are "refresh livearea" and "unmount USB Ux0"

P.D: I was on triangle menu and few minutes later, an error appeared and the application closed. When tried to re-enter it said that was damaged. Rebooted system and now works (but still without Uma0 in the list)

**Comment by TheOfficialFloW** [comment]
I asked you to test v1.6x again. did you do that?

**Comment by baldman89** [comment]
I tried to update the app and it doesn't do the update, so maybe it's corrupted.

I need to uninstall it and reinstall, but I need another vpk installer like molecular, because when I try to install Vitashell 1.63 vpk it says "error 0x80101114", same as if I try to install 1.73 vpk version.

Now I don't have too much time for it, but few hours later I will retry to install it from another ways.

Thanks!!

**Comment by baldman89** [comment]
Edit: Finally on the second try, I was able to update to 1.73 by WiFi (Uma0 problem still exists), but I can't go back to 1.63 due to that error.

**Comment by TheOfficialFloW** [comment]
Install it over molecularshell.

**Comment by TheOfficialFloW** [comment]
OR copy and paste eboot.bin manually

**Comment by baldman89** [comment]
Ok, I will try it on the evening, maybe it's good to have molecularshell in this cases...but MLThaku doesn't came with it.
I will try to install molecularshiell first.

**Comment by baldman89** [comment]
Now it works with the last update, I uninstalled it and reinstalled.

Thanks
