### ISSUE TITLE
Pressing Triangle in Home Area Crashes VitaShell

### ISSUE THREAD

**Issue by MightyBobBarker** [TheOfficialFloW/VitaShell#277]
EDIT: Version 1.72

I get the following error when I press triangle in the home area:

An error has occurred in the following application.
(C2-12828-1)
Saved Core File Succeeded.
ux0:data/psp2core-1505698142-0x00002b2957-eboot.bin.psp2dmp

**Comment by MightyBobBarker** [comment]
As additional information, I use PSVSD with usbmc. Here is the information from the file I listed above:

Exception  Prefetch abort exception
Thread ID 0x40010003
Thread name VITASHELL
EPC  0x00000000
Cause 0x00030003
BadVAddr 0x00000000

a1: 0x00000001
a2: 0x0DEADBEEF
a3: 0x8002D013
a4: 0x4001012F
v1: 0x8128003C
v2: 0x00040000
v3: 0x00000000
v4: 0x00000000
v5: 0x812E36A0
v6: 0x813C0B30
v7: 0x813C0630
v8: 0x812F9D34
ip: 0x89958030
sp: 0x813C0488
lr: 0x81081E5B
pc: 0x00000000

**Comment by TheOfficialFloW** [comment]
https://github.com/TheOfficialFloW/VitaShell/commit/ca7f8992303295477a7137db0caa38068a9b61f4
