### ISSUE TITLE
1.73  update cant mount hdd PSTV

### ISSUE THREAD

**Issue by WaterCoolFool** [TheOfficialFloW/VitaShell#278]
Hello,

After this update now I can not mount my external hdd to the pstv

**Comment by TheOfficialFloW** [comment]
Do you have usbmc plugin installed?

**Comment by TheOfficialFloW** [comment]
Reboot your device too

**Comment by TheOfficialFloW** [comment]
Give me precise details man, how the f*ck am I supposed to help you otherwise?

**Comment by WaterCoolFool** [comment]
Sorry about that, 

I did not need the plug in before I will install that now

**Comment by TheOfficialFloW** [comment]
No you don't need it

**Comment by TheOfficialFloW** [comment]
Delete ux0:VitaShell, reboot and try again

**Comment by WaterCoolFool** [comment]
I used the plugin as suggested.  Now the hdd drive  is recognized and booting from the drive. Thank you for your help. I will be sending a donation as soon as I get paid
