### ISSUE TITLE
QR Code can't download from direct URL.

### ISSUE THREAD

**Issue by cxziaho** [TheOfficialFloW/VitaShell#280]
When downloading from a URL like [https://vitadb.rinnegatamante.it/get_hb_link.php?id=307](url), it works fine, but downloading from a URL like [https://github.com/cxziaho/qrdemo/releases/download/v1.0/qrdemo.vpk](url) causes the error saving the file - error 0x80010016.  This is most likely because there are still special characters after `while (strstr(strdup(fileName), "\n") != NULL) strstr(fileName, "\n")[0] = '\0';`.  I thought I would just commit what I have done so far, I've been stuck on this error for almost an hour...

**Comment by pyroesp** [comment]
Not sure what chars are valid in a URL/URI, but you could just `\0` all the characters that aren't between 0x20 <space> and 0x7A <z>.

**Comment by cxziaho** [comment]
The code is used to strip excess characters of of the file name stored in the header.  When directly linking to the file, it doesn't have quotations around the file name, so I am inserting `\0` at the newline (otherwise I put it at the quotation mark), but it still can not save with this strong as the filename.  
[This](https://twitter.com/cxziaho/status/909641036699279361) here is a photo of the header in the modal.

**Comment by pyroesp** [comment]
Network stuff is not really my forte but does the VitaShell URI / sceNetwork stuff have automatic redirection ? I'm guessing it does looking at the server name on your photo...
I'll see what I can do this afternoon.

**Comment by TheOfficialFloW** [comment]
`strcpy(fileName, fileName);` this is ugly

**Comment by TheOfficialFloW** [comment]
There is white space at the end of the path that's why it fails

**Comment by cxziaho** [comment]
Thought it would be something like that.  (also I was just testing with `strcpy(fileName, fileName)` haha)

**Comment by TheOfficialFloW** [comment]
I'm going to fix it and make it all cleaner.

**Comment by TheOfficialFloW** [comment]
can you give me a link example where there is `filename=\` ?

**Comment by cxziaho** [comment]
[https://vitadb.rinnegatamante.it/get_hb_link.php?id=307]( https://vitadb.rinnegatamante.it/get_hb_link.php?id=307) urls like this which don't directly link to the file (or at least VitaDB uses `"`)

**Comment by cxziaho** [comment]
Or it could be a coincidence...  I have just been using GitHub releases and VitaDB files (both .vpk and non vpk)

**Comment by TheOfficialFloW** [comment]
https://github.com/TheOfficialFloW/VitaShell/commit/9ed04d7b22128c58031d8ba738c113f6cc52cafd
