### ISSUE TITLE
QR Code won't open URL in webbrowser

### ISSUE THREAD

**Issue by pyroesp** [TheOfficialFloW/VitaShell#286]
Haven't checked the source yet, but v1.74 doesn't open valid URL in webbrowser. It just displays "QR code says: ...".
Didn't see in the readme that this functionality was removed so I guess this is a new bug ?

**Comment by KawaiiAurora** [comment]
https://github.com/TheOfficialFloW/VitaShell/issues/281 

The issue's already been reported and it got fixed; the patch should be included in the next VitaShell update.

**Comment by pyroesp** [comment]
My bad, didn't see issue #281. I'll close this one.
