### ISSUE TITLE
Browser not opening on QR scan - 1.74

### ISSUE THREAD

**Issue by rmzalbar** [TheOfficialFloW/VitaShell#287]
After updating from 1.71 to 1.74, a QR Code scan no longer launches the browser. A notification does open with:

QR Code Says:
http://www.qrcode.com/test.zip (fake URL for illustration purposes)
x OK

..but the browser doesn't launch. This worked in 1.71. Running Enso, no plugins other than Download Enabler (which I also removed to make sure it wasn't interfering.) I also tried rebooting, and uninstalling/reinstalling Vitashell.

**Comment by cxziaho** [comment]
This was broken is 1.74 and fixed in 12116311 so it should work again next release
