### ISSUE TITLE
ur0: for USB connection

### ISSUE THREAD

**Issue by arromdee** [TheOfficialFloW/VitaShell#288]
Similar to issue #263.

The procedure to install a sd2vita requires making sure that your config file and plugins are on ur0:.  It is awkward to do this with no way to directly copy anything to ur0: over USB.

**Comment by TheOfficialFloW** [comment]
ur0: cannot be mounted, since it will corrupt the current database

**Comment by arromdee** [comment]
Why does molecularshell allow it to be mounted then?

**Comment by TheRadziu** [comment]
@arromdee VitaShell/MolecularShell in it's latest version DOES NOT have usb support, unless you are speaking about manually updated MolecularShell (to 1.76)
