### ISSUE TITLE
VitaShell crashes when user closes USB connection

### ISSUE THREAD

**Issue by sr4mu** [TheOfficialFloW/VitaShell#289]
- Vitashell 1.74
- sd2vita mounted as ux0

After transferring data via USB, the app is crashing in these cases if done **right after** the transfer :
- Pressing "CIRCLE" to stop the USB connexion
- Unmount the USB device via OS

Vitashell then won't launch until a full turn off.

**Comment by asc-THM** [comment]
The same happens with psvsd mounted as ux0.

But only if VitaShell is on ux0 (psvsd), if its on ur0 the crash doesn't happen.

**Comment by SquallATF** [comment]
I think the new usb driver have issue
In my case on native ux0 after stop USB connection VitaShell will crash and GameCard on pc will not read after stop USB connection some times will crash too.

**Comment by moops44** [comment]
i have the same error

Vitashell 1.74
sd2vita mounted as ux0

**Comment by tamamushiiro** [comment]
I fixed this issue with a windows error check, I think.

**Comment by TheOfficialFloW** [comment]
Fixed https://github.com/TheOfficialFloW/VitaShell/commit/5a376ca464ac7bd4db75f88d4ca6cd2ba5abfd53
