### ISSUE TITLE
VitaShell crashes with error C1-2755-9 and reopening gives "The file is corrupt." error

### ISSUE THREAD

**Issue by tamamushiiro** [TheOfficialFloW/VitaShell#293]
I think it might've happened when I opened USB mode and the current displayed directory on VitaShell was a directory that I deleted while in USB mode. Too scared to reproduce LOL

**Comment by limyz** [comment]
Can you try reinstalling Henkaku? Use molecularShell to reinstall VitaShell.

**Comment by TheOfficialFloW** [comment]
It is a known bug.

**Comment by tamamushiiro** [comment]
When restarting I could run VitaShell once then it will say "The file is corrupt" error after exiting once. Fixed with Windows check for errors

**Comment by HyeVltg3** [comment]
Just like to chime in, used usbmc_installer to Mount USB as ux0:, kept erroring or "file is corrupt" when trying in VShell.
Opening Molecule is fine, only vitashell does not open after enabling usb ux0:.
Reinstall of 1.74 tried. still no dice.

**Comment by BohemianGeek** [comment]
Hi. This is now happening to me as well, after updating to 1.7.4. Error c1-2755-9 upon disconnecting USB using the O button, "This file is corrupted" when re-opening VitaShell, the only way to get pass that error is to reboot my vita and rebuild the database.

**Comment by HyeVltg3** [comment]
As stated above, 1.62 works.
switch to 1.62 while you wait for a fix. this issue seems to only affect those that are using external drives.

**Comment by limyz** [comment]
Refer to #222.

**Comment by slimshizn** [comment]
I know it's been a while, just updating that this still is giving me a file is corrupt issue. Works after a reboot though. MS still works while USB is being used as ux0.
