### ISSUE TITLE
malloc problem in file io ?

### ISSUE THREAD

**Issue by Cpasjuste** [TheOfficialFloW/VitaShell#298]
Hi,

When developing my usbhostfs module i noticed some random crash on file io. I thought the problem was in my module, but i isolated the problem to the malloc calls in "file.c". I guess you may pushing the limits there. You may be able to reproduce the crash by doing multiple times this procedure : 

- copy directory "ux0:user" to "ux0:temp" (as an example)
- delete the directory "ux0:temp"

Before posting this report i tried disabling the only user (sceshell) module i use (psp2shell), whith the same results.

**Comment by Cpasjuste** [comment]
Doing more research i found that around 106 MB is available, so i guess there's something more. I wonder if using malloc in threads (copy_thread, delete_thread..) is safe ?

**Comment by Cpasjuste** [comment]
Hi,

I'm now not sure it's a bug in VitaShell anymore :/ 
I was not able to reproduce the problem when not enabling my (kernel) usbhostfs plugin, so it may corrupt the memory (?!). I was almost sure to have this problem with no plugin enabled, but maybe i did something wrong. I'll try to take another look today and report. (by the way, malloc IS thread safe).

**Comment by Cpasjuste** [comment]
So, i can confirm the problem still happen randomly even with no plugins enabled (on enso at least). I was sometime able to do the copy more than 5 times without VitaShell crashing, sometime it crash at the first copy. It can also happen on delete.

**Comment by TheOfficialFloW** [comment]
please test 1.74

**Comment by limyz** [comment]
This problem is so similar to the one most recently posted - shall wait before tagging that as duplicate.

**Comment by Cpasjuste** [comment]
I will take a look tomorow.

**Comment by Cpasjuste** [comment]
From my testing i don't spot the problem with version 1.74. I still have random crashes when doing file io on host0 with my usbhostfs plugin, but i'm now sure it's a problem with my module. I guess you suspect the changes in the dialog code to cause this in 1.75. I would need to do more testing on 1.75 to be sure i didn't do something wrong when testing on it.

**Comment by Cpasjuste** [comment]
So, it seems i fixed my module, and there is no more problem with 1.74. I'll test again with 1.75 soon.

**Comment by Cpasjuste** [comment]
I can confirm the problem doesn't exist on 1.74 but exist on 1.75. I guess there is maybe a problem with commit this commit : c8ec848

**Comment by Cpasjuste** [comment]
I guess there is a logic problem at this line, i'll take a closer look tomorrow : https://github.com/TheOfficialFloW/VitaShell/blob/e3f52ccac7cf9284e22aafe581e1f05d37f52a30/uncommon_dialog.c#L76

**Comment by Cpasjuste** [comment]
Also, strdup should be freed, which is not the case here.
https://github.com/TheOfficialFloW/VitaShell/blob/e3f52ccac7cf9284e22aafe581e1f05d37f52a30/uncommon_dialog.c#L75

**Comment by Cpasjuste** [comment]
Fixed in dae62124a2f0b76a32e2bab85988b3fba7ff8399

**Comment by TheOfficialFloW** [comment]
Did you test the new build?

**Comment by Cpasjuste** [comment]
Yes just now, no more crash. I saw your changes in "dialog_uncommon", the problem was there for sure.

**Comment by limyz** [comment]
Awesome work
