### ISSUE TITLE
Second panel on file manager

### ISSUE THREAD

**Issue by 1upus** [TheOfficialFloW/VitaShell#3]
Hi, maybe you can add second panel in file manager like total commander/far manager.
On psp was file assistant with two panels (screenshot below).
Thx!
![image](https://cloud.githubusercontent.com/assets/21283299/18032136/4d376c0c-6d0d-11e6-914b-d06d89811601.png)

**Comment by TheOfficialFloW** [comment]
I'm not going to do that
