### ISSUE TITLE
SD2VITA/VitaShell 1.75 incompatibly

### ISSUE THREAD

**Issue by DeadWolfQc** [TheOfficialFloW/VitaShell#300]
Vitashell works well on sd2vita when using version 1.61 but when updating to the latest version (1.75) i get error corrupt, unless i need to manually update it for it to work, which i will try shortly after submitting this issue.

**Comment by DeadWolfQc** [comment]
Seems like my guess was right, you need to manually update vitashell for it to work.

**Comment by DeadWolfQc** [comment]
Seems like my guess was right, you need to manually update vitashell for it to work.

**Comment by SHROOMKINGonDMT** [comment]
that "issue" only exists when psvsd/sd2vita is mounted as ux0:

the auto update works just fine on devices that use an original memcard as ux0

**Comment by DeadWolfQc** [comment]
I suspected as much, thanks for the explanation.
