### ISSUE TITLE
AZERTY keyboard for European Vita

### ISSUE THREAD

**Issue by JigAma** [TheOfficialFloW/VitaShell#302]
Hi
In the text editor, the keyboard is QWERTY but my console is in French and AZERTY is the default keyboard in France so i think it would be nice if Vita Shell keyboard used the proper keyboard according to the System language
I don't know if all European country uses AZERTY so i guess "default keyboard" could be a setting added in the language files.

**Comment by TheOfficialFloW** [comment]
not a bug. you can easiely change the keyboard layout.
