### ISSUE TITLE
Error C2-13242-2

### ISSUE THREAD

**Issue by Zaiphon** [TheOfficialFloW/VitaShell#303]
Hey guys,

I encountered a Error when trying to install VitaShell.
Im using cfw.guide/vita/installing-henkaku.
Its tells me to visit the release page but when i try to click the vpk im getting the Error from the Title.

Any ideas?

**Comment by Zaiphon** [comment]
Why is it closed?

**Comment by limyz** [comment]
If you are getting an installation error, the file is most likely corrupted. Try redownloading the file and reattempt installation. Be sure to allow unsafe homebrew if you haven't done so.
