### ISSUE TITLE
Lots of C2-12828-1 errors in 1.75 release

### ISSUE THREAD

**Issue by Sir-Charles** [TheOfficialFloW/VitaShell#304]
These errors just started happening after updating to 1.75, I've tried using the auto install via VitaShell and installing the git release, makes no difference. Also, I get these errors on multiple Vita 1000s.

So when I'm normally using VitaShell to move/copy/delete or just browse through directories, I often get "An error has occurred... (C2-12828-1) Saved Core File Succeeded" ux0:data/psp2core-1507734383-0x0000772b39-eboot.bin.psp2dmp
But the psp2core file changes each time, here's a few more examples:
1507732923-0x00006a23c1
1507733019-0x00004526bd
1507733284-0x0000282b97
1507733379-0x0000662295
1507734105-0x0000b12e79

And I'm not sure, but it seems to happen more if I do quick actions or move through directories fast. I also get those errors when clicking on files, when before in 1.74 I'd just get an internal error but no system error or crash causing app exit.

**Comment by TheOfficialFloW** [comment]
does it happen with 1.74 too?

**Comment by Sir-Charles** [comment]
It didn't before. Now it's happening all the time, my ux0:data folder has 30+ and 1-5 min apart. I'm using SD2VITA btw. I use Mac so when transferring files I get those stupid "._" duplicate system files and idk if they'll cause problems but I like to run through with VitaShell and delete them, so I do a lot of marking/selecting and deleting.

I'm going to reinstall 1.74 and see if problem persists. But so far this 1.75 update has caused these errors on 3 different Vitas.

**Comment by Sir-Charles** [comment]
Just reinstalled 1.74 and the problem seems to be gone.. guess I'll stick that release for now. I'll upload all those psp2core files I got recently and give you a link to it. 
Hopefully you can fix this cuz I use VitaShell religiously lol. But I'm surprised no one else has posted about this yet.. surely I'm not the only one running into these consistent crashes?

**Comment by limyz** [comment]
Refer to #298.

**Comment by Sir-Charles** [comment]
Finally got around to upload these psp2core logs, kinda late but here they are just in case.. I'm not really sure if this is related to #298 but I'll check latest build to see if it fixes my crashes too.
-Thanks for all your hard work!

[VS175 error logs.zip](https://github.com/TheOfficialFloW/VitaShell/files/1385224/VS175.error.logs.zip)

**Comment by tomazzz369** [comment]
i have same error on vitashell 1.75 completely random (on copy/move folder, on open zip, on open sfo or any other file) all the time. vitashell 1.74 working fine
