### ISSUE TITLE
osk issue when opening 10 consecutive times

### ISSUE THREAD

**Issue by BaltazaR4** [TheOfficialFloW/VitaShell#305]
When using the text editor on vitashell 1.75 if I have to change more than 10 lines, the osk does not comes up makin the app unusable cause most of the buttons lock up and only the power and ps buttons work normally, it works fine on vitashell 1.51. Thanks for your great work!

**Comment by limyz** [comment]
Refer to #243.

**Comment by TheOfficialFloW** [comment]
Fixed in https://github.com/TheOfficialFloW/VitaShell/commit/a9f68eb47569948e5c182483e0efb0f6ff695bc2
