### ISSUE TITLE
Refresh Livearea or Filecopy to USB stick and/or SD Card sometimes causes corruption?

### ISSUE THREAD

**Issue by rsn8887** [TheOfficialFloW/VitaShell#308]
I am having an issue where my SD Card or USB Stick sometimes becomes corrupted. Both are FAT32.

I think it happens after I do a "Refresh LiveArea" but it might also be caused by copying files from a PC using direct USB connection. For the USB stick, I plugged it into the PC directly and copied files to it. For the MicroSD, I used Vitashell USB connection for the copying.

It is a subtle effect because it affects random folders or files and only happens sometimes.

But it happened to me twice in the last few days, once on a USB Stick used on Vita TV, and once on a MicroSD used in a Vita handheld.

Running chkdsk on the stick and sd card finds many errors. It fixes most or all of them it seems. The errors reported are mostly
- "errors in . and/or .. corrected" 
- "first allocation unit is not valid" (with a corrupted folder-/filename showing)
- "removing trailing folders"

It seems the "first allocation unit is not valid" errors are the only ones that cause real problems on Vita/VitaTV: boot-failures, certain programs crash, etc. The other errors seem less harmful.

I am not sure if this even has to do with Vitashell or not. But something is causing it. 

So it might help to double check the "Refresh LiveArea" routine in Vitashell to make sure it cannot under any circumstance corrupt the filesystem.

Upon closer inspection: Both times it was corruption in the ux0:data folder. Specifically, many psp2coredump files became corrupted, giving the "first allocation unit is not valid" error.

**Comment by TheOfficialFloW** [comment]
I can't fix this issue.
