### ISSUE TITLE
Opening zip containing many files seems to freeze UI

### ISSUE THREAD

**Issue by JohnVeness** [TheOfficialFloW/VitaShell#309]
I browsed into a zip that contained approx 3000 files and the UI seemed to freeze for 34 seconds. It would be good if you could show a spinner or a progress bar if opening the zip will take longer than, say, one second, so the user knows what's going on. Allowing the user to cancel it would be good too.

**Comment by TheOfficialFloW** [comment]
can you share the zip?

**Comment by JohnVeness** [comment]
I no longer have it to hand, but I imagine you could recreate the issue by zipping up a system folder on an OS, or any similar source with lots of files.

I remember that it particularly seemed to be the number of files that was the problem, rather than the size if the zip in MB or GB, as a similarly sized zip with only 100 files opened almost instantly.

**Comment by TheOfficialFloW** [comment]
Should be fixed in the latest release.

**Comment by TheOfficialFloW** [comment]
Will do it sometime
