### ISSUE TITLE
Uppercase of all folder names on uma0

### ISSUE THREAD

**Issue by szpieg-z-krainy-deszczowcow** [TheOfficialFloW/VitaShell#311]
After mounting USB devices as "uma0:/", every folder names are uppercase, even if they are not in reality (in example on Windows). However all applications which seeking paths in lowcase (like i.e Adrenaline 6.1-fix) recognize them.

**Comment by TheOfficialFloW** [comment]
doesn't happen for anyone else, is not a problem either.
