### ISSUE TITLE
Error 0x8010113D at the 99% of VPK installation

### ISSUE THREAD

**Issue by szpieg-z-krainy-deszczowcow** [TheOfficialFloW/VitaShell#312]
I'm not sure what kind of bug it is but it's probably related somehow to PNG. If in example I replace them by my own, the package cannot be installed. All graphics are ok because they are working if I replaced them under appmeta after installation of original VPK application.

"icon0.png" and "startup.png" are 24bit, "bg.png" are 8bit. All made by Photoshop with default plugin or SuperPNG plugin and Gimp, using different settings. Using (or not) optipng, and for 8bit using pngquant for converting background from24bit to 8bit.

If I trying installed application from folder, I getting error 0x80010001 instead of 0x8010113D.

**Comment by szpieg-z-krainy-deszczowcow** [comment]
Can be closed. It's my fault... ALL gfx must be 8bit. The fact that Vita OS accept 24bit images in appmeta mislead me that the same can be applied to VPK/ZIP.

**Comment by faelpinho** [comment]
For note: I used `pngquant --posterize 4 bg.png` and now vpk installs sucessfully with bg image.
Thank you!

**Comment by MeteorManiac** [comment]
After all of that it still won't install
