### ISSUE TITLE
Error 0x80870005 on 99% VPK installation

### ISSUE THREAD

**Issue by 1upus** [TheOfficialFloW/VitaShell#313]
The same vpk perfectly installs with AppManager PLUS by OneLua, but it cant be installed with Vitashell 1.75 :/

**Comment by TheOfficialFloW** [comment]
can you send the vpk to me

**Comment by 1upus** [comment]
Sure. Take it. Zipped vpk.

[AdrenalineBubbleManager-fork.zip](https://github.com/TheOfficialFloW/VitaShell/files/1430290/AdrenalineBubbleManager-fork.zip)

**Comment by DRok17** [comment]
Had the same issue while trying to repack a VPK. Turns out it was due to two files:

Files: work.bin and head.bin
Location: ux0:app/123456789/sce_sys/package

Remove those from the build/make files and VPK will install as normal, as those files are generated when VPK is installed.
