### ISSUE TITLE
Freezing VitaShell everytime when OSK is invoking with unmount.skprx active

### ISSUE THREAD

**Issue by szpieg-z-krainy-deszczowcow** [TheOfficialFloW/VitaShell#318]
I'm not sure if this is a VitaShell issue or unmount itself but every time when I want edit something with this module loaded (I have nothing else active besides this specific plugin), VitaShell freeze (text editor, rename function).

Would be possible to add in future to VitaShell RW/RO remounting?

**Comment by TheOfficialFloW** [comment]
Not vitashell bug
