### ISSUE TITLE
Add Database Options

### ISSUE THREAD

**Issue by RaZer0k** [TheOfficialFloW/VitaShell#319]
Add database options like refresh database and rebuild database like safe mode. (ie: https://modconsoles.fr/club-articles.html/sony/vitashellmod-175-r11/) has this funtion.
to support psm liveaction refresh.

**Comment by 1upus** [comment]
And add patch registry key CONFIG/PSM/revocation_check_req to 0 for PSM automatic activation.

**Comment by TheOfficialFloW** [comment]
nope
