### ISSUE TITLE
Partition/Drive size and free space not shown

### ISSUE THREAD

**Issue by dizz00** [TheOfficialFloW/VitaShell#320]
Partition/Drive(as in uma0,ux0,etc) size and free space is shown as "-" when the remaining free space is less than 40MB. It's become like that for my ux0, haven't tried other drive most likely will show same result, i am using sd2vita as ux0 fyi but i don't think it's the cause. I can still access it normally with no issue, just the size shown is "-"

**Comment by tomazzz369** [comment]
i can confirm. i forgot to pause pkgi downloading and now i have no free space, but i noticed vita content manager don't show free space either, i see - instead 0 KB, same as in vitashell -/-
