### ISSUE TITLE
Incorrect storage usage indication when Official Memory Card mounted as imc0; request for remounting feature

### ISSUE THREAD

**Issue by azumukupoe** [TheOfficialFloW/VitaShell#326]
I transferred some files from my PC using Adrenaline's USB connection.
It is fixed once rebooted, so I suppose remounting is required to display the correct value. 
I think you should add remounting feature.
This is happening simultaneously with https://github.com/TheOfficialFloW/Adrenaline/issues/183

**Comment by TheOfficialFloW** [comment]
Fixed in https://github.com/TheOfficialFloW/VitaShell/commit/a9f68eb47569948e5c182483e0efb0f6ff695bc2
