### ISSUE TITLE
file broken after moved to sd2vita

### ISSUE THREAD

**Issue by azumukupoe** [TheOfficialFloW/VitaShell#328]
I have to reinstall the app to use it again

**Comment by limyz** [comment]
This issue is too vague - can you elaborate what did you exactly do? Can this issue be replicated?

**Comment by azumukupoe** [comment]
@limyz 
I wasn't able to open VitaShell following these steps
But It's not a serious problem since I can use it after reinstalling it.

1. install VitaShell on the original ux0(memcard)
2. copy it onto uma0(sd2vita)
3. than use sd2vita for ux0

**Comment by TheOfficialFloW** [comment]
that's not how one does install apps....

**Comment by azumukupoe** [comment]
@TheOfficialFloW
But it's the instruction for sd2vita
other apps works just nice with this
