### ISSUE TITLE
VitaShell 1.76 Corruption when mounting USB as UX0 on PSTV

### ISSUE THREAD

**Issue by figgl001** [TheOfficialFloW/VitaShell#332]
Hi, 
Hoping someone can help me with this. I installed VitaShell 1.76 on my internal memory then copied all my files to my USB stick. Once I mounted the USB as UX0 in Vitashell and exit out of Vitashell I then cannot reload Vitashell without getting the corruption error even though all the Vitashell files are on the mounted USB. Would anyone know why this might be and what I need to do to fix this? All other apps I originally installed on my internal memory such as adrenaline 6.1 all work completely fine.

Thanks
Laurence

**Comment by bensonwind** [comment]
Do you use a memory card or not? Because I thought Vitashell won't affect ur0 if you only mount USB as ux0.

**Comment by figgl001** [comment]
This has been resolved by deleting with usb plugged in restarting and installing directly onto usb when mounted as ux0. There seemed to be some sort of conflict having it installed on the USB and internal memory.
