### ISSUE TITLE
"Move" won't work between partitions

### ISSUE THREAD

**Issue by Yoti** [TheOfficialFloW/VitaShell#335]
For example:
1) Highlight any file on the ux0, press Triangle, select Move
2) Navigate to the ur0, press Triangle, Paste is inactive

**Comment by TheOfficialFloW** [comment]
Lol

**Comment by TheOfficialFloW** [comment]
https://github.com/TheOfficialFloW/VitaShell/commit/fdc5c12059af500f19cbb5c8d97dab73bf4df8cf

**Comment by Yoti** [comment]
Thanks!
