### ISSUE TITLE
Can't connect over FTP on 0.9

### ISSUE THREAD

**Issue by razneck** [TheOfficialFloW/VitaShell#34]
Works fine on molecule 0.8 and VitaShell 0.86.
*Client is WinSCP

**Comment by TheOfficialFloW** [comment]
Reuploaded VitaShell 0.9 with old libftpvita. Hope @persona5 will take a look on it

**Comment by razneck** [comment]
Yup that works, thanks for the quick response.

**Comment by persona5** [comment]
I have resolved this. I confirm that now this works with WinSCP.
https://github.com/xerpi/libftpvita/pull/15
