### ISSUE TITLE
Can't install large VPK file in 1.77

### ISSUE THREAD

**Issue by wfscans** [TheOfficialFloW/VitaShell#342]
I believe I've found an issue with the newest version of ViteShell.  Trying to install a large VPK file(in this case 2.91GB) results in a 0xffffffff error. Trying to install the same VPK in molecularShell(1.43) or VitaShell 1.76 results in a successful install.

**Comment by TheOfficialFloW** [comment]
Fixed https://github.com/TheOfficialFloW/VitaShell/commit/46236aad99212af60c179fee176effeade629e26
