### ISSUE TITLE
allow installing packages to ur0

### ISSUE THREAD

**Issue by MarioMasta64** [TheOfficialFloW/VitaShell#345]
sometimes its useful if an application is needed in case something goes wrong you can still access said application.

**Comment by MarioMasta64** [comment]
and no need to use a seperate program to move it there

**Comment by tomazzz369** [comment]
not needed for me, but if you decide to add this option, additional option in menu (when we press start button) would be useful.

Install packages in: [choice installation dir here - ux0 or ur0]

regards

**Comment by MarioMasta64** [comment]
it is not,

**Comment by MarioMasta64** [comment]
why close this?
