### ISSUE TITLE
Fix SFO display errors

### ISSUE THREAD

**Issue by eiiiiix** [TheOfficialFloW/VitaShell#360]
with certain sfo files text is shown inside of itself (ex. SAO Hollow Fragment title name) and ive noticed this is a few other file types
not a huge problem but its a little weird to see

**Comment by AnalogMan151** [comment]
Seems like for SFO files whose values span multiple lines, the values overlap the values below them because the position of the entries does not change to make room.

**Comment by TheOfficialFloW** [comment]
Fixed: https://github.com/TheOfficialFloW/VitaShell/commit/344f7bd17cd2548e9a80a65d8732dbc1bb04ca50
