### ISSUE TITLE
Newbie: Compiling error

### ISSUE THREAD

**Issue by quyen194** [TheOfficialFloW/VitaShell#365]
I follow this instruction below:
https://github.com/TheOfficialFloW/VitaShell/wiki/Developers
I do compile on Window 10

and got error at last step: make
```
git clone https://github.com/TheOfficialFloW/VitaShell
cd VitaShell
mkdir build
cd build
cmake ..
make
```

This is the error:
```
[ 47%] Building resource /home/CongQuyenKnight/VitaShell/build/resources/umass.skprx.o
Scanning dependencies of target VitaShell
[ 48%] Building C object CMakeFiles/VitaShell.dir/main.c.obj
In file included from C:/msys64/home/CongQuyenKnight/VitaShell/main.c:19:0:
C:/msys64/home/CongQuyenKnight/VitaShell/main.h:47:10: fatal error: vitashell_user.h: No such file or directory
 #include <vitashell_user.h>
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/VitaShell.dir/build.make:348: CMakeFiles/VitaShell.dir/main.c.obj] Error 1
make[1]: *** [CMakeFiles/Makefile2:100: CMakeFiles/VitaShell.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
```

**Comment by quyen194** [comment]
duplicate
https://github.com/TheOfficialFloW/VitaShell/issues/356

**Comment by quyen194** [comment]
Sorry, I think issue is happen again
https://github.com/TheOfficialFloW/VitaShell/issues/356

I try following revision:
https://github.com/TheOfficialFloW/VitaShell/tree/4df32189df8dbf48097bfb11eebdcf71605f0d33
and my error is not happen

**Comment by TheOfficialFloW** [comment]
https://github.com/TheOfficialFloW/VitaShell/commit/b98ce6b46c821e78d3adb296ad2348d0b416a2b8
