### ISSUE TITLE
VitaOrganizer + question about promoting

### ISSUE THREAD

**Issue by soywiz** [TheOfficialFloW/VitaShell#38]
I have created a tool for organizing games and homebrew and uploading them directly to psvita without the VPK (uncompressing it in the desktop). You can download it here:
https://github.com/soywiz/vitaorganizer/releases/tag/0.1

Right it allows to process a folder VPKs, and allows you to create a small VPK with eboot + sce_sys folder and upload it to vita. After that it allows you to send all the rest files from the VPK directly without uncompressing in the vita, or even uncompressing on the computer via FTP.

Right now it requires those two steps. But it would be great if it could be just one step.
What about telling VitaShell somehow to promote something, either via a custom FTP command. Or either writting a file in the ux0: something like autopromote.txt or something like that?
That would make the whole process much more comfortable with less memory card size requirements and less time. And even allowing to push several games unassistedly.
If you like the idea, I could create a PR with the promoting stuff.

![https://raw.githubusercontent.com/soywiz/vitaorganizer/0.1/extra/screenshot.png](https://raw.githubusercontent.com/soywiz/vitaorganizer/0.1/extra/screenshot.png)

**Comment by theorywrong** [comment]
for me' the better choice is to implement an new ftp command

**Comment by TheOfficialFloW** [comment]
Be free to create a PR
