### ISSUE TITLE
I'd like to create a new file with vita shell.

### ISSUE THREAD

**Issue by developer-sp** [TheOfficialFloW/VitaShell#380]
I can not to create a new file only new folders. 
Could you look for this in the future?
![2018-02-01-173645](https://user-images.githubusercontent.com/33873743/35703352-e56a66da-0782-11e8-9bd5-42f48fa024b5.jpg)

**Comment by developer-sp** [comment]
Yep, I tried this, but there is other problem, the file encode. I failed copying ux0:id.dat for to rename pkgi.txt, not work because enconding(UTF-8).

**Comment by RY0M43CH3N** [comment]
copy any other file with the SAME extension, if you want a .txt file, search a file name.txt and change the name to pkgi.txt and use it.

**Comment by alpakeno** [comment]
sounds like a good option.
