### ISSUE TITLE
"Open Decrypted" does not work on savedata.

### ISSUE THREAD

**Issue by koutsie** [TheOfficialFloW/VitaShell#383]
If you Goto ux0:user/00/savedata/titleid press triangle and goto "Open Decrypted"
it will open the directory like it normally would for a game however the files in the directory are still encrypted.

**Comment by satelliteseeker** [comment]
Doesn't work on addcont either (Error 0x80010013).

**Comment by TheOfficialFloW** [comment]
Added: https://github.com/TheOfficialFloW/VitaShell/commit/61b7b03194fd7a5d65a848798059d2e092de4cd1
