### ISSUE TITLE
Error with HDD in Vitashell

### ISSUE THREAD

**Issue by MrCampy** [TheOfficialFloW/VitaShell#391]
Hello,

When I took 30 seconds with the HDD as a ux0 is disconnected and the connection is interrupted due to the fact that the power is turned off USB. This only occurs to me with Vitashell and I didn't happen with previous versions. Do you somehow cannot turn off the USB Power with Vitashell open? 

Thanks

**Comment by TheOfficialFloW** [comment]
Not an issue of VitaShell.
