### ISSUE TITLE
Improve drive compatibility

### ISSUE THREAD

**Issue by hellzknight666** [TheOfficialFloW/VitaShell#392]
I just purchased a 2TB external drive and a Y adapter for external power. P/N: WDBYFT0020BBK-0B

Whatever I try my PSTV running VitaShell 1.81 fails to detect it. I've changed it from GPT to MBR. I've tried ExFat and Fat32. I've tried different wall USB power adapters. 

Or alternatively a supported device page would be nice to have so we don't have to do trial and error to find a device that works. I know some people have gotten 2TB drives to work, but I have no idea what the model numbers for those drives are.

Thanks in advanced. All I really want is a 2TB volume mounted as ux0 so if I could get a model recommendation I would be very happy with that. I don't mind returning my drive to the store.

**Comment by Chef-Curry** [comment]
I'm having the same issues with a 1TB Mypassport HD. Any solutions? Maybe I'm doing something wrong.

**Comment by rsn8887** [comment]
Try to not connect the HD directly but through a powered USB 2.0 (NOT USB3) hub, e.g. Amazonbasics or some such. That worked for me.

**Comment by Chef-Curry** [comment]
Is USB 3.0 the problem?

**Comment by rsn8887** [comment]
Yes USB 3 was the problem for me. The hub solved that issue.

**Comment by TheOfficialFloW** [comment]
Not an issue of VitaShell.
