### ISSUE TITLE
Wrong "banner" verision

### ISSUE THREAD

**Issue by fedelodo** [TheOfficialFloW/VitaShell#394]
I've just installed vitashell 1.82, it says vitashell 1.82 on the top but the bubble still says vita shell 1.81.

**Comment by TheOfficialFloW** [comment]
if you manually copied eboot.bin, then the livearea will not be updated

**Comment by dephunk** [comment]
Is there anyway of manually updating/editing the livearea version?

**Comment by ShroomKing** [comment]
edit app.db   or

replace the template.xml in ur0:appmeta/VITASHELL/ with the one from the 1.83 vpk and reboot   or

replace everything in ux0:app/VITASHELL/ with the content from the 1.83 vpk and reboot.

**Comment by ShroomKing** [comment]
i meant rebuild database on the last one, just a rebuild won't do it

**Comment by ShroomKing** [comment]
*just a reboot won't do it.

jeet, my autocorrect hates me today apparently

**Comment by ShroomKing** [comment]
*jeez...

**Comment by dephunk** [comment]
this didnt work & now half of my Sony bubbles are blank...

**Comment by dephunk** [comment]
Applying the stock theme and rebooting fixed the blank bubbles but yeah still showing v1.81 in the banner lol

**Comment by ShroomKing** [comment]
> replace the template.xml in ur0:appmeta/VITASHELL/ with the one from the 1.83 vpk and reboot

that's the most simple way and if it doesn't work for you it's something on your end.
