### ISSUE TITLE
Error 0x80010016 vitashell 1.82

### ISSUE THREAD

**Issue by khanhelft** [TheOfficialFloW/VitaShell#396]
i installed cfw enso 3.65 and i'm installing vitashell v1.82 but error 0x80010016 appears

**Comment by veteransdr** [comment]
I got same problem. I already delete vitashell v1.8 and try to install v1.82 on molecular but error 0x80010016 appears

**Comment by khanhelft** [comment]
i tried installing the older version of vitashell but it still not works

**Comment by TheOfficialFloW** [comment]
if you get an error when trying to install the vpk, simply rename the vpk to zip and manually copy the eboot.bin file to ux0:app/VITASHELL/eboot.bin

**Comment by khanhelft** [comment]
i renamed vitashell.vpk to vitashell.zip and copied file eboot.bin inside it to ux0:app/VITASHELL. After, i renamed zip file into vpk file and installed it.But this error still appeared

**Comment by TheOfficialFloW** [comment]
so you‘ve installed it already

**Comment by khanhelft** [comment]
but i don't see it on my HOME PAGE

**Comment by dethboy** [comment]
I am having the same issue and I followed the same steps (rename, copy file, rename, install and fail).

**Comment by TheOfficialFloW** [comment]
if you rename and copy file manually to ux0:app/VITASHELL/eboot.bin, this is the the manual installation and you don't need to reinstall vpk after that. the livearea however will not be updated. but if it is v1.82 within the application, it's fine.

**Comment by lovelydumpling** [comment]
I think the concern in this case is they already deleted Vitashell 1.81 to install 1.82, so now they have nothing in the livearea. As such, wouldn't that keep them from using VITASHELL? Since MoleculeShell can't refresh the livearea afaik.

I *think* the only fix is a CMA backup.

**Comment by veteransdr** [comment]
Omg... U guys r so nice. Fortunately I have another 3.60 with broken buttons, so I already replaced motherboard and got 3.65 enso last night. I missed "VITASHALL 1.82 or LATER BEFORE INSTALL 3.65 enso" when I install 3.65 enso first time, then I choose wrong way again and again. Anyway thanks a lot for ur help. I should CMA BACKUP tonight.

**Comment by dethboy** [comment]
I was able to install AFTER I deleted the folder VITASHELL in the ux0/patch/ directory. The install would fail until I did that and then went perfectly.

**Comment by pepsypollo** [comment]
Can confirm that after deleting the ux0/patch/ files it let me install vitashell again via molecular.

**Comment by m6mb3rtx** [comment]
So there is a VITASHELL folder  inside **ux0:/patch** thats why it fails. Thanks for the heads up!

I was too worried so  did the BITASHELL workaround LOL.

**Comment by Louhike** [comment]
> I was able to install AFTER I deleted the folder VITASHELL in the ux0/patch/ directory. The install would fail until I did that and then went perfectly.

I still had the issue and confirm this workaround works
