### ISSUE TITLE
gpu crashes

### ISSUE THREAD

**Issue by eiiiiix** [TheOfficialFloW/VitaShell#397]
ive had this issue for awhile and just now decided to make it here
sometimes when im doing stuff like opening files the vita will have a gpu crash
when i use really early versions i do not get a gpu crash
the crashes are seemingly random and i started getting them back in 1.7
i dont remember which version exactly but i know they started in a 1.7 version

(also why am i blocked on twitter? i dont remember doing anything to you that would deserve a block...)

**Comment by richard1222** [comment]
The dev of pkgj blocked you?

**Comment by TheOfficialFloW** [comment]
Can you check if v1.83 solves this?

**Comment by yuriko192** [comment]
i seem to have this issue too, and my vitashell is currently on V1.9, my vitashell also doesnt seem to increase it's free space when i deleted my games

**Comment by eiiiiix** [comment]
@TheOfficialFloW im still getting them even in 1.9
still randomly but they seem more frequent in read only partitions
