### ISSUE TITLE
Lock buttons during install vpk process

### ISSUE THREAD

**Issue by klinux86** [TheOfficialFloW/VitaShell#40]
Hi Theflow,

I would thank you for the huge work that you are doing for PS VITA scene.

I have a request to lock the buttons during the install process because if we touch the power button or the circle button accidentally the install is canceled, can you please add it.

Best regards

Klinux

**Comment by Mored1984** [comment]
Same here, make the VitaShell work as background

**Comment by limyz** [comment]
As there are no provisions to lock the power button or PS button, this issue will be closed. The cross/circle button is required to allow the user to cancel the installation process.
