### ISSUE TITLE
Can't export photos to media using Vitashell but works via molecularshell

### ISSUE THREAD

**Issue by snintendog** [TheOfficialFloW/VitaShell#401]
Error 0x80101a02 is the code i get i have a USB Sandisk 128GB drive acting has a memory card i have the usbmc plugin auto mounting the USB as ux0: on boot henkaku enso 3.60 -10
I may be missing something i had tried to export the pictures to media in vitashell 1.83. After the failure it give me the error again when i try to go into the MMS/PHOTO on the USB drive and the MMS/VIDEO i have to do a reboot to clear the error then i can reenter the folders sometimes a restart of vitashell fixes it but not always. however using molecular shell 1.43 the export is successful

**Comment by Jgr9** [comment]
Same in 1.98, but I also get the error with molecular.  It also doesn't let you export Wav.  Error is with MP3.

**Comment by avan06** [comment]
Try removing PSVita UDCD USB Video Class plugin from config.txt (udcd_uvc.skprx)

https://www.reddit.com/r/VitaPiracy/comments/9584tb/vitashell_usb_error_0x8054360c/
