### ISSUE TITLE
vitalshell 1.83 is not updating

### ISSUE THREAD

**Issue by animekai** [TheOfficialFloW/VitaShell#406]
the new update 1.9 is out but the prompt for the update is not working at least in my case, i had 3.65 enso, i had rebooted my console and entered again in vitashell but no update prompt, i know i cant just download and install the vpk from here but, if the update funtion is there why no to use it right? maybe some people had the same problem, and for the record my wifi is ok, and in the past when vitashell had the  update was working for me, maybe a fix for the auto update were cool

**Comment by TheOfficialFloW** [comment]
You don‘t have v1.83 then

**Comment by animekai** [comment]
Sorry you were right,  my vitashell label said 1.83, but inside vitashell the version was 1.82, thats weird, but  thanks for make me check that

**Comment by animekai** [comment]
Yeah that was the problem,  i deleted the patch vitashell, reinstall the 1.83, and then the prompt pops up, it's working great
