### ISSUE TITLE
Bookmark support

### ISSUE THREAD

**Issue by Exeedy** [TheOfficialFloW/VitaShell#407]
TheFlow thank you for your awesome work!
I have one question would it be possible to add a "bookmark file/folder" feature?
That would make vitashell perfect =)

Thank you for your hard work.

Greetz

**Comment by eiiiiix** [comment]
that would be insanely useful
adding a virtual folder to all paths or an option in the menu would be great

**Comment by TheOfficialFloW** [comment]
https://github.com/TheOfficialFloW/VitaShell/commit/8eff0e6bbacaf9d51c0a7de8689bc5712e12244e
