### ISSUE TITLE
GPU crash pkgj and vitashell freespace differs

### ISSUE THREAD

**Issue by yuriko192** [TheOfficialFloW/VitaShell#408]
so recently i was downloading Akibas's Beat from the pkgj but suddenly my internet went down. the pkgj stop the download but later the system seems to show a GPU crash. i restarted the system and it seems okay at first but when i tried to redownload the game, the system crash again after about 5 or so minutes. when i see whether the downloaded files were corrupted or not through vita shell i saw the size on my ux0:/ was about 9 gb but from the pkgj was about 6 gb.

*note: i dont know whether this is a pkgj or vitashell bug so i decided to go with both

**Comment by TheOfficialFloW** [comment]
You realize on vitashell the used space is shown not free.

**Comment by yuriko192** [comment]
ok, just realized it sorry.
