### ISSUE TITLE
Unauthorized software?!?

### ISSUE THREAD

**Issue by Imroy** [TheOfficialFloW/VitaShell#409]
You sneaky bastard ;)
Was that what the 1.9 update was for?

**Comment by SilicaAndPina** [comment]
![dznukqqv4auibit](https://user-images.githubusercontent.com/18594213/38163843-0f5d158a-3557-11e8-8c5b-37d4b7746038.png)
APRIL FOOLS! :D

**Comment by SilicaAndPina** [comment]
no. 1.9 added support for decrypting trophys and savedata.

**Comment by robin840211** [comment]
happy april's fool ;)
