### ISSUE TITLE
VitaShell music player broken

### ISSUE THREAD

**Issue by TheOfficialFloW** [TheOfficialFloW/VitaShell#41]
@ribbid987 I couldn't try the music player yet, as it crashes. No idea why. Hope you are going to improve it.

**Comment by ribbid987** [comment]
I tired mp3 file with the following Specs:
Format: MPEG Audio
File size: 2.60 MiB
Duration : 2 min 50 s
Overall bit rate mode : Constant
Overall bit rate: 128 kb/s

Audio
Format : MPEG Audio
Format version: Version 1
Format profile : Layer 3
Mode : Joint stereo
Mode extension: MS Stereo
Duration: 2 min 50 s
Bit rate mode: Constant
Bit rate: 128 kb/s
Channel(s): 2 channels
Sampling rate: 48.0 kHz
Compression mode : Lossy
Stream size: 2.60 MiB (100%)

**Comment by littlebalup** [comment]
It crashes on my PCH-1004 to. Same issue with v0.86.

**Comment by ribbid987** [comment]
With the Spec above it should work. What are your specs?

**Comment by TheOfficialFloW** [comment]
It is not good to have an incomplete, and no longer maintained audio player feature. We should add support for any .mp3 file, not only specific ones.

**Comment by ribbid987** [comment]
Is this not a Limitation by sceAudiodec?

**Comment by TheOfficialFloW** [comment]
It seems like, yeah. We should use a library instead.

**Comment by Pheeeeenom** [comment]
I've tried playing audio in those settings and it still crashed.

**Comment by Mustafastar** [comment]
HI MAN....
i want to add new language to vita shell
i want to add ARABIC language and i finished file translation.
HOW I CAN ADD THIS LANGUAGE PLEASE ?
THANKS SO MUCH WITH LOVE ...

**Comment by littlebalup** [comment]
Made some kick tests. Works only with raw encapsulation, MP3 codec, 48.0 kHz.

Here a sample that works:
[test_raw_48khz.zip](https://github.com/TheOfficialFloW/VitaShell/files/457419/test_raw_48khz.zip)

**Comment by Pheeeeenom** [comment]
Ah, that's what it was. Raw encapsulation

**Comment by TheOfficialFloW** [comment]
I have added it myself
