### ISSUE TITLE
Vitashell 1.9 psn error ws-37337-3

### ISSUE THREAD

**Issue by lamlam77777** [TheOfficialFloW/VitaShell#410]
When open vitashell, this error code shown.
And only this application will have this problem.

**Comment by lamlam77777** [comment]
System enso 3.65
Mai dump/nnd/legit game can play
Other homebrew can use
System app can access
And no email about the ban

**Comment by robin840211** [comment]
happy april's fool :)

**Comment by SilicaAndPina** [comment]
dude WS-37337-3 is a ps4 error.. wrong fucking console.. go ask on ps4shell's issues
