### ISSUE TITLE
date time bugged out

### ISSUE THREAD

**Issue by leovel0728** [TheOfficialFloW/VitaShell#413]
after the ban message on vitashell 1.9
the date and time became 33/33/33 33:33

psvita is at enso 3.65 firmware.

**Comment by JesterIOS** [comment]
I can confirm this

![2018-04-02-170023](https://user-images.githubusercontent.com/30769120/38192531-9036d4b6-3697-11e8-964b-68c3a4056f7d.png)

**Comment by TheOfficialFloW** [comment]
M33
