### ISSUE TITLE
QR Scanner C2-13696-5

### ISSUE THREAD

**Issue by Scrxtchy** [TheOfficialFloW/VitaShell#414]
I've been using QRs to Github Release VPKs for a while
I'm not sure when it stopped working, since I hadn't used the Vita a lot after I picked up a switch but whatever.

When scanning a github URL, instead of prompting to install the VPK, it's a prompt to open the URL.
Accepting the prompt returns a `C2-13696-5` Error, which was fixed in bdbcb869c28239b84ec5c6f7d51ad509a9aba28d

Unsure if this would be a 3.65 issue, or if github's TLS changes have done anything

**Comment by devnoname120** [comment]
I can confirm I have the same issue here, using VitaShell v1.94 on 3.60.

I doubt it's an SSL issue since [SSL verification is disabled altogether](https://github.com/TheOfficialFloW/VitaShell/blob/81a2a7d0e81f713ad4ba3a83de6fddcc41430aa3/init.c#L275).

**Comment by devingDev** [comment]
VitaDB links don't work at all. Vitashell says "Do you want to open this URL: " but its empty and opening it creates an error C2-13696-5

https://vitadb.rinnegatamante.it/#/info/380

**Comment by devnoname120** [comment]
That's likely the same issue as this: https://github.com/devnoname120/vhbb/issues/39

**Comment by xPsIXx** [comment]
The address appears sometimes if i repeatedly scan the QR code alternating between holding L or R before pressing the other trigger.

**Comment by lucciu5** [comment]
I have same issue using VitaShell 2.02 on 3.60

**Comment by Scrxtchy** [comment]
If @devnoname120 is correct, than using this plugin should solve the problem. I have been able to download files with TLS1.2 just fine with itls on 3.65
https://github.com/SKGleba/iTLS-Enso

**Comment by mizifih** [comment]
> If @devnoname120 is correct, than using this plugin should solve the problem. I have been able to download files with TLS1.2 just fine with itls on 3.65 https://github.com/SKGleba/iTLS-Enso

This one didn't fix for me.

> The address appears sometimes if i repeatedly scan the QR code alternating between holding L or R before pressing the other trigger.

But this one, strangely, at least made vitaShell read the URL, it didn't worked in the end though, got an Error: 0x80010016 message.

**Comment by Scrxtchy** [comment]
Your vita is giving you a SCE_ERROR_ERRNO_EINVAL error, likely during the install process, depending what vpk it is there's already other issues for this code

**Comment by shre-linux** [comment]
> I've been using QRs to Github Release VPKs for a while I'm not sure when it stopped working, since I hadn't used the Vita a lot after I picked up a switch but whatever.
> 
> When scanning a github URL, instead of prompting to install the VPK, it's a prompt to open the URL. Accepting the prompt returns a `C2-13696-5` Error, which was fixed in [bdbcb86](https://github.com/TheOfficialFloW/VitaShell/commit/bdbcb869c28239b84ec5c6f7d51ad509a9aba28d)
> 
> Unsure if this would be a 3.65 issue, or if github's TLS changes have done anything

I found a perfect solution, I know this sounds ridiculous but just install and .vpk file once before scanning the QR code, if you cant find one, thentry this
delete the pkgj app then reinstall it using vitadb or vita deploy
When you launch pkgj after re installing it will ask to install an update and you have to choose yes
Then the vpk file of the new version of pkgj will be saved on ux0:/pkgj/ (here is the vpk)
When you install this vpk, idk how but it fixes the ability to scan QRs and install apps,
 I think that installing any vpk fixes this but this pkgj vpk fs fixes this lmao
