### ISSUE TITLE
Some of the VPK install very slow less than 100 KB/s with VitaShell >1.76

### ISSUE THREAD

**Issue by swkiew** [TheOfficialFloW/VitaShell#417]
Hi, I have this problem for sometime and I decide to submit the issue. When installing some of the Vpk, I have issue with VitaShell 1.77 to 1.9 which the installation are very very slow (<100KB/s). If I use VitaShell 1.76 and below, the Vpk will install at normal speed. So I have to keep on switch between VitaShell 1.9 and 1.76 for this issue. Thank you.

**Comment by TheOfficialFloW** [comment]
Duplicated https://github.com/TheOfficialFloW/VitaShell/issues/402

**Comment by LilCiro** [comment]
I made a video about it, link https://www.youtube.com/watch?v=tyDL5xHf-3Q&ab_channel=LilCiro
