### ISSUE TITLE
Define error messages instead of useless errors like 0xFFFFFFFF

### ISSUE THREAD

**Issue by TheOfficialFloW** [TheOfficialFloW/VitaShell#435]
Happens for example on .vpk's whose TITLEID is longer than 9 characters.

**Comment by eiiiiix** [comment]
yeah
current issues are quite useless
i install a vpk
it throws a error at me but installs successfully and works
and i just sit here confused as hell

**Comment by korgano** [comment]
This is also useful for diagnosing issues like USB flash drives failing to mount as uma0.

**Comment by TheOfficialFloW** [comment]
https://github.com/TheOfficialFloW/VitaShell/commit/57d1f62368263889e28386ea2713561b7b8c7aeb
