### ISSUE TITLE
introduce bookmarks

### ISSUE THREAD

**Issue by abertschi** [TheOfficialFloW/VitaShell#436]
This issue discusses the introduction of bookmarks to VitaShell. Here are some design ideas:

- symlinks
  - FAT is a Microsoft Filesystem format and does not support symlinks https://msdn.microsoft.com/en-us/library/windows/desktop/ee681827%28v=vs.85%29.aspx

  - PS Vita recognises FAT partitions https://vitadevwiki.com/vita/File_Management

Given these limitations, bookmarks cannot be implemented with native symlinks.

- introduce VitaShell specific symlinks
  - 0xF11E0000
  - introduce magic number, 4 bytes, followed by a softlink string pointing to a target file
  - A symlink can point to a folder or file (and also to other symlink)

- When opening a file
  - Check for magic number
  - Check for valid path 
  - Resolve link or open file when above invalid

- UI changes
  - New Menu entry:
     - Bookmarks
       - Show: changes CWD to bookmark folder
       - Add

Bookmarks are just files. Can be deleted/ renamed manually. Initially they have the same name as their target file/folder

**Comment by abertschi** [comment]
Status update: I think the menu entries are better placed this way:
- New
   - Add Bookmark
- More
   - Bookmarks
   - Recent files

Should I use the L or R Key for a shortcut jump to the bookmark directory?

**Comment by TheOfficialFloW** [comment]
https://github.com/TheOfficialFloW/VitaShell/commit/8eff0e6bbacaf9d51c0a7de8689bc5712e12244e
