### ISSUE TITLE
Cant install vpks 0x80010002

### ISSUE THREAD

**Issue by Feelsrat** [TheOfficialFloW/VitaShell#440]
Cant install any vpks to any drive after assigning ux0 to sd with any storage manager.
Thank you :)

**Comment by haltdef** [comment]
Also experiencing this issue. Various sources on the Internet suggest the microSD is usually at fault, however I have tried 3. Tried an alternative sd2vita adapter too. All out of ideas now!

**Comment by Feelsrat** [comment]
Figured it out a few days ago. Just downloaded the whole memory card with ftp then later copied it all to the sd and then it's all good. Probably some dependencies in the original files somewhere idk
