### ISSUE TITLE
d-pad on vitashell wont work 

### ISSUE THREAD

**Issue by zakariajo** [TheOfficialFloW/VitaShell#442]
hi sir  i dont wanna be an ass or something and this is the first time asking you about something and i am sorry in advance if i said something wrong , i was fallowing you on twitter while ago but you block me  for no reason even i never comment or said anything bad in your account :) i want to ask you ,  i have problem with vita shell the d pad wont work at all , its working on games and stuff but when i try to navigate through the vita shell folders i cannot  use the d pad , and sorry again :) 
PS / don't block me please :)

**Comment by ydlaz** [comment]
Same problem with me. Also the "select" button is not working wherein you need to press to enable usb. Any help is highly appreciated.

**Comment by ydlaz** [comment]
found that my analog stick has problem, that's why i cannot use the d-pad to browse thru the directory. I hope there will be an option on the next release to disable the analog stick.
