### ISSUE TITLE
Ask only once for an install all if the list contain at least one Unsafe homebrew

### ISSUE THREAD

**Issue by onaryc** [TheOfficialFloW/VitaShell#449]
I'm using the install all option to update a bunch of unsafe homebrew (emulator, ports, tools, ...). This option is convenient, but each time a new install starts, i have to confirm the permission (and when i update/install a dozen of applications it is a bit annoying).

I understand the need to warn the user, but would it be more convenient to scan all homebew installer, make a list of unsafe ones, display it to the user and ask him to confirm the permission only once if needed?

**Comment by TheOfficialFloW** [comment]
Added option to disable it: https://github.com/TheOfficialFloW/VitaShell/commit/36a16a48ea22b01f4a15de015bc07cea5e9e52c2

**Comment by onaryc** [comment]
Thanks :)
