### ISSUE TITLE
Failed! 0x80431075 

### ISSUE THREAD

**Issue by WindbreakerHD** [TheOfficialFloW/VitaShell#458]
so when I  try to install vita shell everytime I get this 
>downloading vitashell
>downloading eboot.bin
>Failed! 0x80431075 
now what am I supposed to do no one seems to have this problem Iv gone as far as having to fromat my vita (also for other reasons as it wouldnt update) but now Im stuck any help would be great!

**Comment by BenChoad** [comment]
I had the same issue yesterday across all of my devices. I finally managed to fix this issue by connecting my vita to my mobile hotspot rather than my router, and it worked instantly.

Restarting my router, using a friends etc did nothing to help (although we both use the same ISP, so may be related?)

**Comment by sweeching** [comment]
If anyone using h-encore to install vitashell and it failed with this code, follow this guide (it worked for me with PS TV FW 3.68): https://psvitamod.com/vitashell/

Basically use Qcma to allow Vita's content manager to connect via USB cable, and use PSImgTools' easy installer to install the vitashell via Qcma transfer. Good luck.

**Comment by navyvetpdx** [comment]
funny your comment was only 2 days ago. im having this damn issue now as well. had the vita permanently modded for the kids and the vita stop giving errors when opening any game. so ive erased and formatted it to start over and now i cant even get vitashell downloaded. so frustrating. gone through that link you posted and cant for the life of me open up QCMA and changed its preferences. like it runs in the backgound but nothing opens up. fucking stumped.

**Comment by KI11TI11** [comment]
I've been struggling with this issue too until I brought up the internal settings and hit rebuild database then vitashell popped up and magically started working again I hope this helps

**Comment by Alex18-03** [comment]
got a bit of a problem , i mean i did everything the site listed and instructed users to do but when i open the content manager on my ps vita it shows the 5kb apps which then are turned into errors

**Comment by mannyzv** [comment]
> got a bit of a problem , i mean i did everything the site listed and instructed users to do but when i open the content manager on my ps vita it shows the 5kb apps which then are turned into errors

u fix it?
