### ISSUE TITLE
Failed! 0x80431075 

### ISSUE THREAD

**Issue by dckiller21** [TheOfficialFloW/VitaShell#462]
I am getting the error when trying to install vitashell through h-encore, I have tried reformating, manually putting together h-encore and i cant find anything that will let me install it it, 
it fails after trying to download eboot.bin

**Comment by dckiller21** [comment]
k i found to way to download vitashell without using h-encore (still need to have psvita hacked/cracked), just needed to download psvimgtoolsfrontend which will allow you to transfer a vitashell application setting it up like you do for h-encore

**Comment by sweeching** [comment]
If anyone using h-encore to install vitashell and it failed with this error code 0x80431075, follow this guide (it worked for me with PS TV FW 3.68): https://psvitamod.com/vitashell/

Basically use Qcma to allow Vita's content manager to connect via USB cable, and use PSImgTools' easy installer to install the vitashell via Qcma transfer. Good luck.

**Comment by Masamune3210** [comment]
@sweeching  please for the love of all that is unholy, STOP SPAMMING ISSUES.
