### ISSUE TITLE
Please help getting error 0x8054360C when trying to connect via usb to my pc

### ISSUE THREAD

**Issue by Apollobladedx** [TheOfficialFloW/VitaShell#465]
this started happening after i used auto plugin to install some plugins so that might have something to do with it but I'm not sure.

**Comment by Ladyzz** [comment]
Try removing udcd_uvc.skprx line from your config.txt file and that should fix it. I guess that plugin changes usb somehow for streaming instead of usb connecting with vitashell.

**Comment by Apollobladedx** [comment]
oh thanks that makes sense ill give it a try

**Comment by Apollobladedx** [comment]
yup as suspected this worked like a charm thanks for the help
