### ISSUE TITLE
MOVING FILE(S) from a partition to another doesn't work

### ISSUE THREAD

**Issue by CelesteBlue-dev** [TheOfficialFloW/VitaShell#471]
Example:
1) select ux0:id.dat
2) Press Triangle
3) Select Move file
4) Go to ur0:
5) Press Triangle
6) ---> Select Paste file is impossible because "Paste file" is BLANKED !

Copying works as expected but moving has this issue.

**Comment by TheOfficialFloW** [comment]
Done: https://github.com/TheOfficialFloW/VitaShell/commit/fdc5c12059af500f19cbb5c8d97dab73bf4df8cf
