### ISSUE TITLE
[Request] Add pageup/down keys during file navigation

### ISSUE THREAD

**Issue by 01y** [TheOfficialFloW/VitaShell#474]
Doing this would aid in navigating directories with large numbers of files. Some other homebrew programs use left and right d-pad buttons for pageup and pagedown, respectively (which would be a good choice here), and it is very useful and effective for browsing large lists without using too much time.

**Comment by TheOfficialFloW** [comment]
Added https://github.com/TheOfficialFloW/VitaShell/commit/b1dc201f6066df23bfa117831287954c888c33ff
