### ISSUE TITLE
Prompt user file/folder name if deleting a file/folder

### ISSUE THREAD

**Issue by ljkgpxs** [TheOfficialFloW/VitaShell#48]
As we know, vitashell will notice user when they delete file, but the dialog covered the file list, user cant confirm what they have selected, but the dialog only display a message "Are you sure you want to delete this file?", I suggest the message should be "Are you sure you want to delete 'filename' file?". It will very usefull to warn user not delete file/folder by accident.

**Comment by WanderMax** [comment]
Nice idea
