### ISSUE TITLE
Getting error c2-12828-1

### ISSUE THREAD

**Issue by cursai** [TheOfficialFloW/VitaShell#483]
"an error has occurred in the following application c2-12828-1" occurs when launching vitashell. Cant access sd2vita etc.. have tried all fixes i.e older version, reinstalled henkaku 3.68. Attempted to reinstall firmware. Stuck with a brick???

**Comment by TheOfficialFloW** [comment]
Launch and press L. If nothing helps, format your ms.

**Comment by cursai** [comment]
Launch as in start up the vita whilst holding L or launch vitashell whilst holding L?

**Comment by MNKqwerty** [comment]
In start-up

**Comment by TheOfficialFloW** [comment]
add me on hangouts so we can find out the bug together: theofficialflow1996@gmail.com

**Comment by cursai** [comment]
Hi. any update on this or is it a lost cause?

**Comment by TheOfficialFloW** [comment]
I asked you to add me on hangouts such that we can find out the problem - but you didn't! So it's a lost cause.

**Comment by cursai** [comment]
I did. I sent you a message....Google hangouts I presume
