### ISSUE TITLE
Error 0xFFFFFFFF when attempting to install VPK

### ISSUE THREAD

**Issue by TaylorJBirch** [TheOfficialFloW/VitaShell#484]
Having an issue where the above error shows up and I cannot install VPKs or folders. **(OLED)** Vita is in unsafe mode, I allow extended permissions and vita is fresh from a h-encore install after a full system restore and memcard format. h-encore hack is successful with no issues being shown on the log in the app, and h-encore installs Vitashell fine, but vitashell cannot install any files. I should note this system is linked to a PSN account already due to h-encore setup, unsure about activation as it is not my vita, and is running **3.68**.

Please advise on this issue, as I have tried absolutely everything I can think of to fix it.

**Comment by diablosky** [comment]
It seems that VPKs will be broken when transferred by a USB connection in VitaShell 1.95. Try to use FTP mode instead.

**Comment by TaylorJBirch** [comment]
Thank you for the response, I'll try this later when I'm at home and update the thread with a result.

**Comment by perkel666** [comment]
Same here. I was using probably previous version and it worked fine but now when i formated my memory card, redone h-encore and installed latest vitashell it gives me same error like people said above.

0xFFFFFFFF

But it also random. As when i one time unchecked  unsafe homebrew

it threm up 0xFFFFFFE2 one time after installing to 50% vitahomebrewbrowser while everything else was stil 0xFFFFFFFF

**Comment by McPcholkin** [comment]
Test SHA-1 on 3 files (1MB, 50MB, 670MB), SD2VITA, FW 3.68:
Vitashell 1.94 USB - OK
Vitashell 1.94 FTP - OK
Vitashell 1.95 USB - OK
Vitashell 1.95 FTP - OK

**Comment by bashtee** [comment]
Same issue on Vita Slim, might be related to the memory card or some permission issues. I'm using the official 64GB one and couldn't install any vpks after installing h-encore on a fresh 3.65 update. I transfered the files via USB connection and kept getting error 0xFFFFFFFF. Transfering files via FTP as @diablosky suggested did the trick.

**Comment by TheOfficialFloW** [comment]
Hm weird stuff, are you guys sure v1.94 did not have this problem?

**Comment by bashtee** [comment]
The last version I had was 1.9 and I didn't have any issues there using the USB connection.

**Comment by TheOfficialFloW** [comment]
are you using any plugins like sd2vita?

**Comment by TheOfficialFloW** [comment]
I need more details such that I can reproduce that bug..

**Comment by UberGeek1984** [comment]
I had the same issue. I had an old un-hacked Vita in the cupboard that I decided to upgrade to 3.65 and install enso on. All I did was follow the instructions here: https://vita.hacks.guide/installing-h-encore.html. 

I had not yet installed my sd2vita, so the only plugins were as follows:
nonpdrm.skprx
download_enabler.suprx 
shellbat.suprx
pngshot.suprx
kuio.skprx
vsh.suprx

I copied vitahbbrowser.vpk (version 0.82) over to the vita via the USB connection. When I ran the vpk it failed. I copied the file over about 3 or 4 times, and on the fourth copy it finally executed successfully. 

The config.txt in ur0 was the following at the time the copies failed:

# For users plugins, you must refresh taiHEN from HENkaku Settings for
# changes to take place.
# For kernel plugins, you must reboot for changes to take place.

*KERNEL
ur0:tai/nonpdrm.skprx
ur0:tai/kuio.skprx

*main
ur0:tai/henkaku.suprx
ur0:tai/shellbat.suprx
ur0:tai/pngshot.suprx
ur0:tai/download_enabler.suprx

*NPXS10015
ur0:tai/henkaku.suprx

*NPXS10016
ur0:tai/henkaku.suprx

*!PSPEMUCFW
*ALL
ur0:tai/vsh.suprx

**Comment by TheOfficialFloW** [comment]
v1.96 has been released, see if it fixes the issue.

**Comment by StepS-** [comment]
It would of course be nice to eventually find a fix to both problems (corrupted memcards and VPKs). Reverting a fix that prevents potentially the _whole_ memcard from being corrupt just so that some VPK files could be transferred with "no problems" is simply not justifiable. This is just my opinion though.

Just got someone with a new memcard corruption after using vitashell's usb mode (1.97) on discord:
![image](https://user-images.githubusercontent.com/5569139/46248695-411c2e00-c425-11e8-87ec-a305d0798d3d.png)

**Comment by MorroTheCoder** [comment]
im havig n a simmilar issue it was error 0x8001001c when i had transfered the fie from usb than when i transfered it from ftp i goit this error 0xFFFFFFFF.
