### ISSUE TITLE
Support creating new files (from VitaShell itself)

### ISSUE THREAD

**Issue by xy2iii** [TheOfficialFloW/VitaShell#5]

**Comment by TheOfficialFloW** [comment]
Create a file what for?

**Comment by xy2iii** [comment]
Creating theme config file (theme.txt).

**Comment by TheOfficialFloW** [comment]
ah you mean writing a default theme.txt if it doesn't exist? Or an operation inside the context menu to do so?

**Comment by xy2iii** [comment]
The former; currently VitaShell doens't generate it.

**Comment by theorywrong** [comment]
With color of default/selected text for example ?

**Comment by TheOfficialFloW** [comment]
will do it
