### ISSUE TITLE
[PSVSD] VitaShell and h-encore corrupt after suspend mode

### ISSUE THREAD

**Issue by seewood** [TheOfficialFloW/VitaShell#501]
Hey there,
i installed the psvsd Adapter to my Vita 3G and it works very good. But when i enter the suspend mode / standby mode after 30mins or 1hour, the VitaShell and h-encore bubble become corrupt. I cant start it again. 

MolecularShell, Enso Bubble, Adrenaline and every PS Vita Game installed to the psvsd Adapter works fine! after the suspend Mode as well.

Only VitaShell and h-encore Bubble seems to be corrupt. 

And when i Shut down my Vita and Turn it Back on it Stucks on Enso Bootlogo - the only way i get my Vita back to start up is the following:

Start Vita with taiHen Plugins disabled (holding L on Startup) the Vita Boots from the original Sony Memory Card - everything works fine - then i restart my Vita over the Henkaku Settings or Vitashell and the psvsd starts up correctly!!

After an other Suspend Mode / Standby Mode - the same Issue. VitaShell and h-encore Bubble are corrupt.

Im using:
Vita 3G OLED with 3.65 Enso v1.1
StorageMgr 3.0
VitaShell 1.97
PSVSD Adapter

Did you know this Issue? Can i fix it by myself?

Best regards
seeWood

**Comment by TheOfficialFloW** [comment]
Not a VitaShell issue.

**Comment by seewood** [comment]
where should I then start looking in your opinion? StorageMgr Issue? The Games installed on the microSD and other Apps are working fine. only h-encore and vitashell
