### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by lh774567** [TheOfficialFloW/VitaShell#51]
i try make lastest vitashell but mingw show error : 

> arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o main.o main.c
In file included from main.c:36:0:
main.h:200:19: error: unknown type name 'ftpvita_client_info_t'
 void ftpvita_PROM(ftpvita_client_info_t *client);
                   ^
main.c: In function 'fileBrowserMenuCtrl':
main.c:1112:5: warning: implicit declaration of function 'ftpvita_ext_add_custom_command' [-Wimplicit-function-declaration]
     ftpvita_ext_add_custom_command("PROM", ftpvita_PROM);
     ^
main.c:1112:44: error: 'ftpvita_PROM' undeclared (first use in this function)
     ftpvita_ext_add_custom_command("PROM", ftpvita_PROM);
                                            ^
main.c:1112:44: note: each undeclared identifier is reported only once for each function it appears in
main.c: In function 'shellMain':
main.c:1255:3: warning: implicit declaration of function 'sceAppMgrReceiveSystemEvent' [-Wimplicit-function-declaration]
   sceAppMgrReceiveSystemEvent(&event);
   ^
main.c: At top level:
main.c:1442:19: error: unknown type name 'ftpvita_client_info_t'
 void ftpvita_PROM(ftpvita_client_info_t *client) {
                   ^
make: *** [main.o] Error 1

what i missing ?

**Comment by limyz** [comment]
Did you read https://github.com/TheOfficialFloW/VitaShell/blob/master/README.md?

In order to compile VitaShell you'll need
*vitasdk: https://github.com/vitasdk
*vita2dlib: https://github.com/xerpi/vita2dlib
*ftpvitalib https://github.com/xerpi/ftpvitalib

By the way, this is not a helpdesk. This place is for raising issues with VitaShell.

**Comment by lh774567** [comment]
oh, sorry and thank, i will close this issue.
