### ISSUE TITLE
[Request] Change USB Device Options to Select a Partition Instead

### ISSUE THREAD

**Issue by tiduscrying** [TheOfficialFloW/VitaShell#516]
Currently when you press select to change the USB mount point, it will give you the options to select from the various different kinds of storage you want to see. What I am proposing is that the setting be changed from it's current state to a partition selection instead, so instead of selecting "sd2vita" you would select "ux0" or "uma0" based on how things are currently configured. 

I don't know if it is a limitation within VitaShell to mount the ur0 partition over USB, but adding that would also be nice for individuals who have it configured to hold all of their taihen plugin and config files. 

This is purely an aesthetic change and doesn't offer much of a difference in overall function of VitaShell, but I thought I would request it either way.

**Comment by TheOfficialFloW** [comment]
ur0 cannot be mounted, since I have not found a way to remount it in order to avoid corruption. Also people rarely change partitions, thus the option in settings is enoughy
