### ISSUE TITLE
"This application requires extended permissions" no longer showing up?

### ISSUE THREAD

**Issue by KuromeSan** [TheOfficialFloW/VitaShell#519]
it seems in VitaShell 1.97 the check for "Unsafe Homebrew" is completely broken. i can install anything without a warning popping up.. 

was this removed? or is this a bug? i still see the reference to the text in english_us.txt so..

**Comment by TheOfficialFloW** [comment]
Maybe you have activated the option to disable it. Press START and see your settings.

**Comment by KuromeSan** [comment]
Oh you can disable it now. That's nice, also the "this app remounts partitions and could brick your device" thing also doesn't work (let me install VitaRW without it)
