### ISSUE TITLE
Issue copying files into decrypted folders not on ux0

### ISSUE THREAD

**Issue by bamhm182** [TheOfficialFloW/VitaShell#525]
I receive "Error 0x80010016" while I am attempting to install Q-Encore on my memory card mounted at uma0. When I navigate to uma0:user/00/savedata, highlight PCSG90096, and use "Open decrypted", the folder opens appears to be opened properly due to the lack of sce_pfs. However, if I try to paste system.dat here, I receive the aforementioned error code. If I repeat these steps while this same memory card is mounted to ux0:, it works without a problem.

**Comment by TheOfficialFloW** [comment]
Yeah you can only do that from ux0.
