### ISSUE TITLE
[REQUEST] Mount a network folder as a partition for psvita

### ISSUE THREAD

**Issue by animekai** [TheOfficialFloW/VitaShell#536]
Can i request a feature for vitashell please? I throught in a feature. To mount a shared folder from a groupwork network as a partition for psvita like netox0://
Imagine the possibilities, like play psp isos or eboots from network directly stored on the pc, or install ING vpk from pc shared folder.

Trespassing the límits of sd or usb memory, can it be factible?

**Comment by Princess-of-Sleeping** [comment]
Implementation is not easy
Even if the network mount can be implemented, the possibility of booting psp isos or eboots is extremely low.
