### ISSUE TITLE
usb connetion problem windows 7 - xp - lubuntu

### ISSUE THREAD

**Issue by j0s3ph19** [TheOfficialFloW/VitaShell#537]
heya! i have problem with usb mode
connection work i can delete and take item from psvita but i can't tranfer item in the memory!
-win 7 error: driver is dirty!  0x80071AC3
-win xp error: the drive is write protected!
- lubutu don't recognize it

vitashell 1.98 psvita 3.60 henkaku r11 (1**** series)

before has been worked fine...
what i have to do now? 
(ftp work perfectly)

**Comment by developer-sp** [comment]
I too cannot get usb connection in ubuntu 18.04 with fw 3.68(H-Encore), vita shell 1.98
![Captura de tela de 2019-04-18 11-11-09](https://user-images.githubusercontent.com/33873743/56367214-2647b600-61cb-11e9-9ee5-824b54e4d1cc.png)

**Comment by j0s3ph19** [comment]
i try to use an old version of vitashell, but i have the same problem, i don't know why that happend

is secure to use chkdsk? in some forum (old) i see this tip...
