### ISSUE TITLE
vitashell restart my psvita when i try to go to option

### ISSUE THREAD

**Issue by GoodManWeheba** [TheOfficialFloW/VitaShell#549]
when i try to enter Option with triangle button to refresh my  live area it restart my pstiva suddenly
idk what to do to refresh my live area plz help me 
FW 3.73 
vitashell v 2.00

**Comment by Robinsonnn1582** [comment]
This happened to me to, what i do to fix is everytime i want to refresh i change vitashell theme and restart the app, open the app again and its fix (but need to do this every time)

**Comment by ElricleNecro** [comment]
With your method, I was able to access the option menu, but when I want to refresh LiveArea, it will reboot (once it hit 25%). I am also on FW 3.73.

**Comment by TheOfficialFloW** [comment]
VitaShell has not been updated to 3.73 yet that‘s why
