### ISSUE TITLE
When i press triangle on ps tv it crashes on 3.73

### ISSUE THREAD

**Issue by ChromeCrusherr** [TheOfficialFloW/VitaShell#552]
I want to add some storage to my ps tv with a usb drive and now i can't.

**Comment by damnbabs** [comment]
Same problem any update ?

**Comment by damnbabs** [comment]
Cannot refresh the live area + nonpdrm game won't show up.

https://m.youtube.com/watch?v=K2cp76rSW68

**Comment by TheOfficialFloW** [comment]
Fixed in 3fd119d5341fafa2dbb065c71fbdadeb5d811cb3.
