### ISSUE TITLE
Year 12018 is displayed as 25073

### ISSUE THREAD

**Issue by KuromeSan** [TheOfficialFloW/VitaShell#555]
Hello there seems to be a problem with your date read function!

i set my year 10000 years into the future (with ksceRtcSetCurrent****Tick- adding 0x461040bcba00000ull; to current time) to match up with the Holocene Calendar-

as you can see calendar app CORRECTLY displays my time !

![My Great Capture Screenshot 2019-12-31 18-18-44](https://user-images.githubusercontent.com/39113159/71611253-55d50c00-2bfc-11ea-8650-29ab0feb5cd7.png)

However vitashell reports it as year 25073

![My Great Capture Screenshot 2019-12-31 18-29-20](https://user-images.githubusercontent.com/39113159/71611219-01ca2780-2bfc-11ea-98f3-93e48fe9486d.png)

**Comment by pthfdr-42** [comment]
Well, it is a UNIX problem, I guess.  
But you probably do not need that anyway since I do not think that Sony can make something that still works in 2038, let alone 12018.

**Comment by KuromeSan** [comment]
Vita does not use UNIX time!

**Comment by deadair3210** [comment]
Considering it's based on BSD, Im pretty sure it does actually

**Comment by cuevavirus** [comment]
Vita absolutely does not use UNIX time for this.

> librtc performs operations with 1 microsecond as the smallest unit of time. This value is called a Tick unit, and the time represented by SceRtcTick indicates the cumulative number of Ticks from 0001/01/01 00:00:00.

**Comment by deadair3210** [comment]
I stand corrected
