### ISSUE TITLE
Bricked only option #5 in Safe Mode

### ISSUE THREAD

**Issue by Abmarhon** [TheOfficialFloW/VitaShell#576]
Greetings 
I followed the process of installing CFW on PS vita but seems I bricked it up cuz of an error message
After running Henkaku to install 3.65 it showed up 
   1. factory FW is 3.61
   2. Current FW is 3.73
   3. Desired FW 3.65
I hit (X) so the system restart and start updating 3.65 but suddenly an error message pups up so system automatically keep restarting and trying to install the update for 3/4 times. And then I shut it down manually trying to fix/restore using safe mode menu but only one option could be chosen #5 " Update System Software".
So I tried sub-options of Update System Software: 
   - Update by connecting to a PC ; Result shows the latest ver. already installed.
   - Update from PS Vita Card ; Result shows cannot find update file

The only thing that I could access is only Safe mode but if I hit power button  for regular operation then PS logo lighting blue but screen is black .
Anyone experienced such issue please help it's brother bricked by me

**Comment by TheOfficialFloW** [comment]
Not bricked. Go to /r/vitahacks
