### ISSUE TITLE
Unable to update from 0.91

### ISSUE THREAD

**Issue by unclenospam** [TheOfficialFloW/VitaShell#58]
When opening VitaShell 0.91 for the first time, using a PCH-1104 model PS Vita, the shell asks to update by selecting either X for yes or O for no, but will not respond to input of any kind and the prompt remains open.

**Comment by limyz** [comment]
This is identified as a race condition with #56. We have yet to narrow the bug down.

**Comment by sjestus** [comment]
Thank limyz, I wasn't sure if it was the same bug or not since I can't even get to the point of moving/copying, etc

**Comment by sjestus** [comment]
Just in case this is at all different than #56, I uploaded a video showing exactly what happens: https://vid.me/7LDV

**Comment by limyz** [comment]
@sjestus It's very much similar to #56 as your time reflected changes. The UI has not crashed...its just freezing and not accepting any input. I am unsure if it is a 3G/WiFi PS Vita problem, but it definitely occurs on the regular PSV 1k and 2k sets. I will leave this issue open until the root problem is found and fixed.

**Comment by unclenospam** [comment]
@limyz here's an update as of this morning.

I downloaded and hosted a couple HENkaku releases. I tried both R4 (with VitaShell 0.86) and R6beta (and added VitaShell 0.95 manually)

I was able to successfully install HENkaku and VitaShell in both instances.

VitaShell opens and does not prompt for an update in either version.

In both iterations of VitaShell, it then only functions with the left analog stick to cycle up and down in the directories, and the input buttons do not function (like in the 2nd half of my vid).

The X and O buttons function everywhere else other than in VitaShell for some reason, but I'm wondering if I still don't have some sort of fault in the hardware itself.

**Comment by TheOfficialFloW** [comment]
It seems like this is a hardware failure. As I can see in the video, when the dialog was opened, you couldn't press any buttons, that's because the dialog blocked all buttons in the menu and would only react to X and O. At your second run where airplane mode is enabled, it didn't open the dialog, so buttons shoudln't be blocked. However you could only use the left analog stick which means it's a hardware failure, because both digital pad and analog stick are read in the same condition: https://github.com/TheOfficialFloW/VitaShell/blob/master/main.c#L1169

**Comment by unclenospam** [comment]
The buttons work fine in the livearea.

**Comment by TheOfficialFloW** [comment]
https://drive.google.com/file/d/0B8d0Wy4mDFrGZWVlUjJtVGhXUjg/view?usp=sharing

Please try this built and try every button, it should make a log file at ux0:vitashell_log.txt. send the file to me

**Comment by unclenospam** [comment]
Installed the build you sent. I've tried every button.  If I can't enter the ux0 directory on the Vita, how do I send the log back to you?

**Comment by TheOfficialFloW** [comment]
Use this: https://github.com/xerpi/libftpvita/releases

**Comment by limyz** [comment]
@TheOfficialFloW @Bigboot mentioned https://github.com/TheOfficialFloW/VitaShell/commit/54d0b657db961b081fd2168e936b8cd1c46b8ce8 - in case you overlooked. Ignore if not relevant.

**Comment by unclenospam** [comment]
the only entry point for installing a vpk without a shell that I know of is using HENkaku and altering the pkg folder. I've put the libftpvita vpk contents into the pkg folder, but I get errors when trying to install it from my Go server.

**Comment by TheOfficialFloW** [comment]
Ok, an other test: https://drive.google.com/file/d/0B8d0Wy4mDFrGSDAtbEFLb0ZSWnc/view?usp=sharing

This will print three different buttons values at the VitaShell title. Tell me if they react to all buttons

**Comment by unclenospam** [comment]
The only time the values change are when I move either analog stick.

With all the other buttons, the values stay at 0x00000000

**Comment by TheOfficialFloW** [comment]
This is the weirdest bug I've ever had to handle. I don't know where the bug lies, as it doesn't seem to be a VitaShell bug. Try this : https://github.com/SMOKE5/VitaTester/releases

**Comment by unclenospam** [comment]
I was able to get:

https://drive.google.com/open?id=0B8x5IStiJjuYUVhKdTJxZ1RsVGM

https://drive.google.com/open?id=0B8x5IStiJjuYdnFaLUxmZlJLUHc

**Comment by unclenospam** [comment]
I was able to install FTPVita (since I was able to dump those)

There's the command "Press [ ] to exit" at the top. Pressing square while in this app doesn't work either.

**Comment by unclenospam** [comment]
I'm going to try and reinstall the first build you sent me that will create the log, then see if I can FTP again and dump that too.

**Comment by unclenospam** [comment]
I was able to FTP back in after running the build you sent, but it didn't create a log in ux0.

Is there any other file I can grab that might be helpful while I'm FTP'd in?

**Comment by TheOfficialFloW** [comment]
As described at https://github.com/TheOfficialFloW/VitaShell/issues/58#issuecomment-246459363, the issue is now clear. The bug is neither related to the network update feature nor to VitaShell itself. It is a hardware/software/HENkaku/unknown failure, because it does not work with FTPvita either.
Also debug info from VitaShell are showing that your buttons are not recognized.
Therefore, closed.

**Comment by unclenospam** [comment]
Yeah, that definitely seems like the case. Thanks for your help.

**Comment by BigBoot** [comment]
@unclenospam 
xyz asked, if you could provide a video of it working in a game

**Comment by unclenospam** [comment]
@BigFoot I'll get that uploaded once I'm back in my office. Thanks for the heads up.

**Comment by unclenospam** [comment]
@BigBoot I'm just going to skip the video upload. The buttons do not work within a game. Looks like this is a confirmed bad PS Vita. Sucks, cause I just got it.

Thanks again to everyone who helped troubleshoot with me.

**Comment by TheOfficialFloW** [comment]
Please take a video where you show us the using of the buttons in livearea then.

**Comment by BigBoot** [comment]
He already did https://github.com/TheOfficialFloW/VitaShell/issues/58#issuecomment-246437966

**Comment by unclenospam** [comment]
Yeah, the link is up a little ways in this thread. https://vid.me/smDg

The buttons work fine in livearea, but stop functioning in game.

I'm working on replacing the Vita. Again, thanks for the help.

**Comment by limyz** [comment]
Can you ensure the shoulder buttons are not stuck?

**Comment by unclenospam** [comment]
From what I can tell in the livearea, the left shoulder button seems to work to switch between software. The right shoulder button will not allow me to switch back. Maybe it's something going on with the right shoulder?

**Comment by limyz** [comment]
Probably damaged. Work on replacing the Vita if not you will need to replace that.

**Comment by unclenospam** [comment]
I actually just got a return label to ship it back a few seconds before you just replied. I should be getting a new Vita in a couple days.

**Comment by limyz** [comment]
Awesome. Hope that helped...do keep us posted.

**Comment by unclenospam** [comment]
Thanks! You all are awesome!

**Comment by unclenospam** [comment]
Got my replacement Vita today. Everything installed and is working great. Thanks again to everyone, you all are amazing. Keep it up!
