### ISSUE TITLE
ERROR 0x80431084

### ISSUE THREAD

**Issue by kevin061397** [TheOfficialFloW/VitaShell#589]
I TRIED TO DOWNGRADE 3.73 TO 3.68 AND I INSTALLED H-ENCORE HENKAKU AND I TRIED INSTALL VITASHELL BUT IT SAYS FAILD TO DOWNLOAD 0x80431084 how can I fix it? I don't have any VITASHELL(because I formated memory card)

**Comment by Masamune3210** [comment]
go ask for help on the forums or in Discord, this isn't the place for asking for help

**Comment by kevin061397** [comment]
ok thank you
