### ISSUE TITLE
Refreshing the LiveArea doesn't add a game however it shows installed in PKGj

### ISSUE THREAD

**Issue by MasonT8198** [TheOfficialFloW/VitaShell#608]
Interesting bug it seems that this can happen frequently, the livearea doesn't refresh, however in pkgj the game shows as installed, launching from eboot.bin could possibly fix this

**Comment by Masamune3210** [comment]
what is the titleid of the game in question, I have never had this happen on mine. What prx do you have loaded, and what is your storage medium and setup

**Comment by MasonT8198** [comment]
I have had it in quite a few games I've installed, however one of them is PCSE00710. I have an SD2VITA as my storage medium on one of my vita units, along with setups involving internal memory units, my 1000 and 2000 have this issue and my vita tv as well, and games seem to be a hit or miss on all of them. PKGj still installs games fine, however you probably would understand why I would rather just transfer them via usb for speed. When Transferred PKGj sees them as installed however vitashell still doesn't want to refresh the live area, and also, no I haven't used autoplugin, I install all my plugins manually

Before creating this issue I did do further research seeing other people, including the person I was in a discord call with testing some networking items on the vita.

**Comment by MasonT8198** [comment]
> what is the titleid of the game in question, I have never had this happen on mine. What prx do you have loaded, and what is your storage medium and setup

ReF00d, NoNpDRM, and the vita snapshot prx

**Comment by Masamune3210** [comment]
have you tried updating the database first? or deleting the app.db and letting LiveArea reset itself?

**Comment by MasonT8198** [comment]
> have you tried updating the database first? or deleting the app.db and letting LiveArea reset itself?

No I can't say I have, I will try this in a few minutes, where is the app.db located?

**Comment by Masamune3210** [comment]
Probably should try refreshing the livearea through safe mode first, both do similar things, just the safe mode one is more officially supported

**Comment by philippense** [comment]
> Interesting bug it seems that this can happen frequently, the livearea doesn't refresh, however in pkgj the game shows as installed, launching from eboot.bin could possibly fix this

**how i do show games pkgj highlighted installed after that update data base psvita?**:/

![2022-10-21-122547](https://user-images.githubusercontent.com/52587005/197221489-8e33cbab-e162-4db7-9fb7-34f299904967.jpg)

**Comment by Masamune3210** [comment]
I'm sorry but I don't understand what you are trying to ask

**Comment by philippense** [comment]
i did solver itself this isssues ,thank's boond great PSVita enjoy me a lot.
