### ISSUE TITLE
Allow user to sort files by file name, size or type

### ISSUE THREAD

**Issue by c62624** [TheOfficialFloW/VitaShell#63]
These past few days I've been doing a lot of file ripping from my games to reduce memory size. I find myself using Filezilla more than VitaShell because I can sort files by size and type. Would be a nice feature to have in a file manager.

**Comment by TheOfficialFloW** [comment]
Added in https://github.com/TheOfficialFloW/VitaShell/commit/c44fc7df45f0d6f130dd28d3c916848a50646f9a
