### ISSUE TITLE
Compile error on master branch

### ISSUE THREAD

**Issue by ghost** [TheOfficialFloW/VitaShell#64]
Getting this error when trying to compile the latest master branch

xx@xx:~/Documents/VitaShell$ make clean && make
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o main.o main.c
main.c: In function 'main':
main.c:1550:2: warning: implicit declaration of function 'vitaAudioInit' [-Wimplicit-function-declaration]
  vitaAudioInit(0x40);
  ^
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o init.o init.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o io_process.o io_process.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o package_installer.o package_installer.c
package_installer.c: In function 'loadScePaf':
package_installer.c:39:2: warning: implicit declaration of function 'sceSysmoduleLoadModuleInternalWithArg' [-Wimplicit-function-declaration]
  sceSysmoduleLoadModuleInternalWithArg(0x80000008, sizeof(scepaf_argp), scepaf_argp, ptr);
  ^
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o network_update.o network_update.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o context_menu.o context_menu.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o archive.o archive.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o photo.o photo.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o audioplayer.o audioplayer.c
In file included from audioplayer.c:28:0:
audio/mp3player.h:18:17: fatal error: mad.h: No such file or directory
#include <*mad.h>
^
compilation terminated.
<builtin>: recipe for target 'audioplayer.o' failed
make: *** [audioplayer.o] Error 1

**Comment by TheOfficialFloW** [comment]
Will fix it. Write #include "../libmad/mad.h" in mp3player.h

**Comment by rexzc** [comment]
More errors, had to correct 2 files using that include line (one mp3player.h, other one is mp3xing.h)

xx@xx:~/Documents/VitaShell$ make clean && make
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o main.o main.c
main.c: In function 'main':
main.c:1550:2: warning: implicit declaration of function 'vitaAudioInit' [-Wimplicit-function-declaration]
  vitaAudioInit(0x40);
  ^
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o init.o init.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o io_process.o io_process.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o package_installer.o package_installer.c
package_installer.c: In function 'loadScePaf':
package_installer.c:39:2: warning: implicit declaration of function 'sceSysmoduleLoadModuleInternalWithArg' [-Wimplicit-function-declaration]
  sceSysmoduleLoadModuleInternalWithArg(0x80000008, sizeof(scepaf_argp), scepaf_argp, ptr);
  ^
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o network_update.o network_update.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o context_menu.o context_menu.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o archive.o archive.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o photo.o photo.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o audioplayer.o audioplayer.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o file.o file.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o text.o text.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o hex.o hex.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o sfo.o sfo.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o uncommon_dialog.o uncommon_dialog.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o message_dialog.o message_dialog.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o ime_dialog.o ime_dialog.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o config.o config.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o theme.o theme.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o language.o language.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o utils.o utils.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o sha1.o sha1.c
sha1.c: In function 'sha1_final':
sha1.c:124:3: warning: implicit declaration of function 'memset' [-Wimplicit-function-declaration]
   memset(ctx->data, 0, 56);
   ^
sha1.c:124:3: warning: incompatible implicit declaration of built-in function 'memset'
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o minizip/unzip.o minizip/unzip.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o minizip/ioapi.o minizip/ioapi.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o bm.o bm.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o audio/vita_audio.o audio/vita_audio.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o audio/player.o audio/player.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o audio/id3.o audio/id3.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o audio/mp3player.o audio/mp3player.c
In file included from audio/mp3player.c:27:0:
audio/mp3xing.h:21:17: fatal error: mad.h: No such file or directory
 #include <*mad.h>
                 ^
compilation terminated.
<builtin>: recipe for target 'audio/mp3player.o' failed
make: *** [audio/mp3player.o] Error 1
xx@xx:~/Documents/VitaShell$ cd audio
xx@xx:~/Documents/VitaShell/audio$ nano mp3xing.h
xx@xx:~/Documents/VitaShell/audio$ cd ..
xx@xx:~/Documents/VitaShell$ make clean && make
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o main.o main.c
main.c: In function 'main':
main.c:1550:2: warning: implicit declaration of function 'vitaAudioInit' [-Wimplicit-function-declaration]
  vitaAudioInit(0x40);
  ^
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o init.o init.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o io_process.o io_process.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o package_installer.o package_installer.c
package_installer.c: In function 'loadScePaf':
package_installer.c:39:2: warning: implicit declaration of function 'sceSysmoduleLoadModuleInternalWithArg' [-Wimplicit-function-declaration]
  sceSysmoduleLoadModuleInternalWithArg(0x80000008, sizeof(scepaf_argp), scepaf_argp, ptr);
  ^
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o network_update.o network_update.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o context_menu.o context_menu.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o archive.o archive.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o photo.o photo.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o audioplayer.o audioplayer.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o file.o file.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o text.o text.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o hex.o hex.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o sfo.o sfo.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o uncommon_dialog.o uncommon_dialog.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o message_dialog.o message_dialog.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o ime_dialog.o ime_dialog.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o config.o config.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o theme.o theme.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o language.o language.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o utils.o utils.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o sha1.o sha1.c
sha1.c: In function 'sha1_final':
sha1.c:124:3: warning: implicit declaration of function 'memset' [-Wimplicit-function-declaration]
   memset(ctx->data, 0, 56);
   ^
sha1.c:124:3: warning: incompatible implicit declaration of built-in function 'memset'
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o minizip/unzip.o minizip/unzip.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o minizip/ioapi.o minizip/ioapi.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o bm.o bm.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o audio/vita_audio.o audio/vita_audio.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o audio/player.o audio/player.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o audio/id3.o audio/id3.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o audio/mp3player.o audio/mp3player.c
audio/mp3player.c: In function 'MP3_Init':
audio/mp3player.c:290:5: warning: implicit declaration of function 'vitaAudioSetChannelCallback' [-Wimplicit-function-declaration]
     vitaAudioSetChannelCallback(myChannel, MP3Callback,0);
     ^
audio/mp3player.c: In function 'MP3_Load':
audio/mp3player.c:578:5: warning: implicit declaration of function 'vitaAudioSetFrequency' [-Wimplicit-function-declaration]
     if (vitaAudioSetFrequency(myChannel, MP3_info.hz) < 0)
     ^
audio/mp3player.c: In function 'MP3_Stop':
audio/mp3player.c:618:9: warning: implicit declaration of function 'sceKernelDelayThread' [-Wimplicit-function-declaration]
         sceKernelDelayThread(100000);
         ^
In file included from audio/mp3xing.h:21:0,
                 from audio/mp3player.c:27:
audio/mp3player.c: In function 'decode':
audio/../libmad/mad.h:215:5: error: impossible constraint in 'asm'
     asm ("imull %3"  \
     ^
audio/../libmad/mad.h:500:8: note: in expansion of macro 'MAD_F_MLX'
        MAD_F_MLX(__hi, __lo, (x), (y));  \
        ^
audio/mp3player.c:113:4: note: in expansion of macro 'mad_f_mul'
    mad_f_mul(Frame->sbsample[Channel][Sample][SubBand], Filter[SubBand]);
    ^
audio/../libmad/mad.h:215:5: error: impossible constraint in 'asm'
     asm ("imull %3"  \
     ^
audio/../libmad/mad.h:500:8: note: in expansion of macro 'MAD_F_MLX'
        MAD_F_MLX(__hi, __lo, (x), (y));  \
        ^
audio/mp3player.c:117:42: note: in expansion of macro 'mad_f_mul'
    Frame->sbsample[0][Sample][SubBand] = mad_f_mul(Frame->sbsample[0][Sample][SubBand], Filter[SubBand]);
                                          ^
<builtin>: recipe for target 'audio/mp3player.o' failed
make: *** [audio/mp3player.o] Error 1

**Comment by TheOfficialFloW** [comment]
Should be fixed now

**Comment by reszx** [comment]
xx@xx:~/Documents/VitaShell$ make clean && make
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o main.o main.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o init.o init.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o io_process.o io_process.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o package_installer.o package_installer.c
package_installer.c: In function 'loadScePaf':
package_installer.c:39:2: warning: implicit declaration of function 'sceSysmoduleLoadModuleInternalWithArg' [-Wimplicit-function-declaration]
  sceSysmoduleLoadModuleInternalWithArg(0x80000008, sizeof(scepaf_argp), scepaf_argp, ptr);
  ^
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o network_update.o network_update.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o context_menu.o context_menu.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o archive.o archive.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o photo.o photo.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o audioplayer.o audioplayer.c
audioplayer.c: In function 'audioPlayer':
audioplayer.c:98:4: warning: implicit declaration of function 'scePowerRequestDisplayOff' [-Wimplicit-function-declaration]
    scePowerRequestDisplayOff();
    ^
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o file.o file.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o text.o text.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o hex.o hex.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o sfo.o sfo.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o uncommon_dialog.o uncommon_dialog.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o message_dialog.o message_dialog.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o ime_dialog.o ime_dialog.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o config.o config.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o theme.o theme.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o language.o language.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o utils.o utils.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o sha1.o sha1.c
sha1.c: In function 'sha1_final':
sha1.c:124:3: warning: implicit declaration of function 'memset' [-Wimplicit-function-declaration]
   memset(ctx->data, 0, 56);
   ^
sha1.c:124:3: warning: incompatible implicit declaration of built-in function 'memset'
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o minizip/unzip.o minizip/unzip.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o minizip/ioapi.o minizip/ioapi.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o bm.o bm.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o audio/vita_audio.o audio/vita_audio.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o audio/player.o audio/player.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o audio/id3.o audio/id3.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o audio/oggplayer.o audio/oggplayer.c
audio/oggplayer.c:24:44: fatal error: vorbis/codec.h: No such file or directory
 #include <vorbis/codec.h>      //ogg-vorbis
                                            ^
compilation terminated.
<builtin>: recipe for target 'audio/oggplayer.o' failed
make: *** [audio/oggplayer.o] Error 1

-_-

**Comment by TheOfficialFloW** [comment]
That's an other error now. Do you even understand the error? You need to have libogg...refer to the readme.

**Comment by reszx** [comment]
Well didn't notice that. now it works.. But srsly you should have putted the deps at the top of the README, cause it takes way too long to scroll down and not everyone sees it

**Comment by limyz** [comment]
Unfortunately not everyone is a developer. Leaving it to the top will make no sense to the typical user. Since the issue has been resolved, I will now close this issue.
