### ISSUE TITLE
[Improvement] Unzip the zip files

### ISSUE THREAD

**Issue by ck201** [TheOfficialFloW/VitaShell#65]
Would you add **unzip the .zip files** function for VitaShell ?
 It will reduce the time of  transporting a great many small files from PC to Vita. For example, Dead or Alive Xtreme 3, which have about 10 thousand files. it need 5 more hours to transport the all files to Vita via FTP or CMA. I tried to pack the game folder to .zip and rename to .vpk ,transport it to Vita within about 10 minutes, then install it with vitashell, but failed with an error 0xFFFFE when progress at 99% even through there were 5GB free space. If Vitshell can unzip the .zip to folder,then I can use MaiDump tool to install the game from folder in seconds, It will save very much time. Thank you.

**Comment by TheOfficialFloW** [comment]
The 0xFFFFFFFE error occurs because your game is missing param.sfo. VitaShell can of course unzip .zip files, how would it be able to install .vpks then which are nothing than .zip files?

**Comment by limyz** [comment]
Please use the Mark All and Copy functionality.
