### ISSUE TITLE
Compatibility with screen touch

### ISSUE THREAD

**Issue by Dragoon1010** [TheOfficialFloW/VitaShell#66]
Add compatibility for touch screen possible ?

**Comment by limyz** [comment]
It was previously worked on by someone else, then dropped due to non-functional code. Refer to https://github.com/TheOfficialFloW/VitaShell/pull/44. Nevertheless, its just an extra feature that may or may not be implemented.

If time allows, I may implement those for dialog boxes only.

**Comment by TheOfficialFloW** [comment]
Having touch doesn't fit the design of VitaShell. If I implement it I have to make everything bigger, which is not possible with the current pgf font (font looks bad then).

**Comment by limyz** [comment]
See explanation above. As touch functionalities do not fit the design of VitaShell, this issue will be closed. This issue can also be revisited in the future should we wish to implement it.

**Comment by Dragoon1010** [comment]
The touch function can be used for the rapid slide to bottom/top, no need to make bigger. 
It can also be used to zoom the image, and used for switch to back folder with swipe at left of the screen.

**Comment by TheOfficialFloW** [comment]
Hm, I will rethink about minimal touch support

**Comment by Dragoon1010** [comment]
Ok thx ^^ !

**Comment by thhoang99** [comment]
well, it's me dropped that pull request, but i still not  give up, i started this in version 0.4 so many old code i must keep to can run, i modified ui for fit with touch and making nofication, this is sample:
![2016-09-14-211907](https://cloud.githubusercontent.com/assets/20391040/18516113/f5c3e37a-7ac1-11e6-82fa-1f72b50d88b2.jpg)
![2016-09-14-213447](https://cloud.githubusercontent.com/assets/20391040/18516448/38fcdcb8-7ac3-11e6-8c3a-7ea4de6dfac6.jpg)
 Many dirty code, I will try clean code and add lastest code of 1.1 (now my base version is 0.91), then will pull request again.

**Comment by TheOfficialFloW** [comment]
This actually looks awesome

**Comment by limyz** [comment]
@TheOfficialFloW Yes it is.
@thhoang99 Looking at your commits, I suggest refactoring your code into touch.c/touch.h to make things cleaner.

**Comment by TheOfficialFloW** [comment]
@thhoang99 Can you send me the built so I can experience this UI?

**Comment by thhoang99** [comment]
ok, but maybe it still have error.
[VitaShell.zip](https://github.com/TheOfficialFloW/VitaShell/files/472344/VitaShell.zip) (rename to vpk)

**Comment by TheOfficialFloW** [comment]
Please work on a two-option solution where we can switch between the original UI and yours. I have asked my followers on twitter and they prefer the original one, so I would not replace it.

**Comment by limyz** [comment]
@thhoang99 Just tried it, feels awesome. Dialog boxes and scrolling features are are touch implemented.

**Comment by thhoang99** [comment]
oh, i intent will trying make switch between 2 ui to can clean code easier. ok, when it done i will contact with you.

**Comment by limyz** [comment]
I am assigned to work on this part of VitaShell. At least I do have a skeleton code to work and improve on.

**Comment by Dragoon1010** [comment]
very nice ! but can switch between the original UI and yours is good choice ;).

**Comment by TheOfficialFloW** [comment]
Peoples reactions are that the icons are quite too large, otherwise they like it

**Comment by Dragoon1010** [comment]
yes it's too large, and the slide is not smooth. But it's good work !

**Comment by TheOfficialFloW** [comment]
@thhoang99 how is the development going? You don't need to work on it until it's fully done, be free to push commits so we can see the step by step progression.

**Comment by thhoang99** [comment]
Ah, sorry i busy in my work, I combined 2 UI but some function not work correctly, i fixing and review my work, when done i will pull requests immediately.

**Comment by limyz** [comment]
No worries. Just hint me over at your commit and I would be more than glad to help to test out functionalities.

**Comment by limyz** [comment]
Refer to #114.
