### ISSUE TITLE
VPK installation does not terminate if cancel is pressed before full permissions is granted

### ISSUE THREAD

**Issue by limyz** [TheOfficialFloW/VitaShell#68]
Refer to https://github.com/TheOfficialFloW/VitaShell/blob/master/package_installer.c#L364. Happens when trying to install with large or huge vpk sizes.

**Comment by TheOfficialFloW** [comment]
The permission warning dialog will pop up even after you have cancelled if I have understood correctly?

**Comment by limyz** [comment]
Yep yep

**Comment by TheOfficialFloW** [comment]
I have fixed it in v1.1. Forgot to mention it in the changelog though
