### ISSUE TITLE
Add GUI theme switcher

### ISSUE THREAD

**Issue by xy2iii** [TheOfficialFloW/VitaShell#7]
Sorry if this is a big request.

For swapping themes via VitaShell itself. Name and author could be read from the theme folder (which I enforce in the theme repo, via theme-name^author.) Maybe with the ability to display preview (reading preview.jpg from the theme folder, or previewX.jpg if there are multiple previews and cycling them.)

**Comment by Cologler** [comment]
This is what you looking for:
[VitaShell Theme Manager](http://wololo.net/talk/viewtopic.php?f=116&t=46936)

**Comment by theorywrong** [comment]
Working on his soon :+1:

**Comment by coderobe** [comment]
This is already included in the settings branch

**Comment by TheOfficialFloW** [comment]
https://github.com/TheOfficialFloW/VitaShell/commit/49e6b9b8988ebf1a2fd2de0474ae1c5a64167757
