### ISSUE TITLE
got issue compiling latest sources, since audioplayer addition

### ISSUE THREAD

**Issue by littlebalup** [TheOfficialFloW/VitaShell#73]
I'm compiling using PSDK3v3 updated with latest vita-headers, libvita2d, libftpvita and adding EasyRPG libraries as requested.
I have no idea what's wrong.

I got:

> audioplayer.o: In function `audioPlayer':
> audioplayer.c:(.text+0x976): undefined reference to `scePowerRequestDisplayOff'
> collect2.exe: error: ld returned 1 exit status
> make: *** [VitaShell.elf] Error 1

**Comment by TheOfficialFloW** [comment]
You aren't using the latest vita-headers then: https://github.com/vitasdk/vita-headers/blob/master/db.json#L3823

**Comment by littlebalup** [comment]
Ok. I got latest win32 toolchain build and seems to work now.
