### ISSUE TITLE
duplicate Installation

### ISSUE THREAD

**Issue by Dimkar3000** [TheOfficialFloW/VitaShell#74]
Ok after version 0.91 molecule can update itself but instead it installs Vitashell. As a result I have two version of the app. if I delete molecule, henkaku reinstalls it and if I delete Vitashell every update reinstall it. 

Possible fixes: 
Make Vitashell the default app that comes with henkaku and remove support for molecule or
Fix the updater so it update molecule and it doesn't install vitashell.

Now I know they are one and the same app but you can update the updater so it understand which of the 2 is installed and it doesn't install the other.

**Comment by limyz** [comment]
Fixed in v1.2.
Refer to https://github.com/TheOfficialFloW/VitaShell/commit/ba83860ffd34c275f4b8542a17fb4b3c96540997.
