### ISSUE TITLE
FTP disconnects file transfer(s) when going to sleep

### ISSUE THREAD

**Issue by Dimkar3000** [TheOfficialFloW/VitaShell#75]
If you transfer a large file and the screen dim the proccess will either freeze or get slower. If the screen closes the proccess will most likely stop resulting to partialy transfered files.

*Workarounds* : if the proccess get slow but it hasn't stop you can fix it by navigating between folders

*Fix Recommendations* ; To prevemt the partialy transfered files you can implement a temp functionality. When the files are tranfsered you can at first put the in a temp folder and move them to the right dir only if the transfer is successful.

Now for the freezing problem I think PSVita free up resources when the app becomes idle( screen dims). You can probably fix it by forcing the VIta stay focus when the ftp is active.

**Comment by limyz** [comment]
@Dimkar3000 Can you describe slow? Even if VitaShell is suspended (Pressing the PS button), FTP transfers will resume normally. If not, move to a less noisy environment or closer to the access point.

**Comment by Dimkar3000** [comment]
@limyz  Yes, let's say it starts the tranfer at 1.5Mb/s, if I let it go idle it will slow down to about 50-100Kb/s. I found it also happening when I transfer multiple files that take more than 5 minutes to complete.

**Comment by limyz** [comment]
@Dimkar3000 Other factors on the network also comes into play. Meanwhile, use https://github.com/TheOfficialFloW/VitaShell/issues/21#issuecomment-244129252. This will prevent the Vita from sleeping during transfer when the image is loaded.

As for your fix recommendations, it would seem awkward to perform a copy operation on the device twice. https://github.com/xerpi/ftpvitalib handles all FTP protocols on VitaShell, and supports resume should the process is interrupted. There are reports of failing memory cards and this will not be feasible for implementation.

**Comment by Dimkar3000** [comment]
@limyz  Then can't you prevent the device from going idle? That will probably fix it since it happens when the power saving option kicks in( screen dims). Another workaround I found was to turn power saving options to 30mins. That gave me more time to touch the screem and reset the idle time

**Comment by limyz** [comment]
That would seem so. This was supposedly to fix burn-ins for OLED Vitas but introduces this problem instead.

**Comment by TheOfficialFloW** [comment]
Nobody else has experienced this bug, I'll close this issue

**Comment by EmuAGR** [comment]
I'm experiencing this issue, too.
