### ISSUE TITLE
[Feature Request] Media Access from apps

### ISSUE THREAD

**Issue by Dimkar3000** [TheOfficialFloW/VitaShell#76]
Fristly: I hate the content manager.

Now I tried to send music to my vita via ftp and it worked :smirk: . Vita Shell was able to play it  but it wasn't available in the music app( the same think happened with photos. I'd like Vita Shell to make the media files available to their respective apps, maybe it will only be an option if you have selected a song or a photo.

**Comment by TheOfficialFloW** [comment]
Added in https://github.com/TheOfficialFloW/VitaShell/commit/371bcdd5689c7330f1d6fb1f53967f00a87d4c95
