### ISSUE TITLE
Display option

### ISSUE THREAD

**Issue by Mored1984** [TheOfficialFloW/VitaShell#78]
- Stay live or turn off

- Make option like Vitamin v2.0 "Hold L to turn off the display" also if I didn't turn the display off it will remain on (when display switched off the data transfer be cancel {FTP client Mode}{install VPK file}).

**Comment by Dimkar3000** [comment]
This feature will solve the issue I posted earlier. #75

**Comment by limyz** [comment]
Duplicate of #75.
