### ISSUE TITLE
Adding percentage % to FTP and battery to VitaSell (request).

### ISSUE THREAD

**Issue by Fadi5555** [TheOfficialFloW/VitaShell#79]
Hi there can you please add percentage of battery life and FTP while we transferring files please?

**Comment by limyz** [comment]
There are two issues raised here.
1. Battery Percentage
* The battery indicator on the top right corner is already represented as a float value. It should be pretty helpful enough. We probably can add a percentage if more users can request for it.
2. FTP Percentage
* Using Filezilla or WinSCP will indicate percentages during file transfer. Implementation on the server (PS Vita) is deemed unnecessary.

**Comment by littlebalup** [comment]
Added battery percentage into SYS_INFO dialog: https://github.com/TheOfficialFloW/VitaShell/pull/80

**Comment by Fadi5555** [comment]
@littlebalup thank you for adding this. We really appreciate so much.
