### ISSUE TITLE
Can't open png files from Playstore games

### ISSUE THREAD

**Issue by Dakor91** [TheOfficialFloW/VitaShell#82]
When trying to open the icon0.png from games which I installed from the PS Store, i get "Error 0xFFFFFFFFFF."

This seems to be an issue with the png files, because i can't open them on windows either (maybe a missing png header?)

The icon0.png from other hombrew apps work without any issue. It would be awesome if vitashell would be able to patch the non-working png files so that they can be opened :)

**Comment by TheOfficialFloW** [comment]
they are pfs encrypted

**Comment by partyp770** [comment]
Can you add an error message that points this out? I spent MONTHS wondering why icons wouldn't open.
