### ISSUE TITLE
More context menu have a bug with control

### ISSUE THREAD

**Issue by theorywrong** [TheOfficialFloW/VitaShell#86]
All is in the title, try "More" context menu by yourself ^^
I'm working on theme manager, i doesn't have the time to fix this

**Comment by littlebalup** [comment]
What do you mean? Right D-pad that start the command?

**Comment by theorywrong** [comment]
No, the rel pos doesn't go to the center

Le 20 sept. 2016 22:45, "littlebalup" <notifications@github.com> a écrit :

What do you mean? Right D-pad that start the command?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/TheOfficialFloW/VitaShell/issues/86#issuecomment-248428746>,
or mute the thread

**Comment by TheOfficialFloW** [comment]
You say 'All is in the title', but it's in fact still unclear. Also, what do you mean with 'rel pos doesn't go to the center'?

**Comment by theorywrong** [comment]
Okay is not a bug, a theme use the same color for "not usable" and "usable" entry
