### ISSUE TITLE
Add custom font ability

### ISSUE THREAD

**Issue by littlebalup** [TheOfficialFloW/VitaShell#87]
I quicly tested 
`vita2d_pgf *vita2d_load_custom_pgf(const char *path);`

I'll do my best but I'm not sure to find time to fully implement it as theme option. Feel free to do it if you wish.

example with crappy Zrnic.ttf converted to pgf:
![2016-09-20-231613](https://cloud.githubusercontent.com/assets/6732619/18689491/b92d54e2-7f89-11e6-88b3-7030893e0cc8.jpg)

Note: I don't know pgf files. And I don't know how to add the buttons symbols (circle, square, triangle, cross...) to custom pgf font files, matching actual used UTF-8 encoded bytes (to not brake default font)...

**Comment by littlebalup** [comment]
Code merged for test purpose (see prior post) :

The pgf font file, named "font.pgf", must be located into the theme folder.
else default font is loaded.
The pgf files generated with ttf2pgf (even with good unicode font) will not include/display special characters (buttons symbols, arrows...).
I'm realy not font specialist and not familiar at all with pgf file format.

Issue left open to discuss about it.

**Comment by soywiz** [comment]
If it is in the same format than the original PSP, this is the only thing that I remember (the URL, and that they were bitmap fonts :P):
https://github.com/soywiz/cspspemu/blob/master/Tests/Tests.CSPspEmu.Hle/Formats/Font/PGFTest.cs
https://github.com/soywiz/cspspemu/blob/master/Hle/CSPspEmu.Hle.Formats/Font/PGF.cs

Sorry I don't really know about the mapping of special characters like those.

**Comment by limyz** [comment]
Tools to process the PGF font. A quick Google brought me some results:
https://github.com/tpunix/pgftool
http://bbq.xyz.is/PGF_font_format

**Comment by littlebalup** [comment]
So, I learn a bit and found a maybe cappy but working and easy process to make custom PGF file that include the special characters.

I probably teach you nothing here but I think I understood that all the base font is included into the jpn0.pgf file, included special geometric characters. So the default system font characters are the characters included in the jpn0.pgf plus the minimal characters of the font matching your region (ltn, arib, kr...). 

So, mixing the jpn0.pgf with your custom pgf file, generated with ttf2pgf, you obtain all is needed in a single file.
And it seems to work:
![2016-09-22-190115](https://cloud.githubusercontent.com/assets/6732619/18758768/a632987c-80f9-11e6-8b5e-d84cab82fa34.jpg)

For the end users, I'll prepare an archive that includes ttf2pgf, mix_pgf and a small batch scrip to generated a proper custom pgf file for vitashell.

For futur, it may be interesting to do something directly in the code (vitashell or libvita2d?) to load default pgf, then replace characters included in the custom pgf if exist.

**Comment by littlebalup** [comment]
here the tool
[ttf2pgf_4vitashell.zip](https://github.com/TheOfficialFloW/VitaShell/files/488153/ttf2pgf_4vitashell.zip)

**Comment by TheOfficialFloW** [comment]
Very nice

**Comment by limyz** [comment]
Awesome work

**Comment by WanderMax** [comment]
great, users can do custom font
