### ISSUE TITLE
Toolbox always translates X as 'confirm'

### ISSUE THREAD

**Issue by Tails32** [TheOfficialFloW/VitaShell#88]
Even though I can use O to open folders and confirm prompts, the new toolbox ignores this

**Comment by WanderMax** [comment]
Yes, me too!

**Comment by theorywrong** [comment]
You use the X and O inversion ?

**Comment by Tails32** [comment]
Yes, I am using the X / O input inversion made possible by the button swap homebrew.

**Comment by WanderMax** [comment]
button swap homebrew too

**Comment by TheOfficialFloW** [comment]
@theorywrong you didn't use SCE_CTRL_ENTER but SCE_CTRL_CROSS..I oversaw that before releasing unfortunately

**Comment by WanderMax** [comment]
thanks flow, it seems that it can be fixed in next release

**Comment by theorywrong** [comment]
@TheOfficialFloW noted for next time :+1:

**Comment by littlebalup** [comment]
Fixed : https://github.com/TheOfficialFloW/VitaShell/commit/51879aa607246bc46d1152155d6657b95a9e6906
