### ISSUE TITLE
Add manual update checker

### ISSUE THREAD

**Issue by WanderMax** [TheOfficialFloW/VitaShell#89]
Auto-update check is not that immediate, I think it will be better to add manual check.

**Comment by limyz** [comment]
You can manually grab the vpk from the releases section if you require an update immediately.

**Comment by WanderMax** [comment]
@limyz yes, you are right. However online update in PSV is much friendly. Thanks.

**Comment by limyz** [comment]
Close your VitaShell app, reopen it and execute the update. It should update to v1.2 normally.
