### ISSUE TITLE
Can merge my code ?

### ISSUE THREAD

**Issue by thhoang99** [TheOfficialFloW/VitaShell#9]
I intervened your code, change many method to make this unofficial vitashell, can we merge code? 
(Almost is dirty code, I do not know how to organize code for correct)

This is demo:
https://mega.nz/#!nAUllRrD!pjJhgR1HuEGTcjR9sBp4uZHaWpWHDRn09S2W4PZ_Blc

+ Compile with your lastest source
+ Touch (experiment)

Sorry for my bad english.

**Comment by limyz** [comment]
Can you upload some images, push your code into your fork or make a pull request instead?

**Comment by TheOfficialFloW** [comment]
Exactly

**Comment by thhoang99** [comment]
my code conflict with Flow's code very much, if i continue my work, afraid will can't merge anymore

**Comment by thhoang99** [comment]
ok so i will fork, i am beginner of git, i need read some docs.

**Comment by TheOfficialFloW** [comment]
Not even src provided to merge.
