### ISSUE TITLE
Compile Error?

### ISSUE THREAD

**Issue by ghost** [TheOfficialFloW/VitaShell#90]
While compiling the latest main brach code:

arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o main.o main.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o init.o init.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o io_process.o io_process.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o package_installer.o package_installer.c
package_installer.c: In function 'loadScePaf':
package_installer.c:40:2: warning: implicit declaration of function 'sceSysmoduleLoadModuleInternalWithArg' [-Wimplicit-function-declaration]
  sceSysmoduleLoadModuleInternalWithArg(0x80000008, sizeof(scepaf_argp), scepaf_argp, ptr);
  ^
package_installer.c: In function 'deleteApp':
package_installer.c:188:8: error: too many arguments to function '_sceAppMgrDestroyAppByName'
  res = _sceAppMgrDestroyAppByName(titleid, temp);
        ^
In file included from main.h:22:0,
                 from package_installer.c:19:
/usr/local/vitasdk/arm-vita-eabi/include/psp2/appmgr.h:74:5: note: declared here
 int _sceAppMgrDestroyAppByName(char *name);
     ^
<builtin>: recipe for target 'package_installer.o' failed
make: *** [package_installer.o] Error 1

**Comment by limyz** [comment]
I didn't come across this issue - did you use the toolchain from jenkins?

**Comment by Yamigami** [comment]
@limyz yep i did

**Comment by limyz** [comment]
Revert to an earlier commit and see if the issue persists.

**Comment by Yamigami** [comment]
@limyz 

As you can see i checked out tree 89bf570 which worked well and compiled
`vita@ubuntu:~/Documents/VitaShell$ git checkout 89bf570c07a234119cbf310c8bfa897d306a9405
Note: checking out '89bf570c07a234119cbf310c8bfa897d306a9405'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 89bf570... Improved list dialog
vita@ubuntu:~/Documents/VitaShell$ make clean && make
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o main.o main.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o init.o init.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o io_process.o io_process.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o package_installer.o package_installer.c
package_installer.c: In function 'loadScePaf':
package_installer.c:39:2: warning: implicit declaration of function 'sceSysmoduleLoadModuleInternalWithArg' [-Wimplicit-function-declaration]
  sceSysmoduleLoadModuleInternalWithArg(0x80000008, sizeof(scepaf_argp), scepaf_argp, ptr);
  ^
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o network_update.o network_update.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o context_menu.o context_menu.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o archive.o archive.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o photo.o photo.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o audioplayer.o audioplayer.c
audioplayer.c: In function 'audioPlayer':
audioplayer.c:151:4: warning: implicit declaration of function 'scePowerRequestDisplayOff' [-Wimplicit-function-declaration]
    scePowerRequestDisplayOff();
    ^
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o file.o file.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o text.o text.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o hex.o hex.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o sfo.o sfo.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o uncommon_dialog.o uncommon_dialog.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o message_dialog.o message_dialog.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o ime_dialog.o ime_dialog.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o config.o config.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o theme.o theme.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o language.o language.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o utils.o utils.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o sha1.o sha1.c
sha1.c: In function 'sha1_final':
sha1.c:124:3: warning: implicit declaration of function 'memset' [-Wimplicit-function-declaration]
   memset(ctx->data, 0, 56);
   ^
sha1.c:124:3: warning: incompatible implicit declaration of built-in function 'memset'
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o list_dialog.o list_dialog.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o minizip/unzip.o minizip/unzip.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o minizip/ioapi.o minizip/ioapi.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o bm.o bm.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o audio/vita_audio.o audio/vita_audio.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o audio/player.o audio/player.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o audio/id3.o audio/id3.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o audio/oggplayer.o audio/oggplayer.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o audio/mp3player.o audio/mp3player.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o audio/mp3xing.o audio/mp3xing.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o libmad/bit.o libmad/bit.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o libmad/decoder.o libmad/decoder.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o libmad/fixed.o libmad/fixed.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o libmad/frame.o libmad/frame.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o libmad/huffman.o libmad/huffman.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o libmad/layer12.o libmad/layer12.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o libmad/layer3.o libmad/layer3.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o libmad/stream.o libmad/stream.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o libmad/synth.o libmad/synth.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o libmad/timer.o libmad/timer.c
arm-vita-eabi-ld -r -b binary -o resources/battery_bar_green.o resources/battery_bar_green.png
arm-vita-eabi-ld -r -b binary -o resources/pause.o resources/pause.png
arm-vita-eabi-ld -r -b binary -o resources/archive_icon.o resources/archive_icon.png
arm-vita-eabi-ld -r -b binary -o resources/play.o resources/play.png
arm-vita-eabi-ld -r -b binary -o resources/ftp.o resources/ftp.png
arm-vita-eabi-ld -r -b binary -o resources/fastforward.o resources/fastforward.png
arm-vita-eabi-ld -r -b binary -o resources/text_icon.o resources/text_icon.png
arm-vita-eabi-ld -r -b binary -o resources/audio_icon.o resources/audio_icon.png
arm-vita-eabi-ld -r -b binary -o resources/battery.o resources/battery.png
arm-vita-eabi-ld -r -b binary -o resources/stop.o resources/stop.png
arm-vita-eabi-ld -r -b binary -o resources/folder_icon.o resources/folder_icon.png
arm-vita-eabi-ld -r -b binary -o resources/battery_bar_charge.o resources/battery_bar_charge.png
arm-vita-eabi-ld -r -b binary -o resources/cover.o resources/cover.png
arm-vita-eabi-ld -r -b binary -o resources/sfo_icon.o resources/sfo_icon.png
arm-vita-eabi-ld -r -b binary -o resources/image_icon.o resources/image_icon.png
arm-vita-eabi-ld -r -b binary -o resources/file_icon.o resources/file_icon.png
arm-vita-eabi-ld -r -b binary -o resources/battery_bar_red.o resources/battery_bar_red.png
arm-vita-eabi-ld -r -b binary -o resources/fastrewind.o resources/fastrewind.png
arm-vita-eabi-ld -r -b binary -o resources/theme.o resources/theme.txt
arm-vita-eabi-ld -r -b binary -o resources/english_us.o resources/english_us.txt
arm-vita-eabi-ld -r -b binary -o resources/colors.o resources/colors.txt
arm-vita-eabi-ld -r -b binary -o resources/changeinfo.o resources/changeinfo.txt
arm-vita-eabi-ld -r -b binary -o resources/updater_eboot.o resources/updater_eboot.bin
arm-vita-eabi-ld -r -b binary -o resources/updater_param.o resources/updater_param.bin
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Wno-unused-variable -Wno-unused-but-set-variable main.o init.o io_process.o package_installer.o network_update.o context_menu.o archive.o photo.o audioplayer.o file.o text.o hex.o sfo.o uncommon_dialog.o message_dialog.o ime_dialog.o config.o theme.o language.o utils.o sha1.o list_dialog.o minizip/unzip.o minizip/ioapi.o bm.o audio/vita_audio.o audio/player.o audio/id3.o audio/oggplayer.o audio/mp3player.o audio/mp3xing.o libmad/bit.o libmad/decoder.o libmad/fixed.o libmad/frame.o libmad/huffman.o libmad/layer12.o libmad/layer3.o libmad/stream.o libmad/synth.o libmad/timer.o resources/battery_bar_green.o resources/pause.o resources/archive_icon.o resources/play.o resources/ftp.o resources/fastforward.o resources/text_icon.o resources/audio_icon.o resources/battery.o resources/stop.o resources/folder_icon.o resources/battery_bar_charge.o resources/cover.o resources/sfo_icon.o resources/image_icon.o resources/file_icon.o resources/battery_bar_red.o resources/fastrewind.o resources/theme.o resources/english_us.o resources/colors.o resources/changeinfo.o resources/updater_eboot.o resources/updater_param.o -lvorbisfile -logg -lvorbis -lftpvita -lvita2d -lpng -ljpeg -lz -lm -lc -lSceAppMgr_stub -lSceAppUtil_stub -lSceCommonDialog_stub -lSceCtrl_stub -lSceDisplay_stub -lSceGxm_stub -lSceIme_stub -lSceHttp_stub -lSceKernel_stub -lSceMusicExport_stub -lSceNet_stub -lSceNetCtl_stub -lSceSsl_stub -lSceSysmodule_stub -lScePhotoExport_stub -lScePower_stub -lScePgf_stub libpromoter/libScePromoterUtil_stub.a -lSceAudio_stub -lSceAudiodec_stub -lSceTouch_stub -o VitaShell.elf
vita-elf-create VitaShell.elf VitaShell.velf libpromoter/promoterutil.json
vita-make-fself VitaShell.velf eboot.bin
vita-mksfoex -d PARENTAL_LEVEL=1 -s APP_VER=01.10 -s TITLE_ID=VITASHELL "VitaShell" param.sfo
vita-pack-vpk -s param.sfo -b eboot.bin \
	--add pkg/sce_sys/icon0.png=sce_sys/icon0.png \
	--add pkg/sce_sys/livearea/contents/bg.png=sce_sys/livearea/contents/bg.png \
	--add pkg/sce_sys/livearea/contents/startup.png=sce_sys/livearea/contents/startup.png \
	--add pkg/sce_sys/livearea/contents/template.xml=sce_sys/livearea/contents/template.xml`

**Comment by littlebalup** [comment]
https://github.com/TheOfficialFloW/VitaShell/commit/a5a12502ac99cf1a2e402b5989861e900f89ab23#commitcomment-19103218

**Comment by dreampiggy** [comment]
change `package_installer.c` 188 line:

```c
char temp[0x100];

res = _sceAppMgrDestroyAppByName(titleid, temp);
```

to 

```c
res = _sceAppMgrDestroyAppByName(titleid);
```

see PR here:
https://github.com/TheOfficialFloW/VitaShell/pull/92/files

**Comment by TheOfficialFloW** [comment]
Don't change `package_installer.c` 188 line. Change this instead: https://github.com/vitasdk/vita-headers/pull/58
