### ISSUE TITLE
VPK install: Error 0xFFFFFFFD

### ISSUE THREAD

**Issue by neon1234** [TheOfficialFloW/VitaShell#94]
Hello,

I'm encountering Error 0xFFFFFFFD whenever I install certain vpk files on VitaShell 1.1 or 1.2.

Haven't tried earlier vitashell versions.

Any idea what this error is about?

Thanks

**Comment by limyz** [comment]
Probably caused by insufficient space in your memory card or a corrupted .vpk.

**Comment by neon1234** [comment]
You are right. The vpk was corrupted. Thanks!
